// Generated by aspeed-data-gen.  DO NOT EDIT.
// Re-run `cargo run -p aspeed-data-gen` to regenerate.

#![no_std]

// AST1060
#[cfg(feature = "ast1060")]
#[path = "chips/ast1060.rs"]
mod ast1060;
#[cfg(feature = "ast1060")]
pub use ast1060::*;

// AST2600
#[cfg(feature = "ast2600")]
#[path = "chips/ast2600.rs"]
mod ast2600;
#[cfg(feature = "ast2600")]
pub use ast2600::*;

// AST2700_BOOTMCU
#[cfg(feature = "ast2700-bootmcu")]
#[path = "chips/ast2700_bootmcu.rs"]
mod ast2700_bootmcu;
#[cfg(feature = "ast2700-bootmcu")]
pub use ast2700_bootmcu::*;

// AST2700_SSP
#[cfg(feature = "ast2700-ssp")]
#[path = "chips/ast2700_ssp.rs"]
mod ast2700_ssp;
#[cfg(feature = "ast2700-ssp")]
pub use ast2700_ssp::*;

// AST2700_TSP
#[cfg(feature = "ast2700-tsp")]
#[path = "chips/ast2700_tsp.rs"]
mod ast2700_tsp;
#[cfg(feature = "ast2700-tsp")]
pub use ast2700_tsp::*;
