// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// AdcV1ADC ASPEED ADC controller block.  8 input channels per instance. AST1060: one instance at 0x7E6E_9000. AST2600: ADC0 at 0x7E6E_9000 (CH0–7), ADC1 at 0x7E6E_9100 (CH8–15).
type AdcV1ADC struct {
    Base uintptr
}

// ReadENGINECTRL reads ADC Engine Control Register (ADC0C, offset 0x00). Controls operating mode, reference voltage, compensation, and per-channel enable. Bit 8 (INIT_RDY) is read-only and indicates the engine has completed initialisation.
func (p *AdcV1ADC) ReadENGINECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteENGINECTRL writes ADC Engine Control Register (ADC0C, offset 0x00). Controls operating mode, reference voltage, compensation, and per-channel enable. Bit 8 (INIT_RDY) is read-only and indicates the engine has completed initialisation.
func (p *AdcV1ADC) WriteENGINECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadINTCTRL reads ADC Interrupt Control Register (ADC04, offset 0x04). Per-channel interrupt enable (bit N enables interrupt for channel N, N=0–7). Interrupt fires when the channel value crosses the threshold set in the VGA_DETECT_CTRL register.
func (p *AdcV1ADC) ReadINTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteINTCTRL writes ADC Interrupt Control Register (ADC04, offset 0x04). Per-channel interrupt enable (bit N enables interrupt for channel N, N=0–7). Interrupt fires when the channel value crosses the threshold set in the VGA_DETECT_CTRL register.
func (p *AdcV1ADC) WriteINTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadVGADETECTCTRL reads VGA Detect Control Register (ADC08, offset 0x08). Holds a 10-bit threshold value and comparison direction per channel. When a channel crosses the threshold and the channel's interrupt is enabled, an ADC interrupt is generated.
func (p *AdcV1ADC) ReadVGADETECTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteVGADETECTCTRL writes VGA Detect Control Register (ADC08, offset 0x08). Holds a 10-bit threshold value and comparison direction per channel. When a channel crosses the threshold and the channel's interrupt is enabled, an ADC interrupt is generated.
func (p *AdcV1ADC) WriteVGADETECTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCLKCTRL reads ADC Clock Control Register (ADC0C, offset 0x0C). 16-bit clock divider: sample_period = PCLK × 2 × (DIV + 1). Set DIV = (PCLK_Hz / (2 × sample_rate_Hz)) - 1.
func (p *AdcV1ADC) ReadCLKCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCLKCTRL writes ADC Clock Control Register (ADC0C, offset 0x0C). 16-bit clock divider: sample_period = PCLK × 2 × (DIV + 1). Set DIV = (PCLK_Hz / (2 × sample_rate_Hz)) - 1.
func (p *AdcV1ADC) WriteCLKCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCH0DATA reads Channel 0 ADC result register (ADC10). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH0DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCH0DATA writes Channel 0 ADC result register (ADC10). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH0DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCH1DATA reads Channel 1 ADC result register (ADC12). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH1DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0012))
}

// WriteCH1DATA writes Channel 1 ADC result register (ADC12). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH1DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0012, uint32(val))
}

// ReadCH2DATA reads Channel 2 ADC result register (ADC14). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH2DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCH2DATA writes Channel 2 ADC result register (ADC14). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH2DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCH3DATA reads Channel 3 ADC result register (ADC16). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH3DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0016))
}

// WriteCH3DATA writes Channel 3 ADC result register (ADC16). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH3DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0016, uint32(val))
}

// ReadCH4DATA reads Channel 4 ADC result register (ADC18). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH4DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteCH4DATA writes Channel 4 ADC result register (ADC18). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH4DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadCH5DATA reads Channel 5 ADC result register (ADC1A). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH5DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001a))
}

// WriteCH5DATA writes Channel 5 ADC result register (ADC1A). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH5DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x001a, uint32(val))
}

// ReadCH6DATA reads Channel 6 ADC result register (ADC1C). Read-only. Bits [9:0].
func (p *AdcV1ADC) ReadCH6DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteCH6DATA writes Channel 6 ADC result register (ADC1C). Read-only. Bits [9:0].
func (p *AdcV1ADC) WriteCH6DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadCH7DATA reads Channel 7 ADC result register (ADC1E). Read-only. Bits [9:0]. This channel can alternatively be used for battery voltage sensing (VBAT/3 or VBAT*2/3) when ENGINE_CTRL.CH7_BAT_MODE = 1.
func (p *AdcV1ADC) ReadCH7DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001e))
}

// WriteCH7DATA writes Channel 7 ADC result register (ADC1E). Read-only. Bits [9:0]. This channel can alternatively be used for battery voltage sensing (VBAT/3 or VBAT*2/3) when ENGINE_CTRL.CH7_BAT_MODE = 1.
func (p *AdcV1ADC) WriteCH7DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x001e, uint32(val))
}

// ReadCOMPENSATIONTRIM reads Compensation Trim Register (ADCC4, offset 0xC4). Factory-programmed calibration value read from OTP (SCU) during init. Written by software after reading SCU OTP; do not set manually.
func (p *AdcV1ADC) ReadCOMPENSATIONTRIM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteCOMPENSATIONTRIM writes Compensation Trim Register (ADCC4, offset 0xC4). Factory-programmed calibration value read from OTP (SCU) during init. Written by software after reading SCU OTP; do not set manually.
func (p *AdcV1ADC) WriteCOMPENSATIONTRIM(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

