// Code generated by chiptool; DO NOT EDIT.

package pac

// Peripheral base addresses
const (
    // SSP_BASE SSP
    SSP_BASE = 0x72c02120
    // GPR_BASE GPR
    GPR_BASE = 0x50000000
    // TIMER0_BASE CPU-die timer block
    TIMER0_BASE = 0x72c10000
    // UART4_BASE CPU-die UART4
    UART4_BASE = 0x72c1a000
    // UART6_BASE IO-die UART6
    UART6_BASE = 0x74c33500
    // GPIO0_BASE CPU-die GPIO bank
    GPIO0_BASE = 0x72c11000
    // GPIO1_BASE IO-die GPIO bank
    GPIO1_BASE = 0x74c0b000
    // WDT0_BASE IO-die watchdog timer 0
    WDT0_BASE = 0x74c37000
    // ADC0_BASE IO-die ADC bank 0
    ADC0_BASE = 0x74c00000
    // ADC1_BASE IO-die ADC bank 1
    ADC1_BASE = 0x74c00100
    // IPC0_BASE IPC0 data-channel bus
    IPC0_BASE = 0x72c1c000
    // INTCG_BASE CPU-die interrupt routing controller (INTCG)
    INTCG_BASE = 0x72100000
    // INTC1G_BASE IO-die interrupt routing controller (INTC1G)
    INTC1G_BASE = 0x74c18000
    // INTC0_11_BASE CPU-die L1 aggregator (NVIC 160-165, parent of INTC1_x)
    INTC0_11_BASE = 0x72102b00
    // INTC1_0_BASE IO-die L2 aggregator 0 (parent bit 0 of INTC0_11)
    INTC1_0_BASE = 0x74c18180
    // INTC1_1_BASE IO-die L2 aggregator 1 (parent bit 1 of INTC0_11)
    INTC1_1_BASE = 0x74c18190
    // INTC1_2_BASE IO-die L2 aggregator 2 (parent bit 2 of INTC0_11)
    INTC1_2_BASE = 0x74c181a0
    // INTC1_3_BASE IO-die L2 aggregator 3 (parent bit 3 of INTC0_11)
    INTC1_3_BASE = 0x74c181b0
    // INTC1_4_BASE IO-die L2 aggregator 4 (parent bit 4 of INTC0_11)
    INTC1_4_BASE = 0x74c181c0
    // INTC1_5_BASE IO-die L2 aggregator 5 (parent bit 5 of INTC0_11)
    INTC1_5_BASE = 0x74c181d0
)

// IRQ numbers
const (
    // TIMER1_IRQ TIMER1
    TIMER1_IRQ = 16
    // TIMER2_IRQ TIMER2
    TIMER2_IRQ = 17
    // TIMER3_IRQ TIMER3
    TIMER3_IRQ = 18
    // TIMER4_IRQ TIMER4
    TIMER4_IRQ = 19
    // TIMER5_IRQ TIMER5
    TIMER5_IRQ = 20
    // TIMER6_IRQ TIMER6
    TIMER6_IRQ = 21
    // TIMER7_IRQ TIMER7
    TIMER7_IRQ = 22
    // TIMER8_IRQ TIMER8
    TIMER8_IRQ = 23
    // WDT_IRQ WDT
    WDT_IRQ = 24
    // GPIO_IRQ GPIO
    GPIO_IRQ = 40
    // UART1_IRQ UART1
    UART1_IRQ = 47
    // UART2_IRQ UART2
    UART2_IRQ = 48
    // UART3_IRQ UART3
    UART3_IRQ = 49
    // UART4_IRQ UART4
    UART4_IRQ = 50
    // UART5_IRQ UART5
    UART5_IRQ = 51
    // UART6_IRQ UART6
    UART6_IRQ = 52
    // UART7_IRQ UART7
    UART7_IRQ = 53
    // UART8_IRQ UART8
    UART8_IRQ = 54
    // INTC0_IRQ INTC0
    INTC0_IRQ = 160
    // INTC1_IRQ INTC1
    INTC1_IRQ = 161
    // INTC2_IRQ INTC2
    INTC2_IRQ = 162
    // INTC3_IRQ INTC3
    INTC3_IRQ = 163
    // INTC4_IRQ INTC4
    INTC4_IRQ = 164
    // INTC5_IRQ INTC5
    INTC5_IRQ = 165
    // IPC_SSP0_IRQ IPC_SSP0
    IPC_SSP0_IRQ = 144
    // IPC_SSP1_IRQ IPC_SSP1
    IPC_SSP1_IRQ = 145
    // IPC_SSP2_IRQ IPC_SSP2
    IPC_SSP2_IRQ = 146
    // IPC_SSP3_IRQ IPC_SSP3
    IPC_SSP3_IRQ = 147
    // IPC_SSP4_IRQ IPC_SSP4
    IPC_SSP4_IRQ = 148
    // IPC_SSP5_IRQ IPC_SSP5
    IPC_SSP5_IRQ = 149
    // IPC_SSP6_IRQ IPC_SSP6
    IPC_SSP6_IRQ = 150
)
