// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// IntcIcAst2700V1INTCIC AST2700 interrupt controller aggregator instance (16 bytes). Each instance aggregates up to 32 interrupt sources into one IRQ line presented to the parent interrupt controller (NVIC or another INTC_IC). IER controls which sources are forwarded; RAW shows and clears pending status.
type IntcIcAst2700V1INTCIC struct {
    Base uintptr
}

// ReadIER reads Interrupt Enable Register. Bit n = 1 enables forwarding of source n to the parent controller. Bit n = 0 masks source n (it will not trigger the parent IRQ). Read to check current enable state.
func (p *IntcIcAst2700V1INTCIC) ReadIER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteIER writes Interrupt Enable Register. Bit n = 1 enables forwarding of source n to the parent controller. Bit n = 0 masks source n (it will not trigger the parent IRQ). Read to check current enable state.
func (p *IntcIcAst2700V1INTCIC) WriteIER(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadRAW reads Raw interrupt status register (write-1-to-clear). Bit n = 1 indicates source n has an active pending interrupt. Write 1 to bit n to acknowledge and clear that interrupt. Only bits that are also enabled in IER will propagate to the parent.
func (p *IntcIcAst2700V1INTCIC) ReadRAW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteRAW writes Raw interrupt status register (write-1-to-clear). Bit n = 1 indicates source n has an active pending interrupt. Write 1 to bit n to acknowledge and clear that interrupt. Only bits that are also enabled in IER will propagate to the parent.
func (p *IntcIcAst2700V1INTCIC) WriteRAW(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

