// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// IntcgAst2700V1INTCG AST2700 CPU-die global interrupt routing controller (INTCG). Routes CPU-die interrupt sources to PSP, SSP, TSP, or BootMCU. Base address (SSP view): 0x72100000. CSEL registers are 32-bit arrays indexed by IRQ group (4 bytes per 32 IRQs).
type IntcgAst2700V1INTCG struct {
    Base uintptr
}

// ReadCSEL0 reads IRQ route select bank 0. Bit n set: this IRQ source uses select code that includes bit 0 = 1. See INTCG architecture description for the 3-bit code encoding. Array: CSEL0[0] covers IRQs 0-31, CSEL0[1] covers IRQs 32-63, etc.
// [n] (n < 12)
func (p *IntcgAst2700V1INTCG) ReadCSEL0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200 + uint32(n)*4))
}

// WriteCSEL0 writes IRQ route select bank 0. Bit n set: this IRQ source uses select code that includes bit 0 = 1. See INTCG architecture description for the 3-bit code encoding. Array: CSEL0[0] covers IRQs 0-31, CSEL0[1] covers IRQs 32-63, etc.
// [n] (n < 12)
func (p *IntcgAst2700V1INTCG) WriteCSEL0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0200+uint32(n)*4, uint32(val))
}

// ReadCSEL1 reads IRQ route select bank 1. Bit n set: this IRQ source uses select code that includes bit 1 = 1.
// [n] (n < 12)
func (p *IntcgAst2700V1INTCG) ReadCSEL1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0300 + uint32(n)*4))
}

// WriteCSEL1 writes IRQ route select bank 1. Bit n set: this IRQ source uses select code that includes bit 1 = 1.
// [n] (n < 12)
func (p *IntcgAst2700V1INTCG) WriteCSEL1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0300+uint32(n)*4, uint32(val))
}

// ReadCSEL2 reads IRQ route select bank 2. Bit n set: this IRQ source uses select code that includes bit 2 = 1.
// [n] (n < 12)
func (p *IntcgAst2700V1INTCG) ReadCSEL2(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0400 + uint32(n)*4))
}

// WriteCSEL2 writes IRQ route select bank 2. Bit n set: this IRQ source uses select code that includes bit 2 = 1.
// [n] (n < 12)
func (p *IntcgAst2700V1INTCG) WriteCSEL2(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0400+uint32(n)*4, uint32(val))
}

