// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// AhbcAst2700V1AHBC AST2700 CPU-die and IO-die AHB matrix debug/control registers. Most fields are reserved in the public datasheet; timeout controls are named because BootMCU disables them while calibrating SLI links.
type AhbcAst2700V1AHBC struct {
    Base uintptr
}

// ReadPORTSTATUS0 reads Per-port reserved debug/status register 0.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadPORTSTATUS0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000 + uint32(n)*64))
}

// ReadPORTSTATUS1 reads Per-port reserved debug/status register 1.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadPORTSTATUS1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004 + uint32(n)*64))
}

// ReadPORTSTATUS2 reads Per-port reserved debug/status register 2.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadPORTSTATUS2(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008 + uint32(n)*64))
}

// ReadPORTSTATUS3 reads Per-port reserved debug/status register 3.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadPORTSTATUS3(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c + uint32(n)*64))
}

// ReadPORTSTATUS4 reads Per-port reserved debug/status register 4.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadPORTSTATUS4(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010 + uint32(n)*64))
}

// ReadPORTSTATUS5 reads Per-port reserved debug/status register 5.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadPORTSTATUS5(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014 + uint32(n)*64))
}

// ReadTIMEOUTCLEAR reads Per-port timeout clear registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadTIMEOUTCLEAR(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030 + uint32(n)*64))
}

// WriteTIMEOUTCLEAR writes Per-port timeout clear registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) WriteTIMEOUTCLEAR(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0030+uint32(n)*64, uint32(val))
}

// ReadTIMEOUT reads Per-port timeout control registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadTIMEOUT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034 + uint32(n)*64))
}

// WriteTIMEOUT writes Per-port timeout control registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) WriteTIMEOUT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0034+uint32(n)*64, uint32(val))
}

// ReadTIMEOUTSTATUS reads Per-port timeout status registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadTIMEOUTSTATUS(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038 + uint32(n)*64))
}

// ReadTIMEOUTSOURCE reads Per-port timeout source/status registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadTIMEOUTSOURCE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c + uint32(n)*64))
}

// ReadMASTERCTRL0 reads Reserved AHB matrix control register.
func (p *AhbcAst2700V1AHBC) ReadMASTERCTRL0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// WriteMASTERCTRL0 writes Reserved AHB matrix control register.
func (p *AhbcAst2700V1AHBC) WriteMASTERCTRL0(val uint32) {
    reg.Write(uint32(p.Base)+0x0200, uint32(val))
}

// ReadMASTERCTRL1 reads Reserved AHB matrix control register.
func (p *AhbcAst2700V1AHBC) ReadMASTERCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// WriteMASTERCTRL1 writes Reserved AHB matrix control register.
func (p *AhbcAst2700V1AHBC) WriteMASTERCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x0204, uint32(val))
}

// ReadMASTERSTATUS0 reads Reserved AHB matrix status register.
func (p *AhbcAst2700V1AHBC) ReadMASTERSTATUS0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0208))
}

// ReadMASTERSTATUS1 reads Reserved AHB matrix status register.
func (p *AhbcAst2700V1AHBC) ReadMASTERSTATUS1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x020c))
}

// ReadMASTERCONFIG0 reads Reserved AHB matrix configuration register.
func (p *AhbcAst2700V1AHBC) ReadMASTERCONFIG0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0210))
}

// WriteMASTERCONFIG0 writes Reserved AHB matrix configuration register.
func (p *AhbcAst2700V1AHBC) WriteMASTERCONFIG0(val uint32) {
    reg.Write(uint32(p.Base)+0x0210, uint32(val))
}

// ReadMASTERCONFIG1 reads Reserved AHB matrix configuration register.
func (p *AhbcAst2700V1AHBC) ReadMASTERCONFIG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0214))
}

// WriteMASTERCONFIG1 writes Reserved AHB matrix configuration register.
func (p *AhbcAst2700V1AHBC) WriteMASTERCONFIG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0214, uint32(val))
}

// ReadMASTERENABLE reads Reserved AHB matrix per-master enable registers.[n] (n < 2)
func (p *AhbcAst2700V1AHBC) ReadMASTERENABLE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0218 + uint32(n)*4))
}

// WriteMASTERENABLE writes Reserved AHB matrix per-master enable registers.[n] (n < 2)
func (p *AhbcAst2700V1AHBC) WriteMASTERENABLE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0218+uint32(n)*4, uint32(val))
}

// ReadWINDOWCFG reads Reserved AHB matrix window configuration registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadWINDOWCFG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0220 + uint32(n)*4))
}

// WriteWINDOWCFG writes Reserved AHB matrix window configuration registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) WriteWINDOWCFG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0220+uint32(n)*4, uint32(val))
}

// ReadWINDOWCFGEXT reads Reserved AHB matrix window configuration registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) ReadWINDOWCFGEXT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0260 + uint32(n)*4))
}

// WriteWINDOWCFGEXT writes Reserved AHB matrix window configuration registers.[n] (n < 8)
func (p *AhbcAst2700V1AHBC) WriteWINDOWCFGEXT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0260+uint32(n)*4, uint32(val))
}

// ReadINTERRUPTCTRL reads Reserved AHB matrix interrupt control register.
func (p *AhbcAst2700V1AHBC) ReadINTERRUPTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02a0))
}

// WriteINTERRUPTCTRL writes Reserved AHB matrix interrupt control register.
func (p *AhbcAst2700V1AHBC) WriteINTERRUPTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x02a0, uint32(val))
}

// ReadINTERRUPTSTATUS reads Reserved AHB matrix interrupt status register.
func (p *AhbcAst2700V1AHBC) ReadINTERRUPTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02a4))
}

// ReadDEBUGCTRL reads Reserved AHB matrix debug control register.
func (p *AhbcAst2700V1AHBC) ReadDEBUGCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02a8))
}

// WriteDEBUGCTRL writes Reserved AHB matrix debug control register.
func (p *AhbcAst2700V1AHBC) WriteDEBUGCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x02a8, uint32(val))
}

// ReadDEBUGSTATUS reads Reserved AHB matrix debug status register.
func (p *AhbcAst2700V1AHBC) ReadDEBUGSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02ac))
}

// ReadID reads Reserved AHB matrix ID/status register.
func (p *AhbcAst2700V1AHBC) ReadID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02fc))
}

