// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// CaliptraIfcV1IFC Caliptra integration interface used for boot status, error reporting, and TRNG handoff.
type CaliptraIfcV1IFC struct {
    Base uintptr
}

// ReadHWERRORFATAL reads Fatal hardware error status.
func (p *CaliptraIfcV1IFC) ReadHWERRORFATAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteHWERRORFATAL writes Fatal hardware error status.
func (p *CaliptraIfcV1IFC) WriteHWERRORFATAL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadHWERRORNONFATAL reads Non-fatal hardware error status.
func (p *CaliptraIfcV1IFC) ReadHWERRORNONFATAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteHWERRORNONFATAL writes Non-fatal hardware error status.
func (p *CaliptraIfcV1IFC) WriteHWERRORNONFATAL(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadFWERRORFATAL reads Fatal firmware error status.
func (p *CaliptraIfcV1IFC) ReadFWERRORFATAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteFWERRORFATAL writes Fatal firmware error status.
func (p *CaliptraIfcV1IFC) WriteFWERRORFATAL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadFWERRORNONFATAL reads Non-fatal firmware error status.
func (p *CaliptraIfcV1IFC) ReadFWERRORNONFATAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteFWERRORNONFATAL writes Non-fatal firmware error status.
func (p *CaliptraIfcV1IFC) WriteFWERRORNONFATAL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadBOOTSTS reads Caliptra boot status register.
func (p *CaliptraIfcV1IFC) ReadBOOTSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteBOOTSTS writes Caliptra boot status register.
func (p *CaliptraIfcV1IFC) WriteBOOTSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadFLOWSTS reads Caliptra boot/runtime flow status register.
func (p *CaliptraIfcV1IFC) ReadFLOWSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteFLOWSTS writes Caliptra boot/runtime flow status register.
func (p *CaliptraIfcV1IFC) WriteFLOWSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadRSTREASON reads Caliptra reset reason register.
func (p *CaliptraIfcV1IFC) ReadRSTREASON() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteRSTREASON writes Caliptra reset reason register.
func (p *CaliptraIfcV1IFC) WriteRSTREASON(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadTRNGDATA reads External TRNG data words supplied by BootMCU.[n] (n < 12)
func (p *CaliptraIfcV1IFC) ReadTRNGDATA(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078 + uint32(n)*4))
}

// WriteTRNGDATA writes External TRNG data words supplied by BootMCU.[n] (n < 12)
func (p *CaliptraIfcV1IFC) WriteTRNGDATA(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0078+uint32(n)*4, uint32(val))
}

// ReadTRNGSTS reads External TRNG request/completion status.
func (p *CaliptraIfcV1IFC) ReadTRNGSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteTRNGSTS writes External TRNG request/completion status.
func (p *CaliptraIfcV1IFC) WriteTRNGSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

