// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// CaliptraMboxV1MBOX Caliptra mailbox command/data transport used by the BootMCU.
type CaliptraMboxV1MBOX struct {
    Base uintptr
}

// ReadLOCK reads Mailbox lock register. Read returns lock owner state; write requests the lock.
func (p *CaliptraMboxV1MBOX) ReadLOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteLOCK writes Mailbox lock register. Read returns lock owner state; write requests the lock.
func (p *CaliptraMboxV1MBOX) WriteLOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadUSER reads Mailbox user register identifying the current lock owner.
func (p *CaliptraMboxV1MBOX) ReadUSER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteUSER writes Mailbox user register identifying the current lock owner.
func (p *CaliptraMboxV1MBOX) WriteUSER(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCMD reads Four-byte mailbox command code.
func (p *CaliptraMboxV1MBOX) ReadCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCMD writes Four-byte mailbox command code.
func (p *CaliptraMboxV1MBOX) WriteCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadDLEN reads Mailbox data length in bytes.
func (p *CaliptraMboxV1MBOX) ReadDLEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteDLEN writes Mailbox data length in bytes.
func (p *CaliptraMboxV1MBOX) WriteDLEN(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadDATAIN reads Mailbox input FIFO. Write checksum word first, then command payload words.
func (p *CaliptraMboxV1MBOX) ReadDATAIN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteDATAIN writes Mailbox input FIFO. Write checksum word first, then command payload words.
func (p *CaliptraMboxV1MBOX) WriteDATAIN(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadDATAOUT reads Mailbox output FIFO. Read response words before releasing the mailbox lock.
func (p *CaliptraMboxV1MBOX) ReadDATAOUT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteDATAOUT writes Mailbox output FIFO. Read response words before releasing the mailbox lock.
func (p *CaliptraMboxV1MBOX) WriteDATAOUT(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadEXEC reads Execute register. Write 1 after CMD, DLEN, and DATAIN are prepared.
func (p *CaliptraMboxV1MBOX) ReadEXEC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteEXEC writes Execute register. Write 1 after CMD, DLEN, and DATAIN are prepared.
func (p *CaliptraMboxV1MBOX) WriteEXEC(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadSTS reads Mailbox status and finite-state-machine state.
func (p *CaliptraMboxV1MBOX) ReadSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteSTS writes Mailbox status and finite-state-machine state.
func (p *CaliptraMboxV1MBOX) WriteSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadUNLOCK reads Mailbox unlock register. Write after command completion and DATAOUT drain.
func (p *CaliptraMboxV1MBOX) ReadUNLOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteUNLOCK writes Mailbox unlock register. Write after command completion and DATAOUT drain.
func (p *CaliptraMboxV1MBOX) WriteUNLOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

