// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// DdrphyAst2700V1DDRPHYAPB DWC DDR PHY APB register aperture. PHY register addresses are 16-bit word addresses; the BootMCU byte offset is APB address * 2. The public datasheet leaves PUB/training details to the SDK, while the internal bring-up notes identify the INITENG, UCT mailbox, and DRTUB control sub-windows below.
type DdrphyAst2700V1DDRPHYAPB struct {
    Base uintptr
}

// ReadWORD reads 16-bit PHY APB word array covering PUB, INITENG, UCT, and DRTUB windows.[n] (n < 1048576)
func (p *DdrphyAst2700V1DDRPHYAPB) ReadWORD(n uintptr) uint16 {
    return uint16(reg.Read(uint32(p.Base) + 0x0000 + uint32(n)*2))
}

// WriteWORD writes 16-bit PHY APB word array covering PUB, INITENG, UCT, and DRTUB windows.[n] (n < 1048576)
func (p *DdrphyAst2700V1DDRPHYAPB) WriteWORD(n uintptr, val uint16) {
    reg.Write(uint32(p.Base)+0x0000+uint32(n)*2, uint32(val))
}

// ReadCALZAP reads PHY calibration zap control used before mission-mode DFI initialization.
func (p *DdrphyAst2700V1DDRPHYAPB) ReadCALZAP() uint16 {
    return uint16(reg.Read(uint32(p.Base) + 0x40112))
}

// WriteCALZAP writes PHY calibration zap control used before mission-mode DFI initialization.
func (p *DdrphyAst2700V1DDRPHYAPB) WriteCALZAP(val uint16) {
    reg.Write(uint32(p.Base)+0x40112, uint32(val))
}

// ReadINITENG reads PHY Init Engine (PIE) sequencer program window.[n] (n < 256)
func (p *DdrphyAst2700V1DDRPHYAPB) ReadINITENG(n uintptr) uint16 {
    return uint16(reg.Read(uint32(p.Base) + 0x120000 + uint32(n)*2))
}

// WriteINITENG writes PHY Init Engine (PIE) sequencer program window.[n] (n < 256)
func (p *DdrphyAst2700V1DDRPHYAPB) WriteINITENG(n uintptr, val uint16) {
    reg.Write(uint32(p.Base)+0x120000+uint32(n)*2, uint32(val))
}

// ReadUCTMAILBOX reads PHY microcontroller mailbox window.[n] (n < 32)
func (p *DdrphyAst2700V1DDRPHYAPB) ReadUCTMAILBOX(n uintptr) uint16 {
    return uint16(reg.Read(uint32(p.Base) + 0x180000 + uint32(n)*2))
}

// WriteUCTMAILBOX writes PHY microcontroller mailbox window.[n] (n < 32)
func (p *DdrphyAst2700V1DDRPHYAPB) WriteUCTMAILBOX(n uintptr, val uint16) {
    reg.Write(uint32(p.Base)+0x180000+uint32(n)*2, uint32(val))
}

// ReadMICROCONTMUXSEL reads Microcontroller/APB CSR mux selection; set to isolate APB while firmware runs.
func (p *DdrphyAst2700V1DDRPHYAPB) ReadMICROCONTMUXSEL() uint16 {
    return uint16(reg.Read(uint32(p.Base) + 0x1a0000))
}

// WriteMICROCONTMUXSEL writes Microcontroller/APB CSR mux selection; set to isolate APB while firmware runs.
func (p *DdrphyAst2700V1DDRPHYAPB) WriteMICROCONTMUXSEL(val uint16) {
    reg.Write(uint32(p.Base)+0x1a0000, uint32(val))
}

// ReadMICRORESET reads PHY microcontroller reset/stall control.
func (p *DdrphyAst2700V1DDRPHYAPB) ReadMICRORESET() uint16 {
    return uint16(reg.Read(uint32(p.Base) + 0x1a0132))
}

// WriteMICRORESET writes PHY microcontroller reset/stall control.
func (p *DdrphyAst2700V1DDRPHYAPB) WriteMICRORESET(val uint16) {
    reg.Write(uint32(p.Base)+0x1a0132, uint32(val))
}

