// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// DdrphyAst2700V1DDRPHYMEM DWC DDR PHY instruction/data memory window used for loading training firmware. Although the PHY firmware is organized as 16-bit words, this AHB-to-APB SRAM path requires word-aligned 32-bit transactions.
type DdrphyAst2700V1DDRPHYMEM struct {
    Base uintptr
}

// ReadDWORD reads 32-bit access words for PHY IMEM/DMEM firmware loading.[n] (n < 16384)
func (p *DdrphyAst2700V1DDRPHYMEM) ReadDWORD(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000 + uint32(n)*4))
}

// WriteDWORD writes 32-bit access words for PHY IMEM/DMEM firmware loading.[n] (n < 16384)
func (p *DdrphyAst2700V1DDRPHYMEM) WriteDWORD(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0000+uint32(n)*4, uint32(val))
}

