// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// DpAst2700V1DPMCUREG DisplayPort MCU control register window.
type DpAst2700V1DPMCUREG struct {
    Base uintptr
}

// ReadREGBANK reads DP MCU register bank words 0..31.[n] (n < 32)
func (p *DpAst2700V1DPMCUREG) ReadREGBANK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000 + uint32(n)*4))
}

// ReadPAUSECTRL reads DP MCU pause control and status.
func (p *DpAst2700V1DPMCUREG) ReadPAUSECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WritePAUSECTRL writes DP MCU pause control and status.
func (p *DpAst2700V1DPMCUREG) WritePAUSECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadBREAKPOINT reads DP MCU program-counter breakpoint configuration.
func (p *DpAst2700V1DPMCUREG) ReadBREAKPOINT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteBREAKPOINT writes DP MCU program-counter breakpoint configuration.
func (p *DpAst2700V1DPMCUREG) WriteBREAKPOINT(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadPCNEXT reads DP MCU next program counter.
func (p *DpAst2700V1DPMCUREG) ReadPCNEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// ReadPCCURRENT reads DP MCU current program counter.
func (p *DpAst2700V1DPMCUREG) ReadPCCURRENT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// ReadINSTNEXT reads Instruction at the next program counter.
func (p *DpAst2700V1DPMCUREG) ReadINSTNEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// ReadINSTCURRENT reads Instruction at the current program counter.
func (p *DpAst2700V1DPMCUREG) ReadINSTCURRENT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// ReadINTENABLESTATUS reads Interrupt enable bits controlled by DPMCU INTEN.
func (p *DpAst2700V1DPMCUREG) ReadINTENABLESTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// ReadINTSOURCESTATUS reads Interrupt sources viewed by DP MCU.
func (p *DpAst2700V1DPMCUREG) ReadINTSOURCESTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// ReadVERSION reads DP MCU version.
func (p *DpAst2700V1DPMCUREG) ReadVERSION() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// ReadCTRL reads DisplayPort MCU memory
func (p *DpAst2700V1DPMCUREG) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteCTRL writes DisplayPort MCU memory
func (p *DpAst2700V1DPMCUREG) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadINTRCTRL reads DisplayPort MCU interrupt clear
func (p *DpAst2700V1DPMCUREG) ReadINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e8))
}

// WriteINTRCTRL writes DisplayPort MCU interrupt clear
func (p *DpAst2700V1DPMCUREG) WriteINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00e8, uint32(val))
}

// ReadINTRSTATUS reads DisplayPort MCU interrupt status.
func (p *DpAst2700V1DPMCUREG) ReadINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec))
}

