// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// DpAst2700V1DP AST2700 DisplayPort transmitter controller registers.
type DpAst2700V1DP struct {
    Base uintptr
}

// ReadCPUINTRCTRL reads Interrupt-to-CPU configuration.
func (p *DpAst2700V1DP) ReadCPUINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCPUINTRCTRL writes Interrupt-to-CPU configuration.
func (p *DpAst2700V1DP) WriteCPUINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCPUINTRSTATUS reads Interrupt-to-CPU status.
func (p *DpAst2700V1DP) ReadCPUINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// ReadCPUSWINTRCTRL reads Software interrupt-to-CPU configuration.
func (p *DpAst2700V1DP) ReadCPUSWINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCPUSWINTRCTRL writes Software interrupt-to-CPU configuration.
func (p *DpAst2700V1DP) WriteCPUSWINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCPUSWINTRSTATUS reads Software interrupt-to-CPU status.
func (p *DpAst2700V1DP) ReadCPUSWINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// ReadCPUTIMER0CTRL reads CPU timer 0 warning configuration.
func (p *DpAst2700V1DP) ReadCPUTIMER0CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCPUTIMER0CTRL writes CPU timer 0 warning configuration.
func (p *DpAst2700V1DP) WriteCPUTIMER0CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCPUTIMER0RELOAD reads CPU timer 0 reload configuration.
func (p *DpAst2700V1DP) ReadCPUTIMER0RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCPUTIMER0RELOAD writes CPU timer 0 reload configuration.
func (p *DpAst2700V1DP) WriteCPUTIMER0RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCPUTIMER0STATUS reads CPU timer 0 status and current count.
func (p *DpAst2700V1DP) ReadCPUTIMER0STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteCPUTIMER0STATUS writes CPU timer 0 status and current count.
func (p *DpAst2700V1DP) WriteCPUTIMER0STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadVERSION reads DisplayPort controller version register.
func (p *DpAst2700V1DP) ReadVERSION() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// ReadCPUTIMER1CTRL reads CPU timer 1 warning configuration.
func (p *DpAst2700V1DP) ReadCPUTIMER1CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteCPUTIMER1CTRL writes CPU timer 1 warning configuration.
func (p *DpAst2700V1DP) WriteCPUTIMER1CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadCPUTIMER1RELOAD reads CPU timer 1 reload configuration.
func (p *DpAst2700V1DP) ReadCPUTIMER1RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteCPUTIMER1RELOAD writes CPU timer 1 reload configuration.
func (p *DpAst2700V1DP) WriteCPUTIMER1RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadCPUTIMER1STATUS reads CPU timer 1 status and current count.
func (p *DpAst2700V1DP) ReadCPUTIMER1STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteCPUTIMER1STATUS writes CPU timer 1 status and current count.
func (p *DpAst2700V1DP) WriteCPUTIMER1STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadMCUINTRCTRL reads Interrupt-to-MCU configuration.
func (p *DpAst2700V1DP) ReadMCUINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteMCUINTRCTRL writes Interrupt-to-MCU configuration.
func (p *DpAst2700V1DP) WriteMCUINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadMCUINTRSTATUS reads Interrupt-to-MCU status.
func (p *DpAst2700V1DP) ReadMCUINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// ReadMCUSWINTRCTRL reads Software interrupt-to-MCU configuration.
func (p *DpAst2700V1DP) ReadMCUSWINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteMCUSWINTRCTRL writes Software interrupt-to-MCU configuration.
func (p *DpAst2700V1DP) WriteMCUSWINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadMCUSWINTRSTATUS reads Software interrupt-to-MCU status.
func (p *DpAst2700V1DP) ReadMCUSWINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// ReadMCUTIMER0CTRL reads MCU timer 0 warning configuration.
func (p *DpAst2700V1DP) ReadMCUTIMER0CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteMCUTIMER0CTRL writes MCU timer 0 warning configuration.
func (p *DpAst2700V1DP) WriteMCUTIMER0CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadMCUTIMER0RELOAD reads MCU timer 0 reload configuration.
func (p *DpAst2700V1DP) ReadMCUTIMER0RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteMCUTIMER0RELOAD writes MCU timer 0 reload configuration.
func (p *DpAst2700V1DP) WriteMCUTIMER0RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadMCUTIMER0STATUS reads MCU timer 0 status and current count.
func (p *DpAst2700V1DP) ReadMCUTIMER0STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteMCUTIMER0STATUS writes MCU timer 0 status and current count.
func (p *DpAst2700V1DP) WriteMCUTIMER0STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadMCUTIMER1CTRL reads MCU timer 1 warning configuration.
func (p *DpAst2700V1DP) ReadMCUTIMER1CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteMCUTIMER1CTRL writes MCU timer 1 warning configuration.
func (p *DpAst2700V1DP) WriteMCUTIMER1CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadMCUTIMER1RELOAD reads MCU timer 1 reload configuration.
func (p *DpAst2700V1DP) ReadMCUTIMER1RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteMCUTIMER1RELOAD writes MCU timer 1 reload configuration.
func (p *DpAst2700V1DP) WriteMCUTIMER1RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadMCUTIMER1STATUS reads MCU timer 1 status and current count.
func (p *DpAst2700V1DP) ReadMCUTIMER1STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteMCUTIMER1STATUS writes MCU timer 1 status and current count.
func (p *DpAst2700V1DP) WriteMCUTIMER1STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadHPDSTATUS reads Hot-plug detect status.
func (p *DpAst2700V1DP) ReadHPDSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// ReadHPDIRQCFG reads HPD IRQ low-period bounds.
func (p *DpAst2700V1DP) ReadHPDIRQCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteHPDIRQCFG writes HPD IRQ low-period bounds.
func (p *DpAst2700V1DP) WriteHPDIRQCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadHPDEVENTCFG reads HPD event low-period threshold.
func (p *DpAst2700V1DP) ReadHPDEVENTCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteHPDEVENTCFG writes HPD event low-period threshold.
func (p *DpAst2700V1DP) WriteHPDEVENTCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadAUXREQCTRL reads AUX request command control and status.
func (p *DpAst2700V1DP) ReadAUXREQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteAUXREQCTRL writes AUX request command control and status.
func (p *DpAst2700V1DP) WriteAUXREQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadAUXREQADDR reads AUX request length and address.
func (p *DpAst2700V1DP) ReadAUXREQADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteAUXREQADDR writes AUX request length and address.
func (p *DpAst2700V1DP) WriteAUXREQADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadAUXREQDATA reads AUX request data bytes 0..15.[n] (n < 4)
func (p *DpAst2700V1DP) ReadAUXREQDATA(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090 + uint32(n)*4))
}

// WriteAUXREQDATA writes AUX request data bytes 0..15.[n] (n < 4)
func (p *DpAst2700V1DP) WriteAUXREQDATA(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0090+uint32(n)*4, uint32(val))
}

// ReadAUXREPLYDATA reads AUX reply data bytes 0..15.[n] (n < 4)
func (p *DpAst2700V1DP) ReadAUXREPLYDATA(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0 + uint32(n)*4))
}

// ReadAUXREPLYSTATUS reads AUX reply command and status.
func (p *DpAst2700V1DP) ReadAUXREPLYSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// ReadAUXREPLYCFG reads AUX reply timeout and loopback configuration.
func (p *DpAst2700V1DP) ReadAUXREPLYCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteAUXREPLYCFG writes AUX reply timeout and loopback configuration.
func (p *DpAst2700V1DP) WriteAUXREPLYCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadHANDSHAKE reads Display ownership and EDID handoff control.
func (p *DpAst2700V1DP) ReadHANDSHAKE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteHANDSHAKE writes Display ownership and EDID handoff control.
func (p *DpAst2700V1DP) WriteHANDSHAKE(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadLINKCFG reads Main link configuration.
func (p *DpAst2700V1DP) ReadLINKCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteLINKCFG writes Main link configuration.
func (p *DpAst2700V1DP) WriteLINKCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadLINKMVIDHW reads Hardware MVID and VB-ID configuration.
func (p *DpAst2700V1DP) ReadLINKMVIDHW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteLINKMVIDHW writes Hardware MVID and VB-ID configuration.
func (p *DpAst2700V1DP) WriteLINKMVIDHW(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadMSAMVID reads MSA MVID set by firmware.
func (p *DpAst2700V1DP) ReadMSAMVID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteMSAMVID writes MSA MVID set by firmware.
func (p *DpAst2700V1DP) WriteMSAMVID(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadMSANVID reads MSA NVID.
func (p *DpAst2700V1DP) ReadMSANVID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteMSANVID writes MSA NVID.
func (p *DpAst2700V1DP) WriteMSANVID(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadMSATOTAL reads MSA vertical and horizontal total.
func (p *DpAst2700V1DP) ReadMSATOTAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// WriteMSATOTAL writes MSA vertical and horizontal total.
func (p *DpAst2700V1DP) WriteMSATOTAL(val uint32) {
    reg.Write(uint32(p.Base)+0x00d0, uint32(val))
}

// ReadMSASTART reads MSA vertical and horizontal start.
func (p *DpAst2700V1DP) ReadMSASTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteMSASTART writes MSA vertical and horizontal start.
func (p *DpAst2700V1DP) WriteMSASTART(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadMSASIZE reads MSA vertical height and horizontal width.
func (p *DpAst2700V1DP) ReadMSASIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteMSASIZE writes MSA vertical height and horizontal width.
func (p *DpAst2700V1DP) WriteMSASIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadMSASYNC reads MSA vertical and horizontal sync width.
func (p *DpAst2700V1DP) ReadMSASYNC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00dc))
}

// WriteMSASYNC writes MSA vertical and horizontal sync width.
func (p *DpAst2700V1DP) WriteMSASYNC(val uint32) {
    reg.Write(uint32(p.Base)+0x00dc, uint32(val))
}

// ReadMSAMISC reads MSA misc0 and misc1 packet bytes.
func (p *DpAst2700V1DP) ReadMSAMISC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteMSAMISC writes MSA misc0 and misc1 packet bytes.
func (p *DpAst2700V1DP) WriteMSAMISC(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadTRAININGPATTERN reads Link training and quality pattern configuration.
func (p *DpAst2700V1DP) ReadTRAININGPATTERN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e4))
}

// WriteTRAININGPATTERN writes Link training and quality pattern configuration.
func (p *DpAst2700V1DP) WriteTRAININGPATTERN(val uint32) {
    reg.Write(uint32(p.Base)+0x00e4, uint32(val))
}

// ReadDIGITALPHYCFG reads Main link digital PHY configuration.
func (p *DpAst2700V1DP) ReadDIGITALPHYCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e8))
}

// WriteDIGITALPHYCFG writes Main link digital PHY configuration.
func (p *DpAst2700V1DP) WriteDIGITALPHYCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x00e8, uint32(val))
}

// ReadCUSTOMPATTERN reads 80-bit custom encoder test pattern.[n] (n < 3)
func (p *DpAst2700V1DP) ReadCUSTOMPATTERN(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec + uint32(n)*4))
}

// WriteCUSTOMPATTERN writes 80-bit custom encoder test pattern.[n] (n < 3)
func (p *DpAst2700V1DP) WriteCUSTOMPATTERN(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x00ec+uint32(n)*4, uint32(val))
}

// ReadLINKFWCFG reads Firmware-defined main link configuration.
func (p *DpAst2700V1DP) ReadLINKFWCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f8))
}

// WriteLINKFWCFG writes Firmware-defined main link configuration.
func (p *DpAst2700V1DP) WriteLINKFWCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x00f8, uint32(val))
}

// ReadLINKSTATUS reads Link training and packet FSM status.
func (p *DpAst2700V1DP) ReadLINKSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00fc))
}

// WriteLINKSTATUS writes Link training and packet FSM status.
func (p *DpAst2700V1DP) WriteLINKSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x00fc, uint32(val))
}

// ReadTXCFG reads DisplayPort transmitter reset and clock configuration.
func (p *DpAst2700V1DP) ReadTXCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100))
}

// WriteTXCFG writes DisplayPort transmitter reset and clock configuration.
func (p *DpAst2700V1DP) WriteTXCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0100, uint32(val))
}

// ReadPHYCTRL reads DP PHY power
func (p *DpAst2700V1DP) ReadPHYCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0104))
}

// WritePHYCTRL writes DP PHY power
func (p *DpAst2700V1DP) WritePHYCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0104, uint32(val))
}

// ReadPHYLANECFG reads DP PHY lane swing
func (p *DpAst2700V1DP) ReadPHYLANECFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108))
}

// WritePHYLANECFG writes DP PHY lane swing
func (p *DpAst2700V1DP) WritePHYLANECFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0108, uint32(val))
}

// ReadPHYAUXSTATUS reads DP PHY AUX status.
func (p *DpAst2700V1DP) ReadPHYAUXSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x010c))
}

// ReadPHYVENDORCFG0 reads DP PHY vendor control and debug selection.
func (p *DpAst2700V1DP) ReadPHYVENDORCFG0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110))
}

// WritePHYVENDORCFG0 writes DP PHY vendor control and debug selection.
func (p *DpAst2700V1DP) WritePHYVENDORCFG0(val uint32) {
    reg.Write(uint32(p.Base)+0x0110, uint32(val))
}

// ReadPHYVENDORSTATUS reads DP PHY vendor status.
func (p *DpAst2700V1DP) ReadPHYVENDORSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0114))
}

// ReadPHYVENDORCFG reads DP PHY vendor reserved configuration words.[n] (n < 5)
func (p *DpAst2700V1DP) ReadPHYVENDORCFG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0118 + uint32(n)*4))
}

// WritePHYVENDORCFG writes DP PHY vendor reserved configuration words.[n] (n < 5)
func (p *DpAst2700V1DP) WritePHYVENDORCFG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0118+uint32(n)*4, uint32(val))
}

// ReadPHYCLKCFG reads DP PHY reference clock selection.
func (p *DpAst2700V1DP) ReadPHYCLKCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c))
}

// WritePHYCLKCFG writes DP PHY reference clock selection.
func (p *DpAst2700V1DP) WritePHYCLKCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x012c, uint32(val))
}

// ReadPHYRXDATALATCH reads Feedback symbol latch command and shift selection.
func (p *DpAst2700V1DP) ReadPHYRXDATALATCH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WritePHYRXDATALATCH writes Feedback symbol latch command and shift selection.
func (p *DpAst2700V1DP) WritePHYRXDATALATCH(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadPHYRXDATALATCHAUTO reads Automatic feedback symbol shift selection.
func (p *DpAst2700V1DP) ReadPHYRXDATALATCHAUTO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x013c))
}

// ReadPHYMAIN0RXDATA reads Latched feedback symbols for lane 0.[n] (n < 4)
func (p *DpAst2700V1DP) ReadPHYMAIN0RXDATA(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140 + uint32(n)*4))
}

// ReadPHYMAIN1RXDATA reads Latched feedback symbols for lane 1.[n] (n < 4)
func (p *DpAst2700V1DP) ReadPHYMAIN1RXDATA(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0150 + uint32(n)*4))
}

// ReadVGAINTRCTRL reads Interrupt-to-VGA configuration.
func (p *DpAst2700V1DP) ReadVGAINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0160))
}

// WriteVGAINTRCTRL writes Interrupt-to-VGA configuration.
func (p *DpAst2700V1DP) WriteVGAINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0160, uint32(val))
}

// ReadVGAINTRSTATUS reads Interrupt-to-VGA status.
func (p *DpAst2700V1DP) ReadVGAINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0164))
}

// ReadVGASWINTRCTRL reads Software interrupt-to-VGA configuration.
func (p *DpAst2700V1DP) ReadVGASWINTRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// WriteVGASWINTRCTRL writes Software interrupt-to-VGA configuration.
func (p *DpAst2700V1DP) WriteVGASWINTRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0168, uint32(val))
}

// ReadVGASWINTRSTATUS reads Software interrupt-to-VGA status.
func (p *DpAst2700V1DP) ReadVGASWINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x016c))
}

// ReadVIDEOLINEBUFCFG reads Video line buffer configuration.
func (p *DpAst2700V1DP) ReadVIDEOLINEBUFCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0180))
}

// WriteVIDEOLINEBUFCFG writes Video line buffer configuration.
func (p *DpAst2700V1DP) WriteVIDEOLINEBUFCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0180, uint32(val))
}

