// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// Ftgmac100V1FTGMAC100 Faraday FTGMAC100 Gigabit Ethernet MAC register block.
type Ftgmac100V1FTGMAC100 struct {
    Base uintptr
}

// ReadISR reads ISR
func (p *Ftgmac100V1FTGMAC100) ReadISR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteISR writes ISR
func (p *Ftgmac100V1FTGMAC100) WriteISR(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadIER reads IER
func (p *Ftgmac100V1FTGMAC100) ReadIER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteIER writes IER
func (p *Ftgmac100V1FTGMAC100) WriteIER(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadMACMADR reads MAC_MADR
func (p *Ftgmac100V1FTGMAC100) ReadMACMADR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteMACMADR writes MAC_MADR
func (p *Ftgmac100V1FTGMAC100) WriteMACMADR(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadMACLADR reads MAC_LADR
func (p *Ftgmac100V1FTGMAC100) ReadMACLADR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteMACLADR writes MAC_LADR
func (p *Ftgmac100V1FTGMAC100) WriteMACLADR(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMAHT0 reads MAHT0
func (p *Ftgmac100V1FTGMAC100) ReadMAHT0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMAHT0 writes MAHT0
func (p *Ftgmac100V1FTGMAC100) WriteMAHT0(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadMAHT1 reads MAHT1
func (p *Ftgmac100V1FTGMAC100) ReadMAHT1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteMAHT1 writes MAHT1
func (p *Ftgmac100V1FTGMAC100) WriteMAHT1(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadNPTXPD reads NPTXPD
func (p *Ftgmac100V1FTGMAC100) ReadNPTXPD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteNPTXPD writes NPTXPD
func (p *Ftgmac100V1FTGMAC100) WriteNPTXPD(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadRXPD reads RXPD
func (p *Ftgmac100V1FTGMAC100) ReadRXPD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteRXPD writes RXPD
func (p *Ftgmac100V1FTGMAC100) WriteRXPD(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadNPTXRBADR reads NPTXR_BADR
func (p *Ftgmac100V1FTGMAC100) ReadNPTXRBADR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteNPTXRBADR writes NPTXR_BADR
func (p *Ftgmac100V1FTGMAC100) WriteNPTXRBADR(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadRXRBADR reads RXR_BADR
func (p *Ftgmac100V1FTGMAC100) ReadRXRBADR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteRXRBADR writes RXR_BADR
func (p *Ftgmac100V1FTGMAC100) WriteRXRBADR(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadHPTXPD reads HPTXPD
func (p *Ftgmac100V1FTGMAC100) ReadHPTXPD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteHPTXPD writes HPTXPD
func (p *Ftgmac100V1FTGMAC100) WriteHPTXPD(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadHPTXRBADR reads HPTXR_BADR
func (p *Ftgmac100V1FTGMAC100) ReadHPTXRBADR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteHPTXRBADR writes HPTXR_BADR
func (p *Ftgmac100V1FTGMAC100) WriteHPTXRBADR(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadITC reads ITC
func (p *Ftgmac100V1FTGMAC100) ReadITC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteITC writes ITC
func (p *Ftgmac100V1FTGMAC100) WriteITC(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadAPTC reads APTC
func (p *Ftgmac100V1FTGMAC100) ReadAPTC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteAPTC writes APTC
func (p *Ftgmac100V1FTGMAC100) WriteAPTC(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadDBLAC reads DBLAC
func (p *Ftgmac100V1FTGMAC100) ReadDBLAC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteDBLAC writes DBLAC
func (p *Ftgmac100V1FTGMAC100) WriteDBLAC(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadDMAFIFOS reads DMAFIFOS
func (p *Ftgmac100V1FTGMAC100) ReadDMAFIFOS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteDMAFIFOS writes DMAFIFOS
func (p *Ftgmac100V1FTGMAC100) WriteDMAFIFOS(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadREVR reads REVR
func (p *Ftgmac100V1FTGMAC100) ReadREVR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteREVR writes REVR
func (p *Ftgmac100V1FTGMAC100) WriteREVR(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadFEAR reads FEAR
func (p *Ftgmac100V1FTGMAC100) ReadFEAR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteFEAR writes FEAR
func (p *Ftgmac100V1FTGMAC100) WriteFEAR(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadTPAFCR reads TPAFCR
func (p *Ftgmac100V1FTGMAC100) ReadTPAFCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteTPAFCR writes TPAFCR
func (p *Ftgmac100V1FTGMAC100) WriteTPAFCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadRBSR reads RBSR
func (p *Ftgmac100V1FTGMAC100) ReadRBSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteRBSR writes RBSR
func (p *Ftgmac100V1FTGMAC100) WriteRBSR(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadMACCR reads MACCR
func (p *Ftgmac100V1FTGMAC100) ReadMACCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteMACCR writes MACCR
func (p *Ftgmac100V1FTGMAC100) WriteMACCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadMACSR reads MACSR
func (p *Ftgmac100V1FTGMAC100) ReadMACSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteMACSR writes MACSR
func (p *Ftgmac100V1FTGMAC100) WriteMACSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadTM reads TM
func (p *Ftgmac100V1FTGMAC100) ReadTM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteTM writes TM
func (p *Ftgmac100V1FTGMAC100) WriteTM(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadPHYCR reads PHYCR
func (p *Ftgmac100V1FTGMAC100) ReadPHYCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WritePHYCR writes PHYCR
func (p *Ftgmac100V1FTGMAC100) WritePHYCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadPHYDATA reads PHYDATA
func (p *Ftgmac100V1FTGMAC100) ReadPHYDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WritePHYDATA writes PHYDATA
func (p *Ftgmac100V1FTGMAC100) WritePHYDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadFCR reads FCR
func (p *Ftgmac100V1FTGMAC100) ReadFCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteFCR writes FCR
func (p *Ftgmac100V1FTGMAC100) WriteFCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadBPR reads BPR
func (p *Ftgmac100V1FTGMAC100) ReadBPR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteBPR writes BPR
func (p *Ftgmac100V1FTGMAC100) WriteBPR(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadWOLCR reads WOLCR
func (p *Ftgmac100V1FTGMAC100) ReadWOLCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteWOLCR writes WOLCR
func (p *Ftgmac100V1FTGMAC100) WriteWOLCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadWOLSR reads WOLSR
func (p *Ftgmac100V1FTGMAC100) ReadWOLSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteWOLSR writes WOLSR
func (p *Ftgmac100V1FTGMAC100) WriteWOLSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadWFCRC reads WFCRC
func (p *Ftgmac100V1FTGMAC100) ReadWFCRC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteWFCRC writes WFCRC
func (p *Ftgmac100V1FTGMAC100) WriteWFCRC(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadWFBM1 reads WFBM1
func (p *Ftgmac100V1FTGMAC100) ReadWFBM1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteWFBM1 writes WFBM1
func (p *Ftgmac100V1FTGMAC100) WriteWFBM1(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadWFBM2 reads WFBM2
func (p *Ftgmac100V1FTGMAC100) ReadWFBM2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteWFBM2 writes WFBM2
func (p *Ftgmac100V1FTGMAC100) WriteWFBM2(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadWFBM3 reads WFBM3
func (p *Ftgmac100V1FTGMAC100) ReadWFBM3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteWFBM3 writes WFBM3
func (p *Ftgmac100V1FTGMAC100) WriteWFBM3(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadWFBM4 reads WFBM4
func (p *Ftgmac100V1FTGMAC100) ReadWFBM4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteWFBM4 writes WFBM4
func (p *Ftgmac100V1FTGMAC100) WriteWFBM4(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadNPTXRPTR reads NPTXR_PTR
func (p *Ftgmac100V1FTGMAC100) ReadNPTXRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteNPTXRPTR writes NPTXR_PTR
func (p *Ftgmac100V1FTGMAC100) WriteNPTXRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadHPTXRPTR reads HPTXR_PTR
func (p *Ftgmac100V1FTGMAC100) ReadHPTXRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteHPTXRPTR writes HPTXR_PTR
func (p *Ftgmac100V1FTGMAC100) WriteHPTXRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadRXRPTR reads RXR_PTR
func (p *Ftgmac100V1FTGMAC100) ReadRXRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteRXRPTR writes RXR_PTR
func (p *Ftgmac100V1FTGMAC100) WriteRXRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadTX reads TX
func (p *Ftgmac100V1FTGMAC100) ReadTX() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteTX writes TX
func (p *Ftgmac100V1FTGMAC100) WriteTX(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadRX reads RX
func (p *Ftgmac100V1FTGMAC100) ReadRX() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteRX writes RX
func (p *Ftgmac100V1FTGMAC100) WriteRX(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadTXRBADRLOW reads AST2700 transmit ring base low word.
func (p *Ftgmac100V1FTGMAC100) ReadTXRBADRLOW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0178))
}

// WriteTXRBADRLOW writes AST2700 transmit ring base low word.
func (p *Ftgmac100V1FTGMAC100) WriteTXRBADRLOW(val uint32) {
    reg.Write(uint32(p.Base)+0x0178, uint32(val))
}

// ReadTXRBADRHIGH reads AST2700 transmit ring base high word.
func (p *Ftgmac100V1FTGMAC100) ReadTXRBADRHIGH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x017c))
}

// WriteTXRBADRHIGH writes AST2700 transmit ring base high word.
func (p *Ftgmac100V1FTGMAC100) WriteTXRBADRHIGH(val uint32) {
    reg.Write(uint32(p.Base)+0x017c, uint32(val))
}

// ReadHPTXRBADRLOW reads AST2700 high-priority transmit ring base low word.
func (p *Ftgmac100V1FTGMAC100) ReadHPTXRBADRLOW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0180))
}

// WriteHPTXRBADRLOW writes AST2700 high-priority transmit ring base low word.
func (p *Ftgmac100V1FTGMAC100) WriteHPTXRBADRLOW(val uint32) {
    reg.Write(uint32(p.Base)+0x0180, uint32(val))
}

// ReadHPTXRBADRHIGH reads AST2700 high-priority transmit ring base high word.
func (p *Ftgmac100V1FTGMAC100) ReadHPTXRBADRHIGH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0184))
}

// WriteHPTXRBADRHIGH writes AST2700 high-priority transmit ring base high word.
func (p *Ftgmac100V1FTGMAC100) WriteHPTXRBADRHIGH(val uint32) {
    reg.Write(uint32(p.Base)+0x0184, uint32(val))
}

// ReadRXRBADRLOW reads AST2700 receive ring base low word.
func (p *Ftgmac100V1FTGMAC100) ReadRXRBADRLOW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0188))
}

// WriteRXRBADRLOW writes AST2700 receive ring base low word.
func (p *Ftgmac100V1FTGMAC100) WriteRXRBADRLOW(val uint32) {
    reg.Write(uint32(p.Base)+0x0188, uint32(val))
}

// ReadRXRBADRHIGH reads AST2700 receive ring base high word.
func (p *Ftgmac100V1FTGMAC100) ReadRXRBADRHIGH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x018c))
}

// WriteRXRBADRHIGH writes AST2700 receive ring base high word.
func (p *Ftgmac100V1FTGMAC100) WriteRXRBADRHIGH(val uint32) {
    reg.Write(uint32(p.Base)+0x018c, uint32(val))
}

