// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// OtpAst2700V1OTP ASPEED AST2700 one-time-programmable memory controller. OTP read/write commands operate on 16-bit OTP word offsets.
type OtpAst2700V1OTP struct {
    Base uintptr
}

// ReadKEY reads Unlock key register. Write 0x349FE38A before commands.
func (p *OtpAst2700V1OTP) ReadKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteKEY writes Unlock key register. Write 0x349FE38A before commands.
func (p *OtpAst2700V1OTP) WriteKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCMD reads Master command register.
func (p *OtpAst2700V1OTP) ReadCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCMD writes Master command register.
func (p *OtpAst2700V1OTP) WriteCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadWDATA0 reads Write-data word 0.
func (p *OtpAst2700V1OTP) ReadWDATA0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteWDATA0 writes Write-data word 0.
func (p *OtpAst2700V1OTP) WriteWDATA0(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadWDATA1 reads Write-data word 1.
func (p *OtpAst2700V1OTP) ReadWDATA1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteWDATA1 writes Write-data word 1.
func (p *OtpAst2700V1OTP) WriteWDATA1(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadWDATA2 reads Write-data word 2.
func (p *OtpAst2700V1OTP) ReadWDATA2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteWDATA2 writes Write-data word 2.
func (p *OtpAst2700V1OTP) WriteWDATA2(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadWDATA3 reads Write-data word 3.
func (p *OtpAst2700V1OTP) ReadWDATA3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteWDATA3 writes Write-data word 3.
func (p *OtpAst2700V1OTP) WriteWDATA3(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadSTATUS reads Command status; bit 0 set while busy, bits 7:4 hold result.
func (p *OtpAst2700V1OTP) ReadSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteSTATUS writes Command status; bit 0 set while busy, bits 7:4 hold result.
func (p *OtpAst2700V1OTP) WriteSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadADDR reads OTP word address for command.
func (p *OtpAst2700V1OTP) ReadADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteADDR writes OTP word address for command.
func (p *OtpAst2700V1OTP) WriteADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadRDATA reads Read-data register; low 16 bits contain one OTP word.
func (p *OtpAst2700V1OTP) ReadRDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// ReadCMDM1 reads Master 1 command register.
func (p *OtpAst2700V1OTP) ReadCMDM1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteCMDM1 writes Master 1 command register.
func (p *OtpAst2700V1OTP) WriteCMDM1(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadWDATAM1 reads Master 1 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) ReadWDATAM1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028 + uint32(n)*4))
}

// WriteWDATAM1 writes Master 1 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) WriteWDATAM1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0028+uint32(n)*4, uint32(val))
}

// ReadSTATUSM1 reads Master 1 command status register.
func (p *OtpAst2700V1OTP) ReadSTATUSM1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// ReadADDRM1 reads Master 1 OTP word address register.
func (p *OtpAst2700V1OTP) ReadADDRM1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteADDRM1 writes Master 1 OTP word address register.
func (p *OtpAst2700V1OTP) WriteADDRM1(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadRDATAM1 reads Master 1 read-data register.
func (p *OtpAst2700V1OTP) ReadRDATAM1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// ReadCMDM2 reads Master 2 command register.
func (p *OtpAst2700V1OTP) ReadCMDM2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteCMDM2 writes Master 2 command register.
func (p *OtpAst2700V1OTP) WriteCMDM2(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadWDATAM2 reads Master 2 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) ReadWDATAM2(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048 + uint32(n)*4))
}

// WriteWDATAM2 writes Master 2 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) WriteWDATAM2(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0048+uint32(n)*4, uint32(val))
}

// ReadSTATUSM2 reads Master 2 command status register.
func (p *OtpAst2700V1OTP) ReadSTATUSM2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// ReadADDRM2 reads Master 2 OTP word address register.
func (p *OtpAst2700V1OTP) ReadADDRM2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteADDRM2 writes Master 2 OTP word address register.
func (p *OtpAst2700V1OTP) WriteADDRM2(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadRDATAM2 reads Master 2 read-data register.
func (p *OtpAst2700V1OTP) ReadRDATAM2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// ReadCMDM3 reads Master 3 command register.
func (p *OtpAst2700V1OTP) ReadCMDM3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteCMDM3 writes Master 3 command register.
func (p *OtpAst2700V1OTP) WriteCMDM3(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadWDATAM3 reads Master 3 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) ReadWDATAM3(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068 + uint32(n)*4))
}

// WriteWDATAM3 writes Master 3 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) WriteWDATAM3(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0068+uint32(n)*4, uint32(val))
}

// ReadSTATUSM3 reads Master 3 command status register.
func (p *OtpAst2700V1OTP) ReadSTATUSM3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// ReadADDRM3 reads Master 3 OTP word address register.
func (p *OtpAst2700V1OTP) ReadADDRM3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteADDRM3 writes Master 3 OTP word address register.
func (p *OtpAst2700V1OTP) WriteADDRM3(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadRDATAM3 reads Master 3 read-data register.
func (p *OtpAst2700V1OTP) ReadRDATAM3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// ReadCMDM4 reads Master 4 command register.
func (p *OtpAst2700V1OTP) ReadCMDM4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteCMDM4 writes Master 4 command register.
func (p *OtpAst2700V1OTP) WriteCMDM4(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadWDATAM4 reads Master 4 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) ReadWDATAM4(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088 + uint32(n)*4))
}

// WriteWDATAM4 writes Master 4 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) WriteWDATAM4(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0088+uint32(n)*4, uint32(val))
}

// ReadSTATUSM4 reads Master 4 command status register.
func (p *OtpAst2700V1OTP) ReadSTATUSM4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// ReadADDRM4 reads Master 4 OTP word address register.
func (p *OtpAst2700V1OTP) ReadADDRM4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// WriteADDRM4 writes Master 4 OTP word address register.
func (p *OtpAst2700V1OTP) WriteADDRM4(val uint32) {
    reg.Write(uint32(p.Base)+0x009c, uint32(val))
}

// ReadRDATAM4 reads Master 4 read-data register.
func (p *OtpAst2700V1OTP) ReadRDATAM4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// ReadCMDM5 reads Master 5 command register.
func (p *OtpAst2700V1OTP) ReadCMDM5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteCMDM5 writes Master 5 command register.
func (p *OtpAst2700V1OTP) WriteCMDM5(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadWDATAM5 reads Master 5 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) ReadWDATAM5(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8 + uint32(n)*4))
}

// WriteWDATAM5 writes Master 5 write-data words.[n] (n < 4)
func (p *OtpAst2700V1OTP) WriteWDATAM5(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x00a8+uint32(n)*4, uint32(val))
}

// ReadSTATUSM5 reads Master 5 command status register.
func (p *OtpAst2700V1OTP) ReadSTATUSM5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// ReadADDRM5 reads Master 5 OTP word address register.
func (p *OtpAst2700V1OTP) ReadADDRM5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteADDRM5 writes Master 5 OTP word address register.
func (p *OtpAst2700V1OTP) WriteADDRM5(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadRDATAM5 reads Master 5 read-data register.
func (p *OtpAst2700V1OTP) ReadRDATAM5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// ReadDBG00 reads DBG00
func (p *OtpAst2700V1OTP) ReadDBG00() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// ReadDBG01 reads DBG01
func (p *OtpAst2700V1OTP) ReadDBG01() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// ReadMASTERPID reads MASTER_PID
func (p *OtpAst2700V1OTP) ReadMASTERPID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// ReadECCEN reads ECC enable control. Bit 0 enables ECC-aware accesses.
func (p *OtpAst2700V1OTP) ReadECCEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteECCEN writes ECC enable control. Bit 0 enables ECC-aware accesses.
func (p *OtpAst2700V1OTP) WriteECCEN(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadCMDLOCK reads CMD_LOCK
func (p *OtpAst2700V1OTP) ReadCMDLOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteCMDLOCK writes CMD_LOCK
func (p *OtpAst2700V1OTP) WriteCMDLOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadSWRST reads SW_RST
func (p *OtpAst2700V1OTP) ReadSWRST() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00dc))
}

// WriteSWRST writes SW_RST
func (p *OtpAst2700V1OTP) WriteSWRST(val uint32) {
    reg.Write(uint32(p.Base)+0x00dc, uint32(val))
}

// ReadSLVID reads SLV_ID
func (p *OtpAst2700V1OTP) ReadSLVID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteSLVID writes SLV_ID
func (p *OtpAst2700V1OTP) WriteSLVID(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadPMCCQ reads PMC_CQ
func (p *OtpAst2700V1OTP) ReadPMCCQ() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e4))
}

// WritePMCCQ writes PMC_CQ
func (p *OtpAst2700V1OTP) WritePMCCQ(val uint32) {
    reg.Write(uint32(p.Base)+0x00e4, uint32(val))
}

// ReadFPGA reads FPGA
func (p *OtpAst2700V1OTP) ReadFPGA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec))
}

// WriteFPGA writes FPGA
func (p *OtpAst2700V1OTP) WriteFPGA(val uint32) {
    reg.Write(uint32(p.Base)+0x00ec, uint32(val))
}

// ReadCLRFPGA reads CLR_FPGA
func (p *OtpAst2700V1OTP) ReadCLRFPGA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f0))
}

// WriteCLRFPGA writes CLR_FPGA
func (p *OtpAst2700V1OTP) WriteCLRFPGA(val uint32) {
    reg.Write(uint32(p.Base)+0x00f0, uint32(val))
}

// ReadREGIONROMPATCH reads REGION_ROM_PATCH
func (p *OtpAst2700V1OTP) ReadREGIONROMPATCH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100))
}

// WriteREGIONROMPATCH writes REGION_ROM_PATCH
func (p *OtpAst2700V1OTP) WriteREGIONROMPATCH(val uint32) {
    reg.Write(uint32(p.Base)+0x0100, uint32(val))
}

// ReadREGIONOTPCFG reads REGION_OTPCFG
func (p *OtpAst2700V1OTP) ReadREGIONOTPCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0104))
}

// WriteREGIONOTPCFG writes REGION_OTPCFG
func (p *OtpAst2700V1OTP) WriteREGIONOTPCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0104, uint32(val))
}

// ReadREGIONOTPSTRAP reads REGION_OTPSTRAP
func (p *OtpAst2700V1OTP) ReadREGIONOTPSTRAP() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108))
}

// WriteREGIONOTPSTRAP writes REGION_OTPSTRAP
func (p *OtpAst2700V1OTP) WriteREGIONOTPSTRAP(val uint32) {
    reg.Write(uint32(p.Base)+0x0108, uint32(val))
}

// ReadREGIONOTPSTRAPEXT reads REGION_OTPSTRAP_EXT
func (p *OtpAst2700V1OTP) ReadREGIONOTPSTRAPEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x010c))
}

// WriteREGIONOTPSTRAPEXT writes REGION_OTPSTRAP_EXT
func (p *OtpAst2700V1OTP) WriteREGIONOTPSTRAPEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x010c, uint32(val))
}

// ReadREGIONSECURE0 reads REGION_SECURE0
func (p *OtpAst2700V1OTP) ReadREGIONSECURE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0120))
}

// WriteREGIONSECURE0 writes REGION_SECURE0
func (p *OtpAst2700V1OTP) WriteREGIONSECURE0(val uint32) {
    reg.Write(uint32(p.Base)+0x0120, uint32(val))
}

// ReadREGIONSECURE0RANGE reads REGION_SECURE0_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONSECURE0RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0124))
}

// WriteREGIONSECURE0RANGE writes REGION_SECURE0_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONSECURE0RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0124, uint32(val))
}

// ReadREGIONSECURE1 reads REGION_SECURE1
func (p *OtpAst2700V1OTP) ReadREGIONSECURE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128))
}

// WriteREGIONSECURE1 writes REGION_SECURE1
func (p *OtpAst2700V1OTP) WriteREGIONSECURE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0128, uint32(val))
}

// ReadREGIONSECURE1RANGE reads REGION_SECURE1_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONSECURE1RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c))
}

// WriteREGIONSECURE1RANGE writes REGION_SECURE1_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONSECURE1RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x012c, uint32(val))
}

// ReadREGIONSECURE2 reads REGION_SECURE2
func (p *OtpAst2700V1OTP) ReadREGIONSECURE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0130))
}

// WriteREGIONSECURE2 writes REGION_SECURE2
func (p *OtpAst2700V1OTP) WriteREGIONSECURE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0130, uint32(val))
}

// ReadREGIONSECURE2RANGE reads REGION_SECURE2_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONSECURE2RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0134))
}

// WriteREGIONSECURE2RANGE writes REGION_SECURE2_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONSECURE2RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0134, uint32(val))
}

// ReadREGIONSECURE3 reads REGION_SECURE3
func (p *OtpAst2700V1OTP) ReadREGIONSECURE3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WriteREGIONSECURE3 writes REGION_SECURE3
func (p *OtpAst2700V1OTP) WriteREGIONSECURE3(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadREGIONSECURE3RANGE reads REGION_SECURE3_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONSECURE3RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x013c))
}

// WriteREGIONSECURE3RANGE writes REGION_SECURE3_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONSECURE3RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x013c, uint32(val))
}

// ReadREGIONUSR0 reads REGION_USR0
func (p *OtpAst2700V1OTP) ReadREGIONUSR0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140))
}

// WriteREGIONUSR0 writes REGION_USR0
func (p *OtpAst2700V1OTP) WriteREGIONUSR0(val uint32) {
    reg.Write(uint32(p.Base)+0x0140, uint32(val))
}

// ReadREGIONUSR0RANGE reads REGION_USR0_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONUSR0RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0144))
}

// WriteREGIONUSR0RANGE writes REGION_USR0_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONUSR0RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0144, uint32(val))
}

// ReadREGIONUSR1 reads REGION_USR1
func (p *OtpAst2700V1OTP) ReadREGIONUSR1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0148))
}

// WriteREGIONUSR1 writes REGION_USR1
func (p *OtpAst2700V1OTP) WriteREGIONUSR1(val uint32) {
    reg.Write(uint32(p.Base)+0x0148, uint32(val))
}

// ReadREGIONUSR1RANGE reads REGION_USR1_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONUSR1RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x014c))
}

// WriteREGIONUSR1RANGE writes REGION_USR1_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONUSR1RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x014c, uint32(val))
}

// ReadREGIONUSR2 reads REGION_USR2
func (p *OtpAst2700V1OTP) ReadREGIONUSR2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0150))
}

// WriteREGIONUSR2 writes REGION_USR2
func (p *OtpAst2700V1OTP) WriteREGIONUSR2(val uint32) {
    reg.Write(uint32(p.Base)+0x0150, uint32(val))
}

// ReadREGIONUSR2RANGE reads REGION_USR2_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONUSR2RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0154))
}

// WriteREGIONUSR2RANGE writes REGION_USR2_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONUSR2RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0154, uint32(val))
}

// ReadREGIONUSR3 reads REGION_USR3
func (p *OtpAst2700V1OTP) ReadREGIONUSR3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0158))
}

// WriteREGIONUSR3 writes REGION_USR3
func (p *OtpAst2700V1OTP) WriteREGIONUSR3(val uint32) {
    reg.Write(uint32(p.Base)+0x0158, uint32(val))
}

// ReadREGIONUSR3RANGE reads REGION_USR3_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONUSR3RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x015c))
}

// WriteREGIONUSR3RANGE writes REGION_USR3_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONUSR3RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x015c, uint32(val))
}

// ReadREGIONCALIPTRA0 reads REGION_CALIPTRA0
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0160))
}

// WriteREGIONCALIPTRA0 writes REGION_CALIPTRA0
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA0(val uint32) {
    reg.Write(uint32(p.Base)+0x0160, uint32(val))
}

// ReadREGIONCALIPTRA0RANGE reads REGION_CALIPTRA0_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA0RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0164))
}

// WriteREGIONCALIPTRA0RANGE writes REGION_CALIPTRA0_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA0RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0164, uint32(val))
}

// ReadREGIONCALIPTRA1 reads REGION_CALIPTRA1
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// WriteREGIONCALIPTRA1 writes REGION_CALIPTRA1
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA1(val uint32) {
    reg.Write(uint32(p.Base)+0x0168, uint32(val))
}

// ReadREGIONCALIPTRA1RANGE reads REGION_CALIPTRA1_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA1RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x016c))
}

// WriteREGIONCALIPTRA1RANGE writes REGION_CALIPTRA1_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA1RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x016c, uint32(val))
}

// ReadREGIONCALIPTRA2 reads REGION_CALIPTRA2
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0170))
}

// WriteREGIONCALIPTRA2 writes REGION_CALIPTRA2
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA2(val uint32) {
    reg.Write(uint32(p.Base)+0x0170, uint32(val))
}

// ReadREGIONCALIPTRA2RANGE reads REGION_CALIPTRA2_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA2RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0174))
}

// WriteREGIONCALIPTRA2RANGE writes REGION_CALIPTRA2_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA2RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0174, uint32(val))
}

// ReadREGIONCALIPTRA3 reads REGION_CALIPTRA3
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0178))
}

// WriteREGIONCALIPTRA3 writes REGION_CALIPTRA3
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA3(val uint32) {
    reg.Write(uint32(p.Base)+0x0178, uint32(val))
}

// ReadREGIONCALIPTRA3RANGE reads REGION_CALIPTRA3_RANGE
func (p *OtpAst2700V1OTP) ReadREGIONCALIPTRA3RANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x017c))
}

// WriteREGIONCALIPTRA3RANGE writes REGION_CALIPTRA3_RANGE
func (p *OtpAst2700V1OTP) WriteREGIONCALIPTRA3RANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x017c, uint32(val))
}

// ReadRBPSOCSVN reads RBP_SOC_SVN
func (p *OtpAst2700V1OTP) ReadRBPSOCSVN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0180))
}

// WriteRBPSOCSVN writes RBP_SOC_SVN
func (p *OtpAst2700V1OTP) WriteRBPSOCSVN(val uint32) {
    reg.Write(uint32(p.Base)+0x0180, uint32(val))
}

// ReadRBPSOCKEYRETIRE reads RBP_SOC_KEYRETIRE
func (p *OtpAst2700V1OTP) ReadRBPSOCKEYRETIRE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0184))
}

// WriteRBPSOCKEYRETIRE writes RBP_SOC_KEYRETIRE
func (p *OtpAst2700V1OTP) WriteRBPSOCKEYRETIRE(val uint32) {
    reg.Write(uint32(p.Base)+0x0184, uint32(val))
}

// ReadRBPCALIPSVN reads RBP_CALIP_SVN
func (p *OtpAst2700V1OTP) ReadRBPCALIPSVN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0188))
}

// WriteRBPCALIPSVN writes RBP_CALIP_SVN
func (p *OtpAst2700V1OTP) WriteRBPCALIPSVN(val uint32) {
    reg.Write(uint32(p.Base)+0x0188, uint32(val))
}

// ReadRBPCALIPKEYRETIRE reads RBP_CALIP_KEYRETIRE
func (p *OtpAst2700V1OTP) ReadRBPCALIPKEYRETIRE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x018c))
}

// WriteRBPCALIPKEYRETIRE writes RBP_CALIP_KEYRETIRE
func (p *OtpAst2700V1OTP) WriteRBPCALIPKEYRETIRE(val uint32) {
    reg.Write(uint32(p.Base)+0x018c, uint32(val))
}

// ReadPUF reads PUF
func (p *OtpAst2700V1OTP) ReadPUF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01a0))
}

// WritePUF writes PUF
func (p *OtpAst2700V1OTP) WritePUF(val uint32) {
    reg.Write(uint32(p.Base)+0x01a0, uint32(val))
}

// ReadMASTERID reads MASTER_ID
func (p *OtpAst2700V1OTP) ReadMASTERID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01b0))
}

// WriteMASTERID writes MASTER_ID
func (p *OtpAst2700V1OTP) WriteMASTERID(val uint32) {
    reg.Write(uint32(p.Base)+0x01b0, uint32(val))
}

// ReadMASTERIDEXT reads MASTER_ID_EXT
func (p *OtpAst2700V1OTP) ReadMASTERIDEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01b4))
}

// WriteMASTERIDEXT writes MASTER_ID_EXT
func (p *OtpAst2700V1OTP) WriteMASTERIDEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x01b4, uint32(val))
}

// ReadRMASTERID reads R_MASTER_ID
func (p *OtpAst2700V1OTP) ReadRMASTERID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01b8))
}

// WriteRMASTERID writes R_MASTER_ID
func (p *OtpAst2700V1OTP) WriteRMASTERID(val uint32) {
    reg.Write(uint32(p.Base)+0x01b8, uint32(val))
}

// ReadRMASTERIDEXT reads R_MASTER_ID_EXT
func (p *OtpAst2700V1OTP) ReadRMASTERIDEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01bc))
}

// WriteRMASTERIDEXT writes R_MASTER_ID_EXT
func (p *OtpAst2700V1OTP) WriteRMASTERIDEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x01bc, uint32(val))
}

// ReadSOCECCKEY reads SOC_ECCKEY
func (p *OtpAst2700V1OTP) ReadSOCECCKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01c0))
}

// WriteSOCECCKEY writes SOC_ECCKEY
func (p *OtpAst2700V1OTP) WriteSOCECCKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x01c0, uint32(val))
}

// ReadSECBOOTEN reads SEC_BOOT_EN
func (p *OtpAst2700V1OTP) ReadSECBOOTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01c4))
}

// WriteSECBOOTEN writes SEC_BOOT_EN
func (p *OtpAst2700V1OTP) WriteSECBOOTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x01c4, uint32(val))
}

// ReadSOCKEY reads SOC_KEY
func (p *OtpAst2700V1OTP) ReadSOCKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01c8))
}

// WriteSOCKEY writes SOC_KEY
func (p *OtpAst2700V1OTP) WriteSOCKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x01c8, uint32(val))
}

// ReadCALIPTRAMANUKEY reads CALIPTRA_MANU_KEY
func (p *OtpAst2700V1OTP) ReadCALIPTRAMANUKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01cc))
}

// WriteCALIPTRAMANUKEY writes CALIPTRA_MANU_KEY
func (p *OtpAst2700V1OTP) WriteCALIPTRAMANUKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x01cc, uint32(val))
}

// ReadCALIPTRAOWNERKEY reads CALIPTRA_OWNER_KEY
func (p *OtpAst2700V1OTP) ReadCALIPTRAOWNERKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01d0))
}

// WriteCALIPTRAOWNERKEY writes CALIPTRA_OWNER_KEY
func (p *OtpAst2700V1OTP) WriteCALIPTRAOWNERKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x01d0, uint32(val))
}

// ReadFWIDLSB reads FW_ID_LSB
func (p *OtpAst2700V1OTP) ReadFWIDLSB() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01d4))
}

// WriteFWIDLSB writes FW_ID_LSB
func (p *OtpAst2700V1OTP) WriteFWIDLSB(val uint32) {
    reg.Write(uint32(p.Base)+0x01d4, uint32(val))
}

// ReadFWIDMSB reads FW_ID_MSB
func (p *OtpAst2700V1OTP) ReadFWIDMSB() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01d8))
}

// WriteFWIDMSB writes FW_ID_MSB
func (p *OtpAst2700V1OTP) WriteFWIDMSB(val uint32) {
    reg.Write(uint32(p.Base)+0x01d8, uint32(val))
}

// ReadCALIPFMCSVN reads CALIP_FMC_SVN
func (p *OtpAst2700V1OTP) ReadCALIPFMCSVN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01dc))
}

// WriteCALIPFMCSVN writes CALIP_FMC_SVN
func (p *OtpAst2700V1OTP) WriteCALIPFMCSVN(val uint32) {
    reg.Write(uint32(p.Base)+0x01dc, uint32(val))
}

// ReadCALIPRUNTIMESVN0 reads CALIP_RUNTIME_SVN0
func (p *OtpAst2700V1OTP) ReadCALIPRUNTIMESVN0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01e0))
}

// WriteCALIPRUNTIMESVN0 writes CALIP_RUNTIME_SVN0
func (p *OtpAst2700V1OTP) WriteCALIPRUNTIMESVN0(val uint32) {
    reg.Write(uint32(p.Base)+0x01e0, uint32(val))
}

// ReadCALIPRUNTIMESVN1 reads CALIP_RUNTIME_SVN1
func (p *OtpAst2700V1OTP) ReadCALIPRUNTIMESVN1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01e4))
}

// WriteCALIPRUNTIMESVN1 writes CALIP_RUNTIME_SVN1
func (p *OtpAst2700V1OTP) WriteCALIPRUNTIMESVN1(val uint32) {
    reg.Write(uint32(p.Base)+0x01e4, uint32(val))
}

// ReadCALIPRUNTIMESVN2 reads CALIP_RUNTIME_SVN2
func (p *OtpAst2700V1OTP) ReadCALIPRUNTIMESVN2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01e8))
}

// WriteCALIPRUNTIMESVN2 writes CALIP_RUNTIME_SVN2
func (p *OtpAst2700V1OTP) WriteCALIPRUNTIMESVN2(val uint32) {
    reg.Write(uint32(p.Base)+0x01e8, uint32(val))
}

// ReadCALIPRUNTIMESVN3 reads CALIP_RUNTIME_SVN3
func (p *OtpAst2700V1OTP) ReadCALIPRUNTIMESVN3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01ec))
}

// WriteCALIPRUNTIMESVN3 writes CALIP_RUNTIME_SVN3
func (p *OtpAst2700V1OTP) WriteCALIPRUNTIMESVN3(val uint32) {
    reg.Write(uint32(p.Base)+0x01ec, uint32(val))
}

// ReadSVNWLOCK reads SVN_WLOCK
func (p *OtpAst2700V1OTP) ReadSVNWLOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01f0))
}

// WriteSVNWLOCK writes SVN_WLOCK
func (p *OtpAst2700V1OTP) WriteSVNWLOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x01f0, uint32(val))
}

// ReadINTREN reads INTR_EN
func (p *OtpAst2700V1OTP) ReadINTREN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// WriteINTREN writes INTR_EN
func (p *OtpAst2700V1OTP) WriteINTREN(val uint32) {
    reg.Write(uint32(p.Base)+0x0200, uint32(val))
}

// ReadINTRSTS reads INTR_STS
func (p *OtpAst2700V1OTP) ReadINTRSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// ReadINTRMID reads INTR_MID
func (p *OtpAst2700V1OTP) ReadINTRMID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0208))
}

// WriteINTRMID writes INTR_MID
func (p *OtpAst2700V1OTP) WriteINTRMID(val uint32) {
    reg.Write(uint32(p.Base)+0x0208, uint32(val))
}

// ReadINTRFUNCINFO reads INTR_FUNC_INFO
func (p *OtpAst2700V1OTP) ReadINTRFUNCINFO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x020c))
}

// ReadINTRMINFO reads INTR_M_INFO
func (p *OtpAst2700V1OTP) ReadINTRMINFO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0210))
}

// ReadINTRRINFO reads INTR_R_INFO
func (p *OtpAst2700V1OTP) ReadINTRRINFO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0214))
}

