// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// PcieAst2700V1PLDA AST2700 PCIe controller configuration space window.  Instances are at 0x12C15000, 0x12C15800, and 0x14C1C000.
type PcieAst2700V1PLDA struct {
    Base uintptr
}

// ReadDEVICEVENDORID reads DEVICE_VENDOR_ID
func (p *PcieAst2700V1PLDA) ReadDEVICEVENDORID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// ReadCOMMANDSTATUS reads COMMAND_STATUS
func (p *PcieAst2700V1PLDA) ReadCOMMANDSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCOMMANDSTATUS writes COMMAND_STATUS
func (p *PcieAst2700V1PLDA) WriteCOMMANDSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCLASSREVISION reads CLASS_REVISION
func (p *PcieAst2700V1PLDA) ReadCLASSREVISION() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// ReadHEADER reads HEADER
func (p *PcieAst2700V1PLDA) ReadHEADER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteHEADER writes HEADER
func (p *PcieAst2700V1PLDA) WriteHEADER(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadBAR reads BAR[n] (n < 2)
func (p *PcieAst2700V1PLDA) ReadBAR(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010 + uint32(n)*4))
}

// WriteBAR writes BAR[n] (n < 2)
func (p *PcieAst2700V1PLDA) WriteBAR(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0010+uint32(n)*4, uint32(val))
}

// ReadBUSNUMBER reads BUS_NUMBER
func (p *PcieAst2700V1PLDA) ReadBUSNUMBER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteBUSNUMBER writes BUS_NUMBER
func (p *PcieAst2700V1PLDA) WriteBUSNUMBER(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadIOMEMLIMITBASE reads IO_MEM_LIMIT_BASE
func (p *PcieAst2700V1PLDA) ReadIOMEMLIMITBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteIOMEMLIMITBASE writes IO_MEM_LIMIT_BASE
func (p *PcieAst2700V1PLDA) WriteIOMEMLIMITBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadPREFETCHLIMITBASE reads PREFETCH_LIMIT_BASE
func (p *PcieAst2700V1PLDA) ReadPREFETCHLIMITBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WritePREFETCHLIMITBASE writes PREFETCH_LIMIT_BASE
func (p *PcieAst2700V1PLDA) WritePREFETCHLIMITBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadPREFETCHBASEUPPER reads PREFETCH_BASE_UPPER
func (p *PcieAst2700V1PLDA) ReadPREFETCHBASEUPPER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WritePREFETCHBASEUPPER writes PREFETCH_BASE_UPPER
func (p *PcieAst2700V1PLDA) WritePREFETCHBASEUPPER(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadPREFETCHLIMITUPPER reads PREFETCH_LIMIT_UPPER
func (p *PcieAst2700V1PLDA) ReadPREFETCHLIMITUPPER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WritePREFETCHLIMITUPPER writes PREFETCH_LIMIT_UPPER
func (p *PcieAst2700V1PLDA) WritePREFETCHLIMITUPPER(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadIOLIMITBASEUPPER reads IO_LIMIT_BASE_UPPER
func (p *PcieAst2700V1PLDA) ReadIOLIMITBASEUPPER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteIOLIMITBASEUPPER writes IO_LIMIT_BASE_UPPER
func (p *PcieAst2700V1PLDA) WriteIOLIMITBASEUPPER(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadEXPANSIONROMBAR reads EXPANSION_ROM_BAR
func (p *PcieAst2700V1PLDA) ReadEXPANSIONROMBAR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteEXPANSIONROMBAR writes EXPANSION_ROM_BAR
func (p *PcieAst2700V1PLDA) WriteEXPANSIONROMBAR(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadCAPPTR reads CAP_PTR
func (p *PcieAst2700V1PLDA) ReadCAPPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// ReadBRIDGECONTROL reads BRIDGE_CONTROL
func (p *PcieAst2700V1PLDA) ReadBRIDGECONTROL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteBRIDGECONTROL writes BRIDGE_CONTROL
func (p *PcieAst2700V1PLDA) WriteBRIDGECONTROL(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadPCIECAP reads PCI Express capability structure at 0x080..0x0bb.[n] (n < 15)
func (p *PcieAst2700V1PLDA) ReadPCIECAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080 + uint32(n)*4))
}

// WritePCIECAP writes PCI Express capability structure at 0x080..0x0bb.[n] (n < 15)
func (p *PcieAst2700V1PLDA) WritePCIECAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0080+uint32(n)*4, uint32(val))
}

// ReadPMCAP reads Power Management capability structure.[n] (n < 2)
func (p *PcieAst2700V1PLDA) ReadPMCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f8 + uint32(n)*4))
}

// WritePMCAP writes Power Management capability structure.[n] (n < 2)
func (p *PcieAst2700V1PLDA) WritePMCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x00f8+uint32(n)*4, uint32(val))
}

// ReadVENDORSPECIFICEXTCAP reads VENDOR_SPECIFIC_EXT_CAP[n] (n < 2)
func (p *PcieAst2700V1PLDA) ReadVENDORSPECIFICEXTCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100 + uint32(n)*4))
}

// WriteVENDORSPECIFICEXTCAP writes VENDOR_SPECIFIC_EXT_CAP[n] (n < 2)
func (p *PcieAst2700V1PLDA) WriteVENDORSPECIFICEXTCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0100+uint32(n)*4, uint32(val))
}

// ReadLTRCAP reads Latency Tolerance Reporting capability.[n] (n < 2)
func (p *PcieAst2700V1PLDA) ReadLTRCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108 + uint32(n)*4))
}

// WriteLTRCAP writes Latency Tolerance Reporting capability.[n] (n < 2)
func (p *PcieAst2700V1PLDA) WriteLTRCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0108+uint32(n)*4, uint32(val))
}

// ReadL1PMSUBSTATESCAP reads L1_PM_SUBSTATES_CAP[n] (n < 4)
func (p *PcieAst2700V1PLDA) ReadL1PMSUBSTATESCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110 + uint32(n)*4))
}

// WriteL1PMSUBSTATESCAP writes L1_PM_SUBSTATES_CAP[n] (n < 4)
func (p *PcieAst2700V1PLDA) WriteL1PMSUBSTATESCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0110+uint32(n)*4, uint32(val))
}

// ReadARICAP reads Alternate Routing ID Interpretation capability.[n] (n < 2)
func (p *PcieAst2700V1PLDA) ReadARICAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128 + uint32(n)*4))
}

// WriteARICAP writes Alternate Routing ID Interpretation capability.[n] (n < 2)
func (p *PcieAst2700V1PLDA) WriteARICAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0128+uint32(n)*4, uint32(val))
}

// ReadDATALINKFEATURECAP reads DATA_LINK_FEATURE_CAP[n] (n < 3)
func (p *PcieAst2700V1PLDA) ReadDATALINKFEATURECAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01e0 + uint32(n)*4))
}

// WriteDATALINKFEATURECAP writes DATA_LINK_FEATURE_CAP[n] (n < 3)
func (p *PcieAst2700V1PLDA) WriteDATALINKFEATURECAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x01e0+uint32(n)*4, uint32(val))
}

// ReadAERCAP reads Advanced Error Reporting capability.[n] (n < 18)
func (p *PcieAst2700V1PLDA) ReadAERCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200 + uint32(n)*4))
}

// WriteAERCAP writes Advanced Error Reporting capability.[n] (n < 18)
func (p *PcieAst2700V1PLDA) WriteAERCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0200+uint32(n)*4, uint32(val))
}

// ReadSECONDARYPCIECAP reads SECONDARY_PCIE_CAP[n] (n < 11)
func (p *PcieAst2700V1PLDA) ReadSECONDARYPCIECAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0300 + uint32(n)*4))
}

// WriteSECONDARYPCIECAP writes SECONDARY_PCIE_CAP[n] (n < 11)
func (p *PcieAst2700V1PLDA) WriteSECONDARYPCIECAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0300+uint32(n)*4, uint32(val))
}

// ReadPHY16GTCAP reads Physical Layer 16GT/s extended capability.[n] (n < 12)
func (p *PcieAst2700V1PLDA) ReadPHY16GTCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0340 + uint32(n)*4))
}

// WritePHY16GTCAP writes Physical Layer 16GT/s extended capability.[n] (n < 12)
func (p *PcieAst2700V1PLDA) WritePHY16GTCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0340+uint32(n)*4, uint32(val))
}

// ReadLANEMARGININGCAP reads Lane Margining at the Receiver extended capability.[n] (n < 18)
func (p *PcieAst2700V1PLDA) ReadLANEMARGININGCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0378 + uint32(n)*4))
}

// WriteLANEMARGININGCAP writes Lane Margining at the Receiver extended capability.[n] (n < 18)
func (p *PcieAst2700V1PLDA) WriteLANEMARGININGCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0378+uint32(n)*4, uint32(val))
}

// ReadDEVICESERIALNUMBERCAP reads DEVICE_SERIAL_NUMBER_CAP[n] (n < 3)
func (p *PcieAst2700V1PLDA) ReadDEVICESERIALNUMBERCAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0440 + uint32(n)*4))
}

// WriteDEVICESERIALNUMBERCAP writes DEVICE_SERIAL_NUMBER_CAP[n] (n < 3)
func (p *PcieAst2700V1PLDA) WriteDEVICESERIALNUMBERCAP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0440+uint32(n)*4, uint32(val))
}

