// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// Scu0Ast2700V1SCU0 AST2700 System Control Unit 0 (SCU0), CPU-die. Base address: 0x12C02000. Controls silicon revision, hardware straps, system resets, clock stop, and PLL configuration for the CPU-die peripherals.
type Scu0Ast2700V1SCU0 struct {
    Base uintptr
}

// ReadSILREV reads Silicon Revision ID Register (read-only). [31:24] = BMC generation (0x06 = AST2700 series). [23:16] = Hardware revision (0x00=A0, 0x01=A1). [15:8]  = EFUSE device ID (0x00=AST2750, 0x01=AST2700, 0x02=AST2720). [7:0]   = Compatibility ID (0x03).
func (p *Scu0Ast2700V1SCU0) ReadSILREV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// ReadHWSTRAP1 reads Hardware Strap Register 1. Reflects external strap pin state sampled at power-on. [4:2] = CPU/HPLL frequency selection. [8]   = disable backdoor.
func (p *Scu0Ast2700V1SCU0) ReadHWSTRAP1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// ReadHWSTRAP1CLR reads Hardware Strap 1 Clear Register (write-1-to-clear). Software can override strap bits by writing 1 to this register (clears corresponding HWSTRAP1 bit).
func (p *Scu0Ast2700V1SCU0) ReadHWSTRAP1CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteHWSTRAP1CLR writes Hardware Strap 1 Clear Register (write-1-to-clear). Software can override strap bits by writing 1 to this register (clears corresponding HWSTRAP1 bit).
func (p *Scu0Ast2700V1SCU0) WriteHWSTRAP1CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadHWSTRAP1LOCK reads Hardware Strap 1 write-protection register.
func (p *Scu0Ast2700V1SCU0) ReadHWSTRAP1LOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteHWSTRAP1LOCK writes Hardware Strap 1 write-protection register.
func (p *Scu0Ast2700V1SCU0) WriteHWSTRAP1LOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadHWSTRAP1SECURE reads Hardware Strap 1 secure-control registers.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) ReadHWSTRAP1SECURE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024 + uint32(n)*4))
}

// WriteHWSTRAP1SECURE writes Hardware Strap 1 secure-control registers.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) WriteHWSTRAP1SECURE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0024+uint32(n)*4, uint32(val))
}

// ReadOTPSTRAPEXT reads Extended OTP strap registers.[n] (n < 2)
func (p *Scu0Ast2700V1SCU0) ReadOTPSTRAPEXT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030 + uint32(n)*4))
}

// WriteOTPSTRAPEXT writes Extended OTP strap registers.[n] (n < 2)
func (p *Scu0Ast2700V1SCU0) WriteOTPSTRAPEXT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0030+uint32(n)*4, uint32(val))
}

// ReadRESETLOG reads System reset event log and secure-control registers.[n] (n < 12)
func (p *Scu0Ast2700V1SCU0) ReadRESETLOG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050 + uint32(n)*4))
}

// WriteRESETLOG writes System reset event log and secure-control registers.[n] (n < 12)
func (p *Scu0Ast2700V1SCU0) WriteRESETLOG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0050+uint32(n)*4, uint32(val))
}

// ReadRESETLOG1 reads Reset log register 1.
func (p *Scu0Ast2700V1SCU0) ReadRESETLOG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteRESETLOG1 writes Reset log register 1.
func (p *Scu0Ast2700V1SCU0) WriteRESETLOG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadDEBUGMISC reads Probe, UART debug, miscellaneous, and free-run counter registers.[n] (n < 18)
func (p *Scu0Ast2700V1SCU0) ReadDEBUGMISC(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0 + uint32(n)*4))
}

// WriteDEBUGMISC writes Probe, UART debug, miscellaneous, and free-run counter registers.[n] (n < 18)
func (p *Scu0Ast2700V1SCU0) WriteDEBUGMISC(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x00a0+uint32(n)*4, uint32(val))
}

// ReadPSPCTRL reads PSP processor control registers.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) ReadPSPCTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100 + uint32(n)*4))
}

// WritePSPCTRL writes PSP processor control registers.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) WritePSPCTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0100+uint32(n)*4, uint32(val))
}

// ReadCA35REL reads CA35 core reset release register.
func (p *Scu0Ast2700V1SCU0) ReadCA35REL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x010c))
}

// WriteCA35REL writes CA35 core reset release register.
func (p *Scu0Ast2700V1SCU0) WriteCA35REL(val uint32) {
    reg.Write(uint32(p.Base)+0x010c, uint32(val))
}

// ReadCA35RVBAR reads CA35 reset vector base address registers, one per core.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadCA35RVBAR(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110 + uint32(n)*4))
}

// WriteCA35RVBAR writes CA35 reset vector base address registers, one per core.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteCA35RVBAR(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0110+uint32(n)*4, uint32(val))
}

// ReadSSPCTRL reads SSP coprocessor control register.
func (p *Scu0Ast2700V1SCU0) ReadSSPCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0120))
}

// WriteSSPCTRL writes SSP coprocessor control register.
func (p *Scu0Ast2700V1SCU0) WriteSSPCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0120, uint32(val))
}

// ReadSSPDRAMREMAP0 reads SSP DRAM remap register 0.
func (p *Scu0Ast2700V1SCU0) ReadSSPDRAMREMAP0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0124))
}

// WriteSSPDRAMREMAP0 writes SSP DRAM remap register 0.
func (p *Scu0Ast2700V1SCU0) WriteSSPDRAMREMAP0(val uint32) {
    reg.Write(uint32(p.Base)+0x0124, uint32(val))
}

// ReadSSPDRAMREMAP1 reads SSP DRAM remap register 1.
func (p *Scu0Ast2700V1SCU0) ReadSSPDRAMREMAP1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128))
}

// WriteSSPDRAMREMAP1 writes SSP DRAM remap register 1.
func (p *Scu0Ast2700V1SCU0) WriteSSPDRAMREMAP1(val uint32) {
    reg.Write(uint32(p.Base)+0x0128, uint32(val))
}

// ReadSSPCACHECTRL reads SSP cache control registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadSSPCACHECTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c + uint32(n)*4))
}

// WriteSSPCACHECTRL writes SSP cache control registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteSSPCACHECTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x012c+uint32(n)*4, uint32(val))
}

// ReadSSPWINDOW reads SSP memory window registers.[n] (n < 6)
func (p *Scu0Ast2700V1SCU0) ReadSSPWINDOW(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140 + uint32(n)*4))
}

// WriteSSPWINDOW writes SSP memory window registers.[n] (n < 6)
func (p *Scu0Ast2700V1SCU0) WriteSSPWINDOW(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0140+uint32(n)*4, uint32(val))
}

// ReadTSPCTRL reads TSP coprocessor control register.
func (p *Scu0Ast2700V1SCU0) ReadTSPCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0160))
}

// WriteTSPCTRL writes TSP coprocessor control register.
func (p *Scu0Ast2700V1SCU0) WriteTSPCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0160, uint32(val))
}

// ReadTSPDRAMREMAP reads TSP DRAM remap register.
func (p *Scu0Ast2700V1SCU0) ReadTSPDRAMREMAP() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// WriteTSPDRAMREMAP writes TSP DRAM remap register.
func (p *Scu0Ast2700V1SCU0) WriteTSPDRAMREMAP(val uint32) {
    reg.Write(uint32(p.Base)+0x0168, uint32(val))
}

// ReadTSPCACHECTRL reads TSP cache control registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadTSPCACHECTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x016c + uint32(n)*4))
}

// WriteTSPCACHECTRL writes TSP cache control registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteTSPCACHECTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x016c+uint32(n)*4, uint32(val))
}

// ReadTSPWINDOW reads TSP memory window registers.[n] (n < 2)
func (p *Scu0Ast2700V1SCU0) ReadTSPWINDOW(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0190 + uint32(n)*4))
}

// WriteTSPWINDOW writes TSP memory window registers.[n] (n < 2)
func (p *Scu0Ast2700V1SCU0) WriteTSPWINDOW(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0190+uint32(n)*4, uint32(val))
}

// ReadSCUINTR reads SCU and host interrupt enable/status/log registers.[n] (n < 11)
func (p *Scu0Ast2700V1SCU0) ReadSCUINTR(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01c0 + uint32(n)*4))
}

// WriteSCUINTR writes SCU and host interrupt enable/status/log registers.[n] (n < 11)
func (p *Scu0Ast2700V1SCU0) WriteSCUINTR(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x01c0+uint32(n)*4, uint32(val))
}

// ReadRSTCTRL1 reads System Reset Control Register 1. Write 1 to assert reset to the corresponding peripheral. Write corresponding bit to RST_CLR1 to de-assert. Key bit: [1]=DDRPHY async reset — assert before PHY power sequence.
func (p *Scu0Ast2700V1SCU0) ReadRSTCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// WriteRSTCTRL1 writes System Reset Control Register 1. Write 1 to assert reset to the corresponding peripheral. Write corresponding bit to RST_CLR1 to de-assert. Key bit: [1]=DDRPHY async reset — assert before PHY power sequence.
func (p *Scu0Ast2700V1SCU0) WriteRSTCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x0200, uint32(val))
}

// ReadRSTCLR1 reads System Reset Clear Register 1 (write-to-clear). Write 1 to de-assert the corresponding reset in RST_CTRL1.
func (p *Scu0Ast2700V1SCU0) ReadRSTCLR1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// WriteRSTCLR1 writes System Reset Clear Register 1 (write-to-clear). Write 1 to de-assert the corresponding reset in RST_CTRL1.
func (p *Scu0Ast2700V1SCU0) WriteRSTCLR1(val uint32) {
    reg.Write(uint32(p.Base)+0x0204, uint32(val))
}

// ReadRESETPOLICY reads Reset policy programming window.[n] (n < 11)
func (p *Scu0Ast2700V1SCU0) ReadRESETPOLICY(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0214 + uint32(n)*4))
}

// WriteRESETPOLICY writes Reset policy programming window.[n] (n < 11)
func (p *Scu0Ast2700V1SCU0) WriteRESETPOLICY(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0214+uint32(n)*4, uint32(val))
}

// ReadRSTCTRL2 reads System Reset Control Register 2. Write 1 to assert reset to the corresponding peripheral.
func (p *Scu0Ast2700V1SCU0) ReadRSTCTRL2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0220))
}

// WriteRSTCTRL2 writes System Reset Control Register 2. Write 1 to assert reset to the corresponding peripheral.
func (p *Scu0Ast2700V1SCU0) WriteRSTCTRL2(val uint32) {
    reg.Write(uint32(p.Base)+0x0220, uint32(val))
}

// ReadRSTCLR2 reads System Reset Clear Register 2 (write-to-clear). Write 1 to de-assert the corresponding reset in RST_CTRL2.
func (p *Scu0Ast2700V1SCU0) ReadRSTCLR2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0224))
}

// WriteRSTCLR2 writes System Reset Clear Register 2 (write-to-clear). Write 1 to de-assert the corresponding reset in RST_CTRL2.
func (p *Scu0Ast2700V1SCU0) WriteRSTCLR2(val uint32) {
    reg.Write(uint32(p.Base)+0x0224, uint32(val))
}

// ReadCLKGATE1 reads Clock Gate Control Register 1. Write 1 to stop the corresponding peripheral clock. Read back to check current gate state (1 = clock stopped).
func (p *Scu0Ast2700V1SCU0) ReadCLKGATE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0240))
}

// WriteCLKGATE1 writes Clock Gate Control Register 1. Write 1 to stop the corresponding peripheral clock. Read back to check current gate state (1 = clock stopped).
func (p *Scu0Ast2700V1SCU0) WriteCLKGATE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0240, uint32(val))
}

// ReadCLKGATE1CLR reads Clock Gate Clear Register 1 (write-1-to-enable). Write 1 to enable (un-gate) the corresponding peripheral clock. Used by BootMCU to enable UART12, DDR PHY, DP, UFS, and related clocks.
func (p *Scu0Ast2700V1SCU0) ReadCLKGATE1CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0244))
}

// WriteCLKGATE1CLR writes Clock Gate Clear Register 1 (write-1-to-enable). Write 1 to enable (un-gate) the corresponding peripheral clock. Used by BootMCU to enable UART12, DDR PHY, DP, UFS, and related clocks.
func (p *Scu0Ast2700V1SCU0) WriteCLKGATE1CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0244, uint32(val))
}

// ReadCLOCKPOLICY reads Clock policy programming window.[n] (n < 14)
func (p *Scu0Ast2700V1SCU0) ReadCLOCKPOLICY(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0254 + uint32(n)*4))
}

// WriteCLOCKPOLICY writes Clock policy programming window.[n] (n < 14)
func (p *Scu0Ast2700V1SCU0) WriteCLOCKPOLICY(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0254+uint32(n)*4, uint32(val))
}

// ReadCLOCKSELECT reads Clock selection registers 1-3.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) ReadCLOCKSELECT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0280 + uint32(n)*4))
}

// WriteCLOCKSELECT writes Clock selection registers 1-3.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) WriteCLOCKSELECT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0280+uint32(n)*4, uint32(val))
}

// ReadCLOCKSELECTPOLICYLOCK reads Clock-select policy lock registers.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) ReadCLOCKSELECTPOLICYLOCK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0290 + uint32(n)*4))
}

// WriteCLOCKSELECTPOLICYLOCK writes Clock-select policy lock registers.[n] (n < 3)
func (p *Scu0Ast2700V1SCU0) WriteCLOCKSELECTPOLICYLOCK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0290+uint32(n)*4, uint32(val))
}

// ReadEXTRSTMASK reads External reset mask registers.[n] (n < 2)
func (p *Scu0Ast2700V1SCU0) ReadEXTRSTMASK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02f0 + uint32(n)*4))
}

// WriteEXTRSTMASK writes External reset mask registers.[n] (n < 2)
func (p *Scu0Ast2700V1SCU0) WriteEXTRSTMASK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x02f0+uint32(n)*4, uint32(val))
}

// ReadHPLLPARAM reads HPLL (Host PLL) Parameter Register. Primary PLL for CPU-die high-speed clocks. Typical: 1600 MHz (M=127, N=3, P=0 → 25×128/4/1 = 800 MHz → ×2 = 1600 MHz). [12:0]=M (multiplier−1), [18:13]=N (pre-divider−1), [22:19]=P (post-divider−1), [23]=off, [24]=bypass, [25]=reset.
func (p *Scu0Ast2700V1SCU0) ReadHPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0300))
}

// WriteHPLLPARAM writes HPLL (Host PLL) Parameter Register. Primary PLL for CPU-die high-speed clocks. Typical: 1600 MHz (M=127, N=3, P=0 → 25×128/4/1 = 800 MHz → ×2 = 1600 MHz). [12:0]=M (multiplier−1), [18:13]=N (pre-divider−1), [22:19]=P (post-divider−1), [23]=off, [24]=bypass, [25]=reset.
func (p *Scu0Ast2700V1SCU0) WriteHPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0300, uint32(val))
}

// ReadHPLLEXT reads HPLL Extended Register. [11:0]=BWADJ (bandwidth adjustment, set to M/2 for recommended operation). [31]=LOCK (read-only, 1 when PLL is locked to target frequency).
func (p *Scu0Ast2700V1SCU0) ReadHPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0304))
}

// WriteHPLLEXT writes HPLL Extended Register. [11:0]=BWADJ (bandwidth adjustment, set to M/2 for recommended operation). [31]=LOCK (read-only, 1 when PLL is locked to target frequency).
func (p *Scu0Ast2700V1SCU0) WriteHPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x0304, uint32(val))
}

// ReadDPLLPARAM reads DPLL (Display PLL) Parameter Register. Used for DP and display pixel clocks. Same field layout as HPLL_PARAM.
func (p *Scu0Ast2700V1SCU0) ReadDPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0308))
}

// WriteDPLLPARAM writes DPLL (Display PLL) Parameter Register. Used for DP and display pixel clocks. Same field layout as HPLL_PARAM.
func (p *Scu0Ast2700V1SCU0) WriteDPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0308, uint32(val))
}

// ReadDPLLEXT reads DPLL Extended Register. Same layout as HPLL_EXT.
func (p *Scu0Ast2700V1SCU0) ReadDPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x030c))
}

// WriteDPLLEXT writes DPLL Extended Register. Same layout as HPLL_EXT.
func (p *Scu0Ast2700V1SCU0) WriteDPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x030c, uint32(val))
}

// ReadMPLLPARAM reads MPLL (Memory PLL) Parameter Register. Controls DRAM clock frequency. Example DDR4-3200 (1600 MHz): M=127, N=3, P=0. Same field layout as HPLL_PARAM.
func (p *Scu0Ast2700V1SCU0) ReadMPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0310))
}

// WriteMPLLPARAM writes MPLL (Memory PLL) Parameter Register. Controls DRAM clock frequency. Example DDR4-3200 (1600 MHz): M=127, N=3, P=0. Same field layout as HPLL_PARAM.
func (p *Scu0Ast2700V1SCU0) WriteMPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0310, uint32(val))
}

// ReadMPLLEXT reads MPLL Extended Register. Same layout as HPLL_EXT.
func (p *Scu0Ast2700V1SCU0) ReadMPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0314))
}

// WriteMPLLEXT writes MPLL Extended Register. Same layout as HPLL_EXT.
func (p *Scu0Ast2700V1SCU0) WriteMPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x0314, uint32(val))
}

// ReadDERIVEDCLKPARAM reads D1CLK, D2CLK, CRT1CLK and CRT2CLK parameter registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadDERIVEDCLKPARAM(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0320 + uint32(n)*16))
}

// WriteDERIVEDCLKPARAM writes D1CLK, D2CLK, CRT1CLK and CRT2CLK parameter registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteDERIVEDCLKPARAM(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0320+uint32(n)*16, uint32(val))
}

// ReadFREQCOUNTER reads Frequency counter, comparison, delay-ring, and readback registers.[n] (n < 5)
func (p *Scu0Ast2700V1SCU0) ReadFREQCOUNTER(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x03a0 + uint32(n)*4))
}

// WriteFREQCOUNTER writes Frequency counter, comparison, delay-ring, and readback registers.[n] (n < 5)
func (p *Scu0Ast2700V1SCU0) WriteFREQCOUNTER(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x03a0+uint32(n)*4, uint32(val))
}

// ReadPINMUXCTRL reads Multi-function pin control registers.[n] (n < 6)
func (p *Scu0Ast2700V1SCU0) ReadPINMUXCTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0400 + uint32(n)*4))
}

// WritePINMUXCTRL writes Multi-function pin control registers.[n] (n < 6)
func (p *Scu0Ast2700V1SCU0) WritePINMUXCTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0400+uint32(n)*4, uint32(val))
}

// ReadPINMUXLOCK reads Pinmux register lock registers.[n] (n < 5)
func (p *Scu0Ast2700V1SCU0) ReadPINMUXLOCK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0420 + uint32(n)*4))
}

// WritePINMUXLOCK writes Pinmux register lock registers.[n] (n < 5)
func (p *Scu0Ast2700V1SCU0) WritePINMUXLOCK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0420+uint32(n)*4, uint32(val))
}

// ReadIOCTRL reads GPIO/JTAG/UART/MISC IO control registers.[n] (n < 15)
func (p *Scu0Ast2700V1SCU0) ReadIOCTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0480 + uint32(n)*4))
}

// WriteIOCTRL writes GPIO/JTAG/UART/MISC IO control registers.[n] (n < 15)
func (p *Scu0Ast2700V1SCU0) WriteIOCTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0480+uint32(n)*4, uint32(val))
}

// ReadCPUSMPEP reads CA35 SMP entry point registers, one 64-bit value per core.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadCPUSMPEP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0780 + uint32(n)*8))
}

// WriteCPUSMPEP writes CA35 SMP entry point registers, one 64-bit value per core.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteCPUSMPEP(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0780+uint32(n)*8, uint32(val))
}

// ReadCPUSCRATCH reads CPU-die scratch registers used for SLI and boot handoff.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadCPUSCRATCH(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x07f0 + uint32(n)*4))
}

// WriteCPUSCRATCH writes CPU-die scratch registers used for SLI and boot handoff.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteCPUSCRATCH(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x07f0+uint32(n)*4, uint32(val))
}

// ReadVGA0HANDSHAKE reads VGA0 function handshake registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadVGA0HANDSHAKE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0900 + uint32(n)*4))
}

// WriteVGA0HANDSHAKE writes VGA0 function handshake registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteVGA0HANDSHAKE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0900+uint32(n)*4, uint32(val))
}

// ReadVGA1HANDSHAKE reads VGA1 function handshake registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) ReadVGA1HANDSHAKE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0910 + uint32(n)*4))
}

// WriteVGA1HANDSHAKE writes VGA1 function handshake registers.[n] (n < 4)
func (p *Scu0Ast2700V1SCU0) WriteVGA1HANDSHAKE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0910+uint32(n)*4, uint32(val))
}

// ReadVGA0SCRATCH reads VGA0 scratch registers.[n] (n < 8)
func (p *Scu0Ast2700V1SCU0) ReadVGA0SCRATCH(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0920 + uint32(n)*4))
}

// WriteVGA0SCRATCH writes VGA0 scratch registers.[n] (n < 8)
func (p *Scu0Ast2700V1SCU0) WriteVGA0SCRATCH(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0920+uint32(n)*4, uint32(val))
}

// ReadVGA1SCRATCH reads VGA1 scratch registers.[n] (n < 8)
func (p *Scu0Ast2700V1SCU0) ReadVGA1SCRATCH(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0940 + uint32(n)*4))
}

// WriteVGA1SCRATCH writes VGA1 scratch registers.[n] (n < 8)
func (p *Scu0Ast2700V1SCU0) WriteVGA1SCRATCH(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0940+uint32(n)*4, uint32(val))
}

// ReadPCIMISC reads SCU PCI miscellaneous registers.[n] (n < 64)
func (p *Scu0Ast2700V1SCU0) ReadPCIMISC(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a00 + uint32(n)*4))
}

// WritePCIMISC writes SCU PCI miscellaneous registers.[n] (n < 64)
func (p *Scu0Ast2700V1SCU0) WritePCIMISC(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0a00+uint32(n)*4, uint32(val))
}

// ReadPCI0MISC70 reads PCIe node 0 miscellaneous register 0x70.
func (p *Scu0Ast2700V1SCU0) ReadPCI0MISC70() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a70))
}

// WritePCI0MISC70 writes PCIe node 0 miscellaneous register 0x70.
func (p *Scu0Ast2700V1SCU0) WritePCI0MISC70(val uint32) {
    reg.Write(uint32(p.Base)+0x0a70, uint32(val))
}

// ReadPCI1MISC70 reads PCIe node 1 miscellaneous register 0x70.
func (p *Scu0Ast2700V1SCU0) ReadPCI1MISC70() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0af0))
}

// WritePCI1MISC70 writes PCIe node 1 miscellaneous register 0x70.
func (p *Scu0Ast2700V1SCU0) WritePCI1MISC70(val uint32) {
    reg.Write(uint32(p.Base)+0x0af0, uint32(val))
}

// ReadWRITESECURE0 reads Write secure-control set 0 registers.[n] (n < 22)
func (p *Scu0Ast2700V1SCU0) ReadWRITESECURE0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0b00 + uint32(n)*4))
}

// WriteWRITESECURE0 writes Write secure-control set 0 registers.[n] (n < 22)
func (p *Scu0Ast2700V1SCU0) WriteWRITESECURE0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0b00+uint32(n)*4, uint32(val))
}

// ReadWRITESECURE1 reads Write secure-control set 1 registers.[n] (n < 22)
func (p *Scu0Ast2700V1SCU0) ReadWRITESECURE1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0c00 + uint32(n)*4))
}

// WriteWRITESECURE1 writes Write secure-control set 1 registers.[n] (n < 22)
func (p *Scu0Ast2700V1SCU0) WriteWRITESECURE1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0c00+uint32(n)*4, uint32(val))
}

// ReadWRITESECURE2 reads Write secure-control set 2 registers.[n] (n < 22)
func (p *Scu0Ast2700V1SCU0) ReadWRITESECURE2(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0d00 + uint32(n)*4))
}

// WriteWRITESECURE2 writes Write secure-control set 2 registers.[n] (n < 22)
func (p *Scu0Ast2700V1SCU0) WriteWRITESECURE2(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0d00+uint32(n)*4, uint32(val))
}

// ReadWRITEPROTECT reads Write-protection registers.[n] (n < 32)
func (p *Scu0Ast2700V1SCU0) ReadWRITEPROTECT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0e00 + uint32(n)*4))
}

// WriteWRITEPROTECT writes Write-protection registers.[n] (n < 32)
func (p *Scu0Ast2700V1SCU0) WriteWRITEPROTECT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0e00+uint32(n)*4, uint32(val))
}

// ReadRESETPOLICYLOCK reads Reset and clock policy lock register.
func (p *Scu0Ast2700V1SCU0) ReadRESETPOLICYLOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0e10))
}

// WriteRESETPOLICYLOCK writes Reset and clock policy lock register.
func (p *Scu0Ast2700V1SCU0) WriteRESETPOLICYLOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0e10, uint32(val))
}

// ReadRESETSOURCECTRL reads Reset source control registers.[n] (n < 32)
func (p *Scu0Ast2700V1SCU0) ReadRESETSOURCECTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0f00 + uint32(n)*4))
}

// WriteRESETSOURCECTRL writes Reset source control registers.[n] (n < 32)
func (p *Scu0Ast2700V1SCU0) WriteRESETSOURCECTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0f00+uint32(n)*4, uint32(val))
}

