// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// Scu1Ast2700V1SCU1 AST2700 System Control Unit 1 (SCU1), IO-die. Base address: 0x14C02000. Controls IO-die hardware straps (including DDR type), Caliptra subsystem power and status, system resets, and PLL configuration for IO-die peripherals.
type Scu1Ast2700V1SCU1 struct {
    Base uintptr
}

// ReadSILREV reads Silicon Revision ID Register (read-only). Same layout as SCU0.SIL_REV. [31:24]=BMC generation, [23:16]=HW revision, [15:8]=EFUSE device ID, [7:0]=compat ID.
func (p *Scu1Ast2700V1SCU1) ReadSILREV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// ReadHWSTRAP1 reads Hardware/OTP Strap Register 1 (read-only at runtime). Reflects strap pins and OTP fuse state sampled at power-on. Key bit: [10]=DDR4/DDR5 selection (0=DDR5, 1=DDR4).
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// ReadHWSTRAP1CLR reads Hardware Strap 1 Clear Register (write-1-to-clear). Software override for strap bits (dev/test use only).
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP1CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteHWSTRAP1CLR writes Hardware Strap 1 Clear Register (write-1-to-clear). Software override for strap bits (dev/test use only).
func (p *Scu1Ast2700V1SCU1) WriteHWSTRAP1CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadHWSTRAP1LOCK reads Hardware/OTP Strap 1 write-protection register.
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP1LOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteHWSTRAP1LOCK writes Hardware/OTP Strap 1 write-protection register.
func (p *Scu1Ast2700V1SCU1) WriteHWSTRAP1LOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadHWSTRAP1SECURE reads Hardware/OTP Strap 1 secure-control registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP1SECURE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024 + uint32(n)*4))
}

// WriteHWSTRAP1SECURE writes Hardware/OTP Strap 1 secure-control registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) WriteHWSTRAP1SECURE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0024+uint32(n)*4, uint32(val))
}

// ReadHWSTRAP2 reads Hardware/OTP Strap Register 2 (read-only at runtime). Boot media, flash, and CPTRA debug configuration.
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// ReadHWSTRAP2CLR reads Hardware/OTP Strap 2 clear register.
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP2CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteHWSTRAP2CLR writes Hardware/OTP Strap 2 clear register.
func (p *Scu1Ast2700V1SCU1) WriteHWSTRAP2CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadHWSTRAP2LOCK reads Hardware/OTP Strap 2 write-protection register.
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP2LOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteHWSTRAP2LOCK writes Hardware/OTP Strap 2 write-protection register.
func (p *Scu1Ast2700V1SCU1) WriteHWSTRAP2LOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadHWSTRAP2SECURE reads Hardware/OTP Strap 2 secure-control registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) ReadHWSTRAP2SECURE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044 + uint32(n)*4))
}

// WriteHWSTRAP2SECURE writes Hardware/OTP Strap 2 secure-control registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) WriteHWSTRAP2SECURE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0044+uint32(n)*4, uint32(val))
}

// ReadRESETLOG reads System reset event log and secure-control registers.[n] (n < 16)
func (p *Scu1Ast2700V1SCU1) ReadRESETLOG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050 + uint32(n)*4))
}

// WriteRESETLOG writes System reset event log and secure-control registers.[n] (n < 16)
func (p *Scu1Ast2700V1SCU1) WriteRESETLOG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0050+uint32(n)*4, uint32(val))
}

// ReadDEBUGMISC reads Debug, heartbeat, DAC, video input, RNG and interrupt registers.[n] (n < 27)
func (p *Scu1Ast2700V1SCU1) ReadDEBUGMISC(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac + uint32(n)*4))
}

// WriteDEBUGMISC writes Debug, heartbeat, DAC, video input, RNG and interrupt registers.[n] (n < 27)
func (p *Scu1Ast2700V1SCU1) WriteDEBUGMISC(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x00ac+uint32(n)*4, uint32(val))
}

// ReadMCU0CTRL reads BootMCU remap/control register.
func (p *Scu1Ast2700V1SCU1) ReadMCU0CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110))
}

// WriteMCU0CTRL writes BootMCU remap/control register.
func (p *Scu1Ast2700V1SCU1) WriteMCU0CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0110, uint32(val))
}

// ReadCPTRACTRL reads Caliptra Control and Status Register. [31:24] = read-only Caliptra status flags (RDY_FOR_RT etc.) [3:0]   = read-write Caliptra control bits (PWRGOOD etc.) SoC ROM writes PWRGOOD at early boot; FMC code reads status bits.
func (p *Scu1Ast2700V1SCU1) ReadCPTRACTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0130))
}

// WriteCPTRACTRL writes Caliptra Control and Status Register. [31:24] = read-only Caliptra status flags (RDY_FOR_RT etc.) [3:0]   = read-write Caliptra control bits (PWRGOOD etc.) SoC ROM writes PWRGOOD at early boot; FMC code reads status bits.
func (p *Scu1Ast2700V1SCU1) WriteCPTRACTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0130, uint32(val))
}

// ReadCPTRAWRPROT reads Caliptra Write Protection Register (write-1-to-set, RW1S). Writing 1 permanently locks the corresponding CPTRA register for this boot cycle.
func (p *Scu1Ast2700V1SCU1) ReadCPTRAWRPROT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WriteCPTRAWRPROT writes Caliptra Write Protection Register (write-1-to-set, RW1S). Writing 1 permanently locks the corresponding CPTRA register for this boot cycle.
func (p *Scu1Ast2700V1SCU1) WriteCPTRAWRPROT(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadCPTRARSTCTRL reads Caliptra Reset Control Register. [2]=reset-tolerance enable.
func (p *Scu1Ast2700V1SCU1) ReadCPTRARSTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x013c))
}

// WriteCPTRARSTCTRL writes Caliptra Reset Control Register. [2]=reset-tolerance enable.
func (p *Scu1Ast2700V1SCU1) WriteCPTRARSTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x013c, uint32(val))
}

// ReadCPTRAOBFKEY reads Caliptra Obfuscation Key Words [0..7]. Write-only (BootMCU access only). 8 × 32-bit words providing the 256-bit obfuscation key.
// [n] (n < 8)
func (p *Scu1Ast2700V1SCU1) ReadCPTRAOBFKEY(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140 + uint32(n)*4))
}

// WriteCPTRAOBFKEY writes Caliptra Obfuscation Key Words [0..7]. Write-only (BootMCU access only). 8 × 32-bit words providing the 256-bit obfuscation key.
// [n] (n < 8)
func (p *Scu1Ast2700V1SCU1) WriteCPTRAOBFKEY(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0140+uint32(n)*4, uint32(val))
}

// ReadCPTRAGENERICIN0 reads Caliptra Generic Input Register [31:0]. BootMCU writable; Caliptra readable. Used for boot state passing.
func (p *Scu1Ast2700V1SCU1) ReadCPTRAGENERICIN0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0160))
}

// WriteCPTRAGENERICIN0 writes Caliptra Generic Input Register [31:0]. BootMCU writable; Caliptra readable. Used for boot state passing.
func (p *Scu1Ast2700V1SCU1) WriteCPTRAGENERICIN0(val uint32) {
    reg.Write(uint32(p.Base)+0x0160, uint32(val))
}

// ReadCPTRAGENERICIN1 reads Caliptra Generic Input Register [63:32]. BootMCU writable; Caliptra readable.
func (p *Scu1Ast2700V1SCU1) ReadCPTRAGENERICIN1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0164))
}

// WriteCPTRAGENERICIN1 writes Caliptra Generic Input Register [63:32]. BootMCU writable; Caliptra readable.
func (p *Scu1Ast2700V1SCU1) WriteCPTRAGENERICIN1(val uint32) {
    reg.Write(uint32(p.Base)+0x0164, uint32(val))
}

// ReadCPTRAGENERICOUT0 reads Caliptra Generic Output Register [31:0] (read-only from BootMCU). Written by Caliptra firmware; read by BootMCU for status.
func (p *Scu1Ast2700V1SCU1) ReadCPTRAGENERICOUT0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// ReadCPTRAGENERICOUT1 reads Caliptra Generic Output Register [63:32] (read-only from BootMCU).
func (p *Scu1Ast2700V1SCU1) ReadCPTRAGENERICOUT1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x016c))
}

// ReadCPTRAINTRSTS reads Caliptra Interrupt Status Register. Edge-triggered; write-1-to-clear (RW1C).
func (p *Scu1Ast2700V1SCU1) ReadCPTRAINTRSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0170))
}

// WriteCPTRAINTRSTS writes Caliptra Interrupt Status Register. Edge-triggered; write-1-to-clear (RW1C).
func (p *Scu1Ast2700V1SCU1) WriteCPTRAINTRSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x0170, uint32(val))
}

// ReadCPTRAINTREN reads Caliptra Interrupt Enable Register. 1 = enable corresponding interrupt to BootMCU.
func (p *Scu1Ast2700V1SCU1) ReadCPTRAINTREN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0174))
}

// WriteCPTRAINTREN writes Caliptra Interrupt Enable Register. 1 = enable corresponding interrupt to BootMCU.
func (p *Scu1Ast2700V1SCU1) WriteCPTRAINTREN(val uint32) {
    reg.Write(uint32(p.Base)+0x0174, uint32(val))
}

// ReadCPTRAMISC reads Caliptra integration registers not modeled individually.[n] (n < 30)
func (p *Scu1Ast2700V1SCU1) ReadCPTRAMISC(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0178 + uint32(n)*4))
}

// WriteCPTRAMISC writes Caliptra integration registers not modeled individually.[n] (n < 30)
func (p *Scu1Ast2700V1SCU1) WriteCPTRAMISC(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0178+uint32(n)*4, uint32(val))
}

// ReadSCRATCH reads IO-die scratch registers used for SLI and boot handoff.[n] (n < 4)
func (p *Scu1Ast2700V1SCU1) ReadSCRATCH(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01f0 + uint32(n)*4))
}

// WriteSCRATCH writes IO-die scratch registers used for SLI and boot handoff.[n] (n < 4)
func (p *Scu1Ast2700V1SCU1) WriteSCRATCH(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x01f0+uint32(n)*4, uint32(val))
}

// ReadRSTCTRL1 reads IO-die System Reset Control Register 1. Write 1 to assert reset. Write to RST_CLR1 to de-assert. Key bit: [9]=CPTRA — reset the Caliptra subsystem.
func (p *Scu1Ast2700V1SCU1) ReadRSTCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// WriteRSTCTRL1 writes IO-die System Reset Control Register 1. Write 1 to assert reset. Write to RST_CLR1 to de-assert. Key bit: [9]=CPTRA — reset the Caliptra subsystem.
func (p *Scu1Ast2700V1SCU1) WriteRSTCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x0200, uint32(val))
}

// ReadRSTCLR1 reads IO-die System Reset Clear Register 1 (write-to-clear).
func (p *Scu1Ast2700V1SCU1) ReadRSTCLR1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// WriteRSTCLR1 writes IO-die System Reset Clear Register 1 (write-to-clear).
func (p *Scu1Ast2700V1SCU1) WriteRSTCLR1(val uint32) {
    reg.Write(uint32(p.Base)+0x0204, uint32(val))
}

// ReadRESETPOLICY reads Reset policy programming window.[n] (n < 11)
func (p *Scu1Ast2700V1SCU1) ReadRESETPOLICY(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0214 + uint32(n)*4))
}

// WriteRESETPOLICY writes Reset policy programming window.[n] (n < 11)
func (p *Scu1Ast2700V1SCU1) WriteRESETPOLICY(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0214+uint32(n)*4, uint32(val))
}

// ReadRSTCTRL2 reads IO-die System Reset Control Register 2.
func (p *Scu1Ast2700V1SCU1) ReadRSTCTRL2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0220))
}

// WriteRSTCTRL2 writes IO-die System Reset Control Register 2.
func (p *Scu1Ast2700V1SCU1) WriteRSTCTRL2(val uint32) {
    reg.Write(uint32(p.Base)+0x0220, uint32(val))
}

// ReadRSTCLR2 reads IO-die System Reset Clear Register 2.
func (p *Scu1Ast2700V1SCU1) ReadRSTCLR2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0224))
}

// WriteRSTCLR2 writes IO-die System Reset Clear Register 2.
func (p *Scu1Ast2700V1SCU1) WriteRSTCLR2(val uint32) {
    reg.Write(uint32(p.Base)+0x0224, uint32(val))
}

// ReadCLOCKPOLICY reads Clock policy programming window.[n] (n < 15)
func (p *Scu1Ast2700V1SCU1) ReadCLOCKPOLICY(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0254 + uint32(n)*4))
}

// WriteCLOCKPOLICY writes Clock policy programming window.[n] (n < 15)
func (p *Scu1Ast2700V1SCU1) WriteCLOCKPOLICY(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0254+uint32(n)*4, uint32(val))
}

// ReadCLKGATE2 reads Clock Stop Control 2 register.
func (p *Scu1Ast2700V1SCU1) ReadCLKGATE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0260))
}

// WriteCLKGATE2 writes Clock Stop Control 2 register.
func (p *Scu1Ast2700V1SCU1) WriteCLKGATE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0260, uint32(val))
}

// ReadCLKGATE2CLR reads Clock Stop Clear 2 register.
func (p *Scu1Ast2700V1SCU1) ReadCLKGATE2CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0264))
}

// WriteCLKGATE2CLR writes Clock Stop Clear 2 register.
func (p *Scu1Ast2700V1SCU1) WriteCLKGATE2CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0264, uint32(val))
}

// ReadCLOCKSELECT reads Clock selection registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) ReadCLOCKSELECT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0280 + uint32(n)*4))
}

// WriteCLOCKSELECT writes Clock selection registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) WriteCLOCKSELECT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0280+uint32(n)*4, uint32(val))
}

// ReadCLOCKSELECTLOCK reads Clock selection lock registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) ReadCLOCKSELECTLOCK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02a0 + uint32(n)*16))
}

// WriteCLOCKSELECTLOCK writes Clock selection lock registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) WriteCLOCKSELECTLOCK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x02a0+uint32(n)*16, uint32(val))
}

// ReadEXTRSTMASK reads External reset mask registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) ReadEXTRSTMASK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02f0 + uint32(n)*4))
}

// WriteEXTRSTMASK writes External reset mask registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) WriteEXTRSTMASK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x02f0+uint32(n)*4, uint32(val))
}

// ReadHPLLPARAM reads IO-die HPLL Parameter Register. Drives IO-die high-speed clocks (UART, I2C, I3C, etc.). Same field layout as SCU0.HPLL_PARAM.
func (p *Scu1Ast2700V1SCU1) ReadHPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0300))
}

// WriteHPLLPARAM writes IO-die HPLL Parameter Register. Drives IO-die high-speed clocks (UART, I2C, I3C, etc.). Same field layout as SCU0.HPLL_PARAM.
func (p *Scu1Ast2700V1SCU1) WriteHPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0300, uint32(val))
}

// ReadHPLLEXT reads IO-die HPLL Extended Register (BWADJ + LOCK).
func (p *Scu1Ast2700V1SCU1) ReadHPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0304))
}

// WriteHPLLEXT writes IO-die HPLL Extended Register (BWADJ + LOCK).
func (p *Scu1Ast2700V1SCU1) WriteHPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x0304, uint32(val))
}

// ReadAPLLPARAM reads IO-die APLL (Audio PLL) Parameter Register. Drives USB and audio clocks. Same field layout as SCU0.HPLL_PARAM.
func (p *Scu1Ast2700V1SCU1) ReadAPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0310))
}

// WriteAPLLPARAM writes IO-die APLL (Audio PLL) Parameter Register. Drives USB and audio clocks. Same field layout as SCU0.HPLL_PARAM.
func (p *Scu1Ast2700V1SCU1) WriteAPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0310, uint32(val))
}

// ReadAPLLEXT reads IO-die APLL Extended Register.
func (p *Scu1Ast2700V1SCU1) ReadAPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0314))
}

// WriteAPLLEXT writes IO-die APLL Extended Register.
func (p *Scu1Ast2700V1SCU1) WriteAPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x0314, uint32(val))
}

// ReadDPLLPARAM reads IO-die DPLL Parameter Register.
func (p *Scu1Ast2700V1SCU1) ReadDPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0320))
}

// WriteDPLLPARAM writes IO-die DPLL Parameter Register.
func (p *Scu1Ast2700V1SCU1) WriteDPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0320, uint32(val))
}

// ReadDPLLEXT reads IO-die DPLL Extended Parameter Register.
func (p *Scu1Ast2700V1SCU1) ReadDPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0324))
}

// WriteDPLLEXT writes IO-die DPLL Extended Parameter Register.
func (p *Scu1Ast2700V1SCU1) WriteDPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x0324, uint32(val))
}

// ReadDPLLPARAMREAD reads IO-die DPLL Parameter Read Register.
func (p *Scu1Ast2700V1SCU1) ReadDPLLPARAMREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0328))
}

// ReadDPLLEXTREAD reads IO-die DPLL Extended Parameter Read Register.
func (p *Scu1Ast2700V1SCU1) ReadDPLLEXTREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x032c))
}

// ReadUARTCLKGEN reads UART clock generation registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) ReadUARTCLKGEN(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0330 + uint32(n)*4))
}

// WriteUARTCLKGEN writes UART clock generation registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) WriteUARTCLKGEN(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0330+uint32(n)*4, uint32(val))
}

// ReadLINKPLL reads L0/L1 PLL parameter and extended registers.[n] (n < 6)
func (p *Scu1Ast2700V1SCU1) ReadLINKPLL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0340 + uint32(n)*4))
}

// WriteLINKPLL writes L0/L1 PLL parameter and extended registers.[n] (n < 6)
func (p *Scu1Ast2700V1SCU1) WriteLINKPLL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0340+uint32(n)*4, uint32(val))
}

// ReadCLOCKMEASURE reads Clock duty measurement and frequency counter registers.[n] (n < 13)
func (p *Scu1Ast2700V1SCU1) ReadCLOCKMEASURE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0380 + uint32(n)*4))
}

// WriteCLOCKMEASURE writes Clock duty measurement and frequency counter registers.[n] (n < 13)
func (p *Scu1Ast2700V1SCU1) WriteCLOCKMEASURE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0380+uint32(n)*4, uint32(val))
}

// ReadUSBCTRL reads USB controller and lock registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) ReadUSBCTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x03b0 + uint32(n)*4))
}

// WriteUSBCTRL writes USB controller and lock registers.[n] (n < 2)
func (p *Scu1Ast2700V1SCU1) WriteUSBCTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x03b0+uint32(n)*4, uint32(val))
}

// ReadPINMUXCTRL reads Multi-function pin control registers.[n] (n < 28)
func (p *Scu1Ast2700V1SCU1) ReadPINMUXCTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0400 + uint32(n)*4))
}

// WritePINMUXCTRL writes Multi-function pin control registers.[n] (n < 28)
func (p *Scu1Ast2700V1SCU1) WritePINMUXCTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0400+uint32(n)*4, uint32(val))
}

// ReadIOSECURE reads IO/VOLT secure-control registers.[n] (n < 105)
func (p *Scu1Ast2700V1SCU1) ReadIOSECURE(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0500 + uint32(n)*4))
}

// WriteIOSECURE writes IO/VOLT secure-control registers.[n] (n < 105)
func (p *Scu1Ast2700V1SCU1) WriteIOSECURE(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0500+uint32(n)*4, uint32(val))
}

// ReadEFUSECTRL reads EFUSE control/data/command registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) ReadEFUSECTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0800 + uint32(n)*4))
}

// WriteEFUSECTRL writes EFUSE control/data/command registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) WriteEFUSECTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0800+uint32(n)*4, uint32(val))
}

// ReadCHIPID reads Chip unique and reserved read-only ID registers.[n] (n < 8)
func (p *Scu1Ast2700V1SCU1) ReadCHIPID(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0810 + uint32(n)*4))
}

// ReadMCUSCRATCH reads Scratch registers for MCU firmware.[n] (n < 16)
func (p *Scu1Ast2700V1SCU1) ReadMCUSCRATCH(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0880 + uint32(n)*4))
}

// WriteMCUSCRATCH writes Scratch registers for MCU firmware.[n] (n < 16)
func (p *Scu1Ast2700V1SCU1) WriteMCUSCRATCH(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0880+uint32(n)*4, uint32(val))
}

// ReadPCIE3CONFIG reads PCIe 3 BMC device/control registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) ReadPCIE3CONFIG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0900 + uint32(n)*4))
}

// WritePCIE3CONFIG writes PCIe 3 BMC device/control registers.[n] (n < 3)
func (p *Scu1Ast2700V1SCU1) WritePCIE3CONFIG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0900+uint32(n)*4, uint32(val))
}

// ReadHOSTCONFIG reads Host configuration, clear, lock, and secure-control registers.[n] (n < 16)
func (p *Scu1Ast2700V1SCU1) ReadHOSTCONFIG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a00 + uint32(n)*4))
}

// WriteHOSTCONFIG writes Host configuration, clear, lock, and secure-control registers.[n] (n < 16)
func (p *Scu1Ast2700V1SCU1) WriteHOSTCONFIG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0a00+uint32(n)*4, uint32(val))
}

// ReadSECURECONTROL reads SCU1 secure-control registers.[n] (n < 86)
func (p *Scu1Ast2700V1SCU1) ReadSECURECONTROL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0c00 + uint32(n)*4))
}

// WriteSECURECONTROL writes SCU1 secure-control registers.[n] (n < 86)
func (p *Scu1Ast2700V1SCU1) WriteSECURECONTROL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0c00+uint32(n)*4, uint32(val))
}

// ReadWRITEPROTECT reads SCU1 write-protection registers.[n] (n < 32)
func (p *Scu1Ast2700V1SCU1) ReadWRITEPROTECT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0e00 + uint32(n)*4))
}

// WriteWRITEPROTECT writes SCU1 write-protection registers.[n] (n < 32)
func (p *Scu1Ast2700V1SCU1) WriteWRITEPROTECT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0e00+uint32(n)*4, uint32(val))
}

// ReadRESETPOLICYLOCK reads Reset policy lock register.
func (p *Scu1Ast2700V1SCU1) ReadRESETPOLICYLOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0e10))
}

// WriteRESETPOLICYLOCK writes Reset policy lock register.
func (p *Scu1Ast2700V1SCU1) WriteRESETPOLICYLOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0e10, uint32(val))
}

// ReadRESETSOURCECTRL reads SCU1 reset source control registers.[n] (n < 32)
func (p *Scu1Ast2700V1SCU1) ReadRESETSOURCECTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0f00 + uint32(n)*4))
}

// WriteRESETSOURCECTRL writes SCU1 reset source control registers.[n] (n < 32)
func (p *Scu1Ast2700V1SCU1) WriteRESETSOURCECTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0f00+uint32(n)*4, uint32(val))
}

