// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// SdrammcAst2700V1SDRAMMC AST2700 SDRAM Memory Controller (DRAMC). Base address: 0x12C00000. PHY base: 0x13000000 (DWC DDR PHY, 16-bit APB). All registers require unlock via PROTECT = 0x1688A8A8 before write.
type SdrammcAst2700V1SDRAMMC struct {
    Base uintptr
}

// ReadPROTECT reads Register protection key. Write 0x1688A8A8 to unlock all protected registers. Write any other value to soft-lock. Write 0xDEADDEAD to hard-lock until next system reset. Read: 0x1 = unlocked, 0x0 = soft-locked, 0x10 = hard-locked.
func (p *SdrammcAst2700V1SDRAMMC) ReadPROTECT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WritePROTECT writes Register protection key. Write 0x1688A8A8 to unlock all protected registers. Write any other value to soft-lock. Write 0xDEADDEAD to hard-lock until next system reset. Read: 0x1 = unlocked, 0x0 = soft-locked, 0x10 = hard-locked.
func (p *SdrammcAst2700V1SDRAMMC) WritePROTECT(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadINTRSTS reads Interrupt status register. Bits are set by hardware events. Write 1 to INTR_CLR to acknowledge.
func (p *SdrammcAst2700V1SDRAMMC) ReadINTRSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// ReadINTRCLR reads Interrupt clear register. Write 1 to each bit to clear the corresponding INTR_STS bit.
func (p *SdrammcAst2700V1SDRAMMC) ReadINTRCLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteINTRCLR writes Interrupt clear register. Write 1 to each bit to clear the corresponding INTR_STS bit.
func (p *SdrammcAst2700V1SDRAMMC) WriteINTRCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadINTRMASK reads Interrupt mask register. 0 = interrupt enabled, 1 = masked.
func (p *SdrammcAst2700V1SDRAMMC) ReadINTRMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteINTRMASK writes Interrupt mask register. 0 = interrupt enabled, 1 = masked.
func (p *SdrammcAst2700V1SDRAMMC) WriteINTRMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMAINCONF reads Main configuration register (protected). Must be written before triggering DDRPHY init.
func (p *SdrammcAst2700V1SDRAMMC) ReadMAINCONF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMAINCONF writes Main configuration register (protected). Must be written before triggering DDRPHY init.
func (p *SdrammcAst2700V1SDRAMMC) WriteMAINCONF(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadMAINCTRL reads Main control register (protected). Trigger bits (W1T) are self-clearing after the operation starts.
func (p *SdrammcAst2700V1SDRAMMC) ReadMAINCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteMAINCTRL writes Main control register (protected). Trigger bits (W1T) are self-clearing after the operation starts.
func (p *SdrammcAst2700V1SDRAMMC) WriteMAINCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadMAINSTS reads Main status register (read-only).
func (p *SdrammcAst2700V1SDRAMMC) ReadMAINSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// ReadERRSTS reads Error status register (read-only). Contains error codes for the most recent error event.
func (p *SdrammcAst2700V1SDRAMMC) ReadERRSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// ReadACTIMING1 reads AC Timing Register 1 (protected). [31:28]=tCCD_L, [27:24]=tRRD_L, [23:20]=tRRD, [15:8]=tMOD/tMRD. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteACTIMING1 writes AC Timing Register 1 (protected). [31:28]=tCCD_L, [27:24]=tRRD_L, [23:20]=tRRD, [15:8]=tMOD/tMRD. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING1(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadACTIMING2 reads AC Timing Register 2 (protected). [31:24]=tFAW, [23:16]=tRP, [15:8]=tRAS, [7:0]=tRCD. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteACTIMING2 writes AC Timing Register 2 (protected). [31:24]=tFAW, [23:16]=tRP, [15:8]=tRAS, [7:0]=tRCD. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING2(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadACTIMING3 reads AC Timing Register 3 (protected). [31:24]=WL+BL/2+tWTR (S), [23:16]=RTW, [15:8]=WL+BL/2+tWR, [7:0]=tRTP. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteACTIMING3 writes AC Timing Register 3 (protected). [31:24]=WL+BL/2+tWTR (S), [23:16]=RTW, [15:8]=WL+BL/2+tWR, [7:0]=tRTP. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING3(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadACTIMING4 reads AC Timing Register 4 (protected). [31:24]=WL+BL/2+tWTRA (DDR5), [23:16]=WL+BL/2+tWTR_L. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteACTIMING4 writes AC Timing Register 4 (protected). [31:24]=WL+BL/2+tWTRA (DDR5), [23:16]=WL+BL/2+tWTR_L. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING4(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadACTIMING5 reads AC Timing Register 5 (protected). [31:20]=tREFSBRD (DDR5), [19:10]=tRFCsb (DDR5), [9:0]=tRFC. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteACTIMING5 writes AC Timing Register 5 (protected). [31:20]=tREFSBRD (DDR5), [19:10]=tRFCsb (DDR5), [9:0]=tRFC. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING5(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadACTIMING6 reads AC Timing Register 6 (protected). [31:24]=tCSH_SRexit, [23:16]=tPD, [15:8]=tXP, [7:0]=tCKSRE/tCKSRX. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteACTIMING6 writes AC Timing Register 6 (protected). [31:24]=tCSH_SRexit, [23:16]=tPD, [15:8]=tXP, [7:0]=tCKSRE/tCKSRX. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING6(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadACTIMING7 reads AC Timing Register 7 (protected). [31:16]=tZQCS/tZQLat, [15:0]=tDLLK. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) ReadACTIMING7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteACTIMING7 writes AC Timing Register 7 (protected). [31:16]=tZQCS/tZQLat, [15:0]=tDLLK. Units: DRAM clock cycles.
func (p *SdrammcAst2700V1SDRAMMC) WriteACTIMING7(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadDFITIMING reads DFI Timing Register (protected). [31:28]=ODT latency, [27:24]=t_phy_odtlat, [23:16]=t_phy_rddata_en, [15:8]=t_phy_wrdata, [7:0]=t_phy_wrlat.
func (p *SdrammcAst2700V1SDRAMMC) ReadDFITIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteDFITIMING writes DFI Timing Register (protected). [31:28]=ODT latency, [27:24]=t_phy_odtlat, [23:16]=t_phy_rddata_en, [15:8]=t_phy_wrdata, [7:0]=t_phy_wrlat.
func (p *SdrammcAst2700V1SDRAMMC) WriteDFITIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadDFICONF reads DFI Configuration Register (protected). [7]=DM-polarity, [6:5]=CKE-after-init, [4]=DFI-reset, [3:2]=LP-wakeup, [1:0]=freq-encoding.
func (p *SdrammcAst2700V1SDRAMMC) ReadDFICONF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteDFICONF writes DFI Configuration Register (protected). [7]=DM-polarity, [6:5]=CKE-after-init, [4]=DFI-reset, [3:2]=LP-wakeup, [1:0]=freq-encoding.
func (p *SdrammcAst2700V1SDRAMMC) WriteDFICONF(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadDFIMSG reads DFI Message Register (protected). [23:8]=message-data, [7:0]=message (default 0x08 = PVT optimisation).
func (p *SdrammcAst2700V1SDRAMMC) ReadDFIMSG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteDFIMSG writes DFI Message Register (protected). [23:8]=message-data, [7:0]=message (default 0x08 = PVT optimisation).
func (p *SdrammcAst2700V1SDRAMMC) WriteDFIMSG(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadMRCTRL reads Mode Register Control (protected). Write trigger bit (bit 0) to issue an MR read or write command.
func (p *SdrammcAst2700V1SDRAMMC) ReadMRCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteMRCTRL writes Mode Register Control (protected). Write trigger bit (bit 0) to issue an MR read or write command.
func (p *SdrammcAst2700V1SDRAMMC) WriteMRCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadMRWROPCODE reads Mode Register Write Opcode — DDR5 only (protected). [31:24]=MR-address, [15:8]=MR-op, [3:0]=rank-select.
func (p *SdrammcAst2700V1SDRAMMC) ReadMRWROPCODE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteMRWROPCODE writes Mode Register Write Opcode — DDR5 only (protected). [31:24]=MR-address, [15:8]=MR-op, [3:0]=rank-select.
func (p *SdrammcAst2700V1SDRAMMC) WriteMRWROPCODE(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadMRRDOPCODE reads Mode Register Read Opcode — DDR5 only (read-only). Filled by hardware after MRR; [15:8]=data, [7:0]=address.
func (p *SdrammcAst2700V1SDRAMMC) ReadMRRDOPCODE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// ReadMR01 reads DDR4 Mode Register 0 and 1 (protected). [31:16]=MR1, [15:0]=MR0. MR0: CL, burst-type, burst-length, DLL-reset. MR1: RTT_Nom, output-drive-strength, DLL-enable.
func (p *SdrammcAst2700V1SDRAMMC) ReadMR01() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteMR01 writes DDR4 Mode Register 0 and 1 (protected). [31:16]=MR1, [15:0]=MR0. MR0: CL, burst-type, burst-length, DLL-reset. MR1: RTT_Nom, output-drive-strength, DLL-enable.
func (p *SdrammcAst2700V1SDRAMMC) WriteMR01(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadMR23 reads DDR4 Mode Register 2 and 3 (protected). [31:16]=MR3, [15:0]=MR2. MR2: CWL, RTT_WR, write-levelling. MR3: MPR-read-format, per-DRAM-addressability.
func (p *SdrammcAst2700V1SDRAMMC) ReadMR23() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteMR23 writes DDR4 Mode Register 2 and 3 (protected). [31:16]=MR3, [15:0]=MR2. MR2: CWL, RTT_WR, write-levelling. MR3: MPR-read-format, per-DRAM-addressability.
func (p *SdrammcAst2700V1SDRAMMC) WriteMR23(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadMR45 reads DDR4 Mode Register 4 and 5 (protected). [31:16]=MR5, [15:0]=MR4. MR4: CAL, read-DBI, write-DBI, parity-error-status. MR5: RTT_Park, DM-disable, parity-latency.
func (p *SdrammcAst2700V1SDRAMMC) ReadMR45() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteMR45 writes DDR4 Mode Register 4 and 5 (protected). [31:16]=MR5, [15:0]=MR4. MR4: CAL, read-DBI, write-DBI, parity-error-status. MR5: RTT_Park, DM-disable, parity-latency.
func (p *SdrammcAst2700V1SDRAMMC) WriteMR45(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadMR67 reads DDR4 Mode Register 6 and 7 (protected). [31:16]=MR7 (vendor-specific), [15:0]=MR6. MR6: VrefDQ training range, VrefDQ training enable, tCCD_L.
func (p *SdrammcAst2700V1SDRAMMC) ReadMR67() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteMR67 writes DDR4 Mode Register 6 and 7 (protected). [31:16]=MR7 (vendor-specific), [15:0]=MR6. MR6: VrefDQ training range, VrefDQ training enable, tCCD_L.
func (p *SdrammcAst2700V1SDRAMMC) WriteMR67(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadREFRESHCTRL reads Refresh Control Register (protected). Controls automatic refresh interval and mode.
func (p *SdrammcAst2700V1SDRAMMC) ReadREFRESHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteREFRESHCTRL writes Refresh Control Register (protected). Controls automatic refresh interval and mode.
func (p *SdrammcAst2700V1SDRAMMC) WriteREFRESHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadREFRESHMGMT reads Refresh Management Register — DDR5 RAA (protected).
func (p *SdrammcAst2700V1SDRAMMC) ReadREFRESHMGMT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteREFRESHMGMT writes Refresh Management Register — DDR5 RAA (protected).
func (p *SdrammcAst2700V1SDRAMMC) WriteREFRESHMGMT(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadREFRESHSTS reads Refresh Status Register (read-only).
func (p *SdrammcAst2700V1SDRAMMC) ReadREFRESHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// ReadZQCTRL reads ZQ Calibration Control Register (protected).
func (p *SdrammcAst2700V1SDRAMMC) ReadZQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteZQCTRL writes ZQ Calibration Control Register (protected).
func (p *SdrammcAst2700V1SDRAMMC) WriteZQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadECCADDR reads ECC Protected Address Range Register (protected). Defines the address range covered by ECC.
func (p *SdrammcAst2700V1SDRAMMC) ReadECCADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteECCADDR writes ECC Protected Address Range Register (protected). Defines the address range covered by ECC.
func (p *SdrammcAst2700V1SDRAMMC) WriteECCADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadECCFAILSTS reads ECC Failure Status Register (read-only). [31:0]=failure type and location.
func (p *SdrammcAst2700V1SDRAMMC) ReadECCFAILSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// ReadECCFAILADDR reads ECC Failure Address Register (read-only). Address of the most recent ECC failure.
func (p *SdrammcAst2700V1SDRAMMC) ReadECCFAILADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// ReadARBCTRL reads Arbitration Control Register (protected). Controls the DRAM bus arbitration policy.
func (p *SdrammcAst2700V1SDRAMMC) ReadARBCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteARBCTRL writes Arbitration Control Register (protected). Controls the DRAM bus arbitration policy.
func (p *SdrammcAst2700V1SDRAMMC) WriteARBCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadMPULOCK reads MPU Region Lock Register. Bit n locks region n (prevents further configuration changes). Write 1 to lock; cannot be unlocked until next system reset. 16 bits used (one per region).
func (p *SdrammcAst2700V1SDRAMMC) ReadMPULOCK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteMPULOCK writes MPU Region Lock Register. Bit n locks region n (prevents further configuration changes). Write 1 to lock; cannot be unlocked until next system reset. 16 bits used (one per region).
func (p *SdrammcAst2700V1SDRAMMC) WriteMPULOCK(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadBISTCONF reads BIST Configuration Register (protected). Configure and start the built-in self-test.
func (p *SdrammcAst2700V1SDRAMMC) ReadBISTCONF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteBISTCONF writes BIST Configuration Register (protected). Configure and start the built-in self-test.
func (p *SdrammcAst2700V1SDRAMMC) WriteBISTCONF(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadBISTADDR reads BIST Start Address Register (protected). Physical DRAM address at which BIST begins.
func (p *SdrammcAst2700V1SDRAMMC) ReadBISTADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteBISTADDR writes BIST Start Address Register (protected). Physical DRAM address at which BIST begins.
func (p *SdrammcAst2700V1SDRAMMC) WriteBISTADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadBISTSIZE reads BIST Test Size Register (protected). Number of bytes to test.
func (p *SdrammcAst2700V1SDRAMMC) ReadBISTSIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteBISTSIZE writes BIST Test Size Register (protected). Number of bytes to test.
func (p *SdrammcAst2700V1SDRAMMC) WriteBISTSIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadBISTPATTERN reads BIST Data Pattern Register (protected). 32-bit pattern used when BIST_CONF.PATTERN_MODE = fixed.
func (p *SdrammcAst2700V1SDRAMMC) ReadBISTPATTERN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteBISTPATTERN writes BIST Data Pattern Register (protected). 32-bit pattern used when BIST_CONF.PATTERN_MODE = fixed.
func (p *SdrammcAst2700V1SDRAMMC) WriteBISTPATTERN(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadBISTRESULT reads BIST Result Register (read-only). Poll until DONE=1 after asserting BIST_CONF.START.
func (p *SdrammcAst2700V1SDRAMMC) ReadBISTRESULT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// ReadBISTFAILADDR reads BIST Failure Address (read-only). Physical address of the first BIST failure.
func (p *SdrammcAst2700V1SDRAMMC) ReadBISTFAILADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// ReadPHYIFSTS reads PHY Interface Status Register (read-only). DFI channel status and PHY-ready indicators.
func (p *SdrammcAst2700V1SDRAMMC) ReadPHYIFSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f8))
}

// ReadPORTCFG reads QoS port configuration register. [7:4] = urgent count threshold; [3] = urgent mode enable; [2] = QoS enable.  Set by sdramc_qos_init() to (1<<2)|(1<<3)|(8<<4).
// [n] (n < 5)
func (p *SdrammcAst2700V1SDRAMMC) ReadPORTCFG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200 + uint32(n)*128))
}

// WritePORTCFG writes QoS port configuration register. [7:4] = urgent count threshold; [3] = urgent mode enable; [2] = QoS enable.  Set by sdramc_qos_init() to (1<<2)|(1<<3)|(8<<4).
// [n] (n < 5)
func (p *SdrammcAst2700V1SDRAMMC) WritePORTCFG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0200+uint32(n)*128, uint32(val))
}

// ReadPORTREADQOS reads QoS port read priority register. Four 4-bit priority fields packed into 32 bits. Field n (bits [4n+3:4n]) sets the AXI QoS priority for read transaction class n.  Higher value = higher priority.
// [n] (n < 5)
func (p *SdrammcAst2700V1SDRAMMC) ReadPORTREADQOS(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0208 + uint32(n)*128))
}

// WritePORTREADQOS writes QoS port read priority register. Four 4-bit priority fields packed into 32 bits. Field n (bits [4n+3:4n]) sets the AXI QoS priority for read transaction class n.  Higher value = higher priority.
// [n] (n < 5)
func (p *SdrammcAst2700V1SDRAMMC) WritePORTREADQOS(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0208+uint32(n)*128, uint32(val))
}

// ReadPORTWRITEQOS reads QoS port write priority register. Same encoding as PORT_READ_QOS but for write transactions.
// [n] (n < 5)
func (p *SdrammcAst2700V1SDRAMMC) ReadPORTWRITEQOS(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0210 + uint32(n)*128))
}

// WritePORTWRITEQOS writes QoS port write priority register. Same encoding as PORT_READ_QOS but for write transactions.
// [n] (n < 5)
func (p *SdrammcAst2700V1SDRAMMC) WritePORTWRITEQOS(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0210+uint32(n)*128, uint32(val))
}

// ReadMPUCTRL reads MPU region control register. Bit 0 = enable.  Bits [7:4] = access permission matrix for CA35 (bit 4 = NS write, bit 5 = NS read, bit 6 = secure write, bit 7 = secure read).  Must write permissions before setting enable. Lock region after configuration via MPU_LOCK.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUCTRL(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0600 + uint32(n)*64))
}

// WriteMPUCTRL writes MPU region control register. Bit 0 = enable.  Bits [7:4] = access permission matrix for CA35 (bit 4 = NS write, bit 5 = NS read, bit 6 = secure write, bit 7 = secure read).  Must write permissions before setting enable. Lock region after configuration via MPU_LOCK.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUCTRL(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0600+uint32(n)*64, uint32(val))
}

// ReadMPUREGIONSTART reads MPU region start address (physical address >> 4, 4 KB granularity). Inclusive lower bound of the protected region. For DRAM-relative regions: value = (dram_offset) >> 4.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUREGIONSTART(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0608 + uint32(n)*64))
}

// WriteMPUREGIONSTART writes MPU region start address (physical address >> 4, 4 KB granularity). Inclusive lower bound of the protected region. For DRAM-relative regions: value = (dram_offset) >> 4.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUREGIONSTART(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0608+uint32(n)*64, uint32(val))
}

// ReadMPUREGIONEND reads MPU region end address (physical address >> 4, 4 KB granularity). Inclusive upper bound of the protected region.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUREGIONEND(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x060c + uint32(n)*64))
}

// WriteMPUREGIONEND writes MPU region end address (physical address >> 4, 4 KB granularity). Inclusive upper bound of the protected region.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUREGIONEND(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x060c+uint32(n)*64, uint32(val))
}

// ReadMPUWRMASTER0 reads Write master block mask — lower 32 masters. Bit n = 1 blocks write access from master ID n. Write 0xFFFFFFFF to block all lower masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUWRMASTER0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0610 + uint32(n)*64))
}

// WriteMPUWRMASTER0 writes Write master block mask — lower 32 masters. Bit n = 1 blocks write access from master ID n. Write 0xFFFFFFFF to block all lower masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUWRMASTER0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0610+uint32(n)*64, uint32(val))
}

// ReadMPUWRMASTER1 reads Write master block mask — upper masters. Bit 19 = SLIM (SLI MBUS); leave 0 to allow BootMCU DRAM access.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUWRMASTER1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0614 + uint32(n)*64))
}

// WriteMPUWRMASTER1 writes Write master block mask — upper masters. Bit 19 = SLIM (SLI MBUS); leave 0 to allow BootMCU DRAM access.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUWRMASTER1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0614+uint32(n)*64, uint32(val))
}

// ReadMPURDMASTER0 reads Read master block mask — lower 32 masters. Bit n = 1 blocks read access from master ID n.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPURDMASTER0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0618 + uint32(n)*64))
}

// WriteMPURDMASTER0 writes Read master block mask — lower 32 masters. Bit n = 1 blocks read access from master ID n.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPURDMASTER0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0618+uint32(n)*64, uint32(val))
}

// ReadMPURDMASTER1 reads Read master block mask — upper masters. Bit 19 = SLIM (SLI MBUS); leave 0 to allow BootMCU DRAM reads.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPURDMASTER1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x061c + uint32(n)*64))
}

// WriteMPURDMASTER1 writes Read master block mask — upper masters. Bit 19 = SLIM (SLI MBUS); leave 0 to allow BootMCU DRAM reads.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPURDMASTER1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x061c+uint32(n)*64, uint32(val))
}

// ReadMPUWRSECURE0 reads Secure write override mask — lower 32 masters. Bit n = 1 forces secure-write permission for master n (overrides the AXI AxPROT secure bit). Set to 0 to rely on AXI transaction attributes.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUWRSECURE0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0620 + uint32(n)*64))
}

// WriteMPUWRSECURE0 writes Secure write override mask — lower 32 masters. Bit n = 1 forces secure-write permission for master n (overrides the AXI AxPROT secure bit). Set to 0 to rely on AXI transaction attributes.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUWRSECURE0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0620+uint32(n)*64, uint32(val))
}

// ReadMPUWRSECURE1 reads Secure write override mask — upper masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPUWRSECURE1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0624 + uint32(n)*64))
}

// WriteMPUWRSECURE1 writes Secure write override mask — upper masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPUWRSECURE1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0624+uint32(n)*64, uint32(val))
}

// ReadMPURDSECURE0 reads Secure read override mask — lower 32 masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPURDSECURE0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0628 + uint32(n)*64))
}

// WriteMPURDSECURE0 writes Secure read override mask — lower 32 masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPURDSECURE0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0628+uint32(n)*64, uint32(val))
}

// ReadMPURDSECURE1 reads Secure read override mask — upper masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) ReadMPURDSECURE1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x062c + uint32(n)*64))
}

// WriteMPURDSECURE1 writes Secure read override mask — upper masters.
// [n] (n < 16)
func (p *SdrammcAst2700V1SDRAMMC) WriteMPURDSECURE1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x062c+uint32(n)*64, uint32(val))
}

