// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// UfsAst2700V1UFS AST2700 UFS controller at 0x12C08000.
type UfsAst2700V1UFS struct {
    Base uintptr
}

// ReadMPHYSWRST reads MPHY software reset register.
func (p *UfsAst2700V1UFS) ReadMPHYSWRST() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteMPHYSWRST writes MPHY software reset register.
func (p *UfsAst2700V1UFS) WriteMPHYSWRST(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadMPHYSPECIALDEBUG reads MPHY_SPECIAL_DEBUG
func (p *UfsAst2700V1UFS) ReadMPHYSPECIALDEBUG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteMPHYSPECIALDEBUG writes MPHY_SPECIAL_DEBUG
func (p *UfsAst2700V1UFS) WriteMPHYSPECIALDEBUG(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadMPHYSFWATCHDOG reads MPHY_SF_WATCHDOG
func (p *UfsAst2700V1UFS) ReadMPHYSFWATCHDOG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteMPHYSFWATCHDOG writes MPHY_SF_WATCHDOG
func (p *UfsAst2700V1UFS) WriteMPHYSFWATCHDOG(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadMPHYSFERRORFLAG reads MPHY_SF_ERROR_FLAG
func (p *UfsAst2700V1UFS) ReadMPHYSFERRORFLAG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteMPHYSFERRORFLAG writes MPHY_SF_ERROR_FLAG
func (p *UfsAst2700V1UFS) WriteMPHYSFERRORFLAG(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMPHYDEBUGSEL reads MPHY_DEBUG_SEL
func (p *UfsAst2700V1UFS) ReadMPHYDEBUGSEL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMPHYDEBUGSEL writes MPHY_DEBUG_SEL
func (p *UfsAst2700V1UFS) WriteMPHYDEBUGSEL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadMPHYDEBUGOUT reads MPHY_DEBUG_OUT
func (p *UfsAst2700V1UFS) ReadMPHYDEBUGOUT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteMPHYDEBUGOUT writes MPHY_DEBUG_OUT
func (p *UfsAst2700V1UFS) WriteMPHYDEBUGOUT(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadMPHYCTL reads MPHY_CTL
func (p *UfsAst2700V1UFS) ReadMPHYCTL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteMPHYCTL writes MPHY_CTL
func (p *UfsAst2700V1UFS) WriteMPHYCTL(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadMPHYRELEASE reads MPHY_RELEASE
func (p *UfsAst2700V1UFS) ReadMPHYRELEASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteMPHYRELEASE writes MPHY_RELEASE
func (p *UfsAst2700V1UFS) WriteMPHYRELEASE(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadMPHYXCFGD reads MPHY_XCFGD[n] (n < 5)
func (p *UfsAst2700V1UFS) ReadMPHYXCFGD(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020 + uint32(n)*4))
}

// WriteMPHYXCFGD writes MPHY_XCFGD[n] (n < 5)
func (p *UfsAst2700V1UFS) WriteMPHYXCFGD(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0020+uint32(n)*4, uint32(val))
}

// ReadMPHYXCFGA reads MPHY_XCFGA[n] (n < 13)
func (p *UfsAst2700V1UFS) ReadMPHYXCFGA(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034 + uint32(n)*4))
}

// WriteMPHYXCFGA writes MPHY_XCFGA[n] (n < 13)
func (p *UfsAst2700V1UFS) WriteMPHYXCFGA(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0034+uint32(n)*4, uint32(val))
}

// ReadMPHYXCFGO reads MPHY_XCFGO[n] (n < 9)
func (p *UfsAst2700V1UFS) ReadMPHYXCFGO(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068 + uint32(n)*4))
}

// ReadMPHYCALIIN0 reads MPHY_CALI_IN0
func (p *UfsAst2700V1UFS) ReadMPHYCALIIN0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteMPHYCALIIN0 writes MPHY_CALI_IN0
func (p *UfsAst2700V1UFS) WriteMPHYCALIIN0(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadMPHYCALIIN1 reads MPHY_CALI_IN1
func (p *UfsAst2700V1UFS) ReadMPHYCALIIN1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteMPHYCALIIN1 writes MPHY_CALI_IN1
func (p *UfsAst2700V1UFS) WriteMPHYCALIIN1(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadMPHYCALIOUT reads MPHY_CALI_OUT
func (p *UfsAst2700V1UFS) ReadMPHYCALIOUT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// ReadMPHYVCONTROL reads MPHY_VCONTROL
func (p *UfsAst2700V1UFS) ReadMPHYVCONTROL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteMPHYVCONTROL writes MPHY_VCONTROL
func (p *UfsAst2700V1UFS) WriteMPHYVCONTROL(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadMPHYBISTOK reads MPHY_BIST_OK
func (p *UfsAst2700V1UFS) ReadMPHYBISTOK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// ReadHCCTL reads HC_CTL
func (p *UfsAst2700V1UFS) ReadHCCTL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteHCCTL writes HC_CTL
func (p *UfsAst2700V1UFS) WriteHCCTL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadHCST reads HC_ST
func (p *UfsAst2700V1UFS) ReadHCST() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// ReadCAP reads CAP
func (p *UfsAst2700V1UFS) ReadCAP() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// ReadUMACAP reads UMACAP
func (p *UfsAst2700V1UFS) ReadUMACAP() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// ReadVER reads VER
func (p *UfsAst2700V1UFS) ReadVER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0208))
}

// ReadHCPID reads HCPID
func (p *UfsAst2700V1UFS) ReadHCPID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0210))
}

// ReadHCMID reads HCMID
func (p *UfsAst2700V1UFS) ReadHCMID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0214))
}

// ReadAHIT reads Auto-hibernate idle timer configuration.
func (p *UfsAst2700V1UFS) ReadAHIT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0218))
}

// WriteAHIT writes Auto-hibernate idle timer configuration.
func (p *UfsAst2700V1UFS) WriteAHIT(val uint32) {
    reg.Write(uint32(p.Base)+0x0218, uint32(val))
}

// ReadIS reads IS
func (p *UfsAst2700V1UFS) ReadIS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0220))
}

// WriteIS writes IS
func (p *UfsAst2700V1UFS) WriteIS(val uint32) {
    reg.Write(uint32(p.Base)+0x0220, uint32(val))
}

// ReadIE reads IE
func (p *UfsAst2700V1UFS) ReadIE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0224))
}

// WriteIE writes IE
func (p *UfsAst2700V1UFS) WriteIE(val uint32) {
    reg.Write(uint32(p.Base)+0x0224, uint32(val))
}

// ReadHCS reads HCS
func (p *UfsAst2700V1UFS) ReadHCS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0230))
}

// ReadHCE reads Host controller enable register.
func (p *UfsAst2700V1UFS) ReadHCE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0234))
}

// WriteHCE writes Host controller enable register.
func (p *UfsAst2700V1UFS) WriteHCE(val uint32) {
    reg.Write(uint32(p.Base)+0x0234, uint32(val))
}

// ReadUICERROR reads UIC error code registers UECPA, UECDL, UECN, UECT, UECDME.[n] (n < 5)
func (p *UfsAst2700V1UFS) ReadUICERROR(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0238 + uint32(n)*4))
}

// ReadUTRIACR reads UTRIACR
func (p *UfsAst2700V1UFS) ReadUTRIACR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x024c))
}

// WriteUTRIACR writes UTRIACR
func (p *UfsAst2700V1UFS) WriteUTRIACR(val uint32) {
    reg.Write(uint32(p.Base)+0x024c, uint32(val))
}

// ReadUTRLBA reads UTRLBA
func (p *UfsAst2700V1UFS) ReadUTRLBA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0250))
}

// WriteUTRLBA writes UTRLBA
func (p *UfsAst2700V1UFS) WriteUTRLBA(val uint32) {
    reg.Write(uint32(p.Base)+0x0250, uint32(val))
}

// ReadUTRLBAU reads UTRLBAU
func (p *UfsAst2700V1UFS) ReadUTRLBAU() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0254))
}

// WriteUTRLBAU writes UTRLBAU
func (p *UfsAst2700V1UFS) WriteUTRLBAU(val uint32) {
    reg.Write(uint32(p.Base)+0x0254, uint32(val))
}

// ReadUTRLDBR reads UTRLDBR
func (p *UfsAst2700V1UFS) ReadUTRLDBR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0258))
}

// WriteUTRLDBR writes UTRLDBR
func (p *UfsAst2700V1UFS) WriteUTRLDBR(val uint32) {
    reg.Write(uint32(p.Base)+0x0258, uint32(val))
}

// ReadUTRLCLR reads UTRLCLR
func (p *UfsAst2700V1UFS) ReadUTRLCLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x025c))
}

// WriteUTRLCLR writes UTRLCLR
func (p *UfsAst2700V1UFS) WriteUTRLCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x025c, uint32(val))
}

// ReadUTRLRSR reads UTRLRSR
func (p *UfsAst2700V1UFS) ReadUTRLRSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0260))
}

// WriteUTRLRSR writes UTRLRSR
func (p *UfsAst2700V1UFS) WriteUTRLRSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0260, uint32(val))
}

// ReadUTRLCNR reads UTRLCNR
func (p *UfsAst2700V1UFS) ReadUTRLCNR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0264))
}

// WriteUTRLCNR writes UTRLCNR
func (p *UfsAst2700V1UFS) WriteUTRLCNR(val uint32) {
    reg.Write(uint32(p.Base)+0x0264, uint32(val))
}

// ReadUTMRLBA reads UTMRLBA
func (p *UfsAst2700V1UFS) ReadUTMRLBA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0270))
}

// WriteUTMRLBA writes UTMRLBA
func (p *UfsAst2700V1UFS) WriteUTMRLBA(val uint32) {
    reg.Write(uint32(p.Base)+0x0270, uint32(val))
}

// ReadUTMRLBAU reads UTMRLBAU
func (p *UfsAst2700V1UFS) ReadUTMRLBAU() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0274))
}

// WriteUTMRLBAU writes UTMRLBAU
func (p *UfsAst2700V1UFS) WriteUTMRLBAU(val uint32) {
    reg.Write(uint32(p.Base)+0x0274, uint32(val))
}

// ReadUTMRLDBR reads UTMRLDBR
func (p *UfsAst2700V1UFS) ReadUTMRLDBR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0278))
}

// WriteUTMRLDBR writes UTMRLDBR
func (p *UfsAst2700V1UFS) WriteUTMRLDBR(val uint32) {
    reg.Write(uint32(p.Base)+0x0278, uint32(val))
}

// ReadUTMRLCLR reads UTMRLCLR
func (p *UfsAst2700V1UFS) ReadUTMRLCLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x027c))
}

// WriteUTMRLCLR writes UTMRLCLR
func (p *UfsAst2700V1UFS) WriteUTMRLCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x027c, uint32(val))
}

// ReadUTMRLRSR reads UTMRLRSR
func (p *UfsAst2700V1UFS) ReadUTMRLRSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0280))
}

// WriteUTMRLRSR writes UTMRLRSR
func (p *UfsAst2700V1UFS) WriteUTMRLRSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0280, uint32(val))
}

// ReadUICCMD reads UICCMD
func (p *UfsAst2700V1UFS) ReadUICCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0290))
}

// WriteUICCMD writes UICCMD
func (p *UfsAst2700V1UFS) WriteUICCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0290, uint32(val))
}

// ReadUICCMDARG reads UICCMDARG[n] (n < 3)
func (p *UfsAst2700V1UFS) ReadUICCMDARG(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0294 + uint32(n)*4))
}

// WriteUICCMDARG writes UICCMDARG[n] (n < 3)
func (p *UfsAst2700V1UFS) WriteUICCMDARG(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0294+uint32(n)*4, uint32(val))
}

// ReadUMABA reads UMABA
func (p *UfsAst2700V1UFS) ReadUMABA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02b0))
}

// WriteUMABA writes UMABA
func (p *UfsAst2700V1UFS) WriteUMABA(val uint32) {
    reg.Write(uint32(p.Base)+0x02b0, uint32(val))
}

// ReadUMABAU reads UMABAU
func (p *UfsAst2700V1UFS) ReadUMABAU() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02b4))
}

// WriteUMABAU writes UMABAU
func (p *UfsAst2700V1UFS) WriteUMABAU(val uint32) {
    reg.Write(uint32(p.Base)+0x02b4, uint32(val))
}

// ReadUMAOMAX reads UMAOMAX
func (p *UfsAst2700V1UFS) ReadUMAOMAX() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02b8))
}

// WriteUMAOMAX writes UMAOMAX
func (p *UfsAst2700V1UFS) WriteUMAOMAX(val uint32) {
    reg.Write(uint32(p.Base)+0x02b8, uint32(val))
}

// ReadUMACONF reads UMACONF
func (p *UfsAst2700V1UFS) ReadUMACONF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02bc))
}

// WriteUMACONF writes UMACONF
func (p *UfsAst2700V1UFS) WriteUMACONF(val uint32) {
    reg.Write(uint32(p.Base)+0x02bc, uint32(val))
}

// ReadBUSTHRTL reads BUSTHRTL
func (p *UfsAst2700V1UFS) ReadBUSTHRTL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02c0))
}

// WriteBUSTHRTL writes BUSTHRTL
func (p *UfsAst2700V1UFS) WriteBUSTHRTL(val uint32) {
    reg.Write(uint32(p.Base)+0x02c0, uint32(val))
}

// ReadCDACFG reads CDACFG
func (p *UfsAst2700V1UFS) ReadCDACFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02d0))
}

// WriteCDACFG writes CDACFG
func (p *UfsAst2700V1UFS) WriteCDACFG(val uint32) {
    reg.Write(uint32(p.Base)+0x02d0, uint32(val))
}

// ReadCDATX reads CDATX[n] (n < 2)
func (p *UfsAst2700V1UFS) ReadCDATX(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02d4 + uint32(n)*4))
}

// WriteCDATX writes CDATX[n] (n < 2)
func (p *UfsAst2700V1UFS) WriteCDATX(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x02d4+uint32(n)*4, uint32(val))
}

// ReadCDARX reads CDARX[n] (n < 2)
func (p *UfsAst2700V1UFS) ReadCDARX(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02dc + uint32(n)*4))
}

// ReadCDASTA reads CDASTA
func (p *UfsAst2700V1UFS) ReadCDASTA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02e4))
}

// ReadLBMCFG reads LBMCFG
func (p *UfsAst2700V1UFS) ReadLBMCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02f0))
}

// WriteLBMCFG writes LBMCFG
func (p *UfsAst2700V1UFS) WriteLBMCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x02f0, uint32(val))
}

// ReadLBMSTA reads LBMSTA
func (p *UfsAst2700V1UFS) ReadLBMSTA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02f4))
}

// WriteLBMSTA writes LBMSTA
func (p *UfsAst2700V1UFS) WriteLBMSTA(val uint32) {
    reg.Write(uint32(p.Base)+0x02f4, uint32(val))
}

// ReadHCLKDIV reads UFS host clock divider; HCLK frequency in MHz.
func (p *UfsAst2700V1UFS) ReadHCLKDIV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02fc))
}

// WriteHCLKDIV writes UFS host clock divider; HCLK frequency in MHz.
func (p *UfsAst2700V1UFS) WriteHCLKDIV(val uint32) {
    reg.Write(uint32(p.Base)+0x02fc, uint32(val))
}

