// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// UsbVhubAst2700V1VHUBDEV AST2700 vHub per-downstream-device registers. One instance per virtual downstream port, located at controller_base + 0x100 + 0x10*index. Each describes an independent gadget behind the emulated hub: its enable/port state, USB address, EP0 control-transfer state, and EP0 data buffer.
type UsbVhubAst2700V1VHUBDEV struct {
    Base uintptr
}

// ReadENCTRL reads Device enable control — port enable, high-speed select, USB address, EP0 IRQ enables.
func (p *UsbVhubAst2700V1VHUBDEV) ReadENCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteENCTRL writes Device enable control — port enable, high-speed select, USB address, EP0 IRQ enables.
func (p *UsbVhubAst2700V1VHUBDEV) WriteENCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadISR reads Device EP0 interrupt status (setup / IN / OUT ACK-stall / NAK).
func (p *UsbVhubAst2700V1VHUBDEV) ReadISR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteISR writes Device EP0 interrupt status (setup / IN / OUT ACK-stall / NAK).
func (p *UsbVhubAst2700V1VHUBDEV) WriteISR(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadEP0CTRL reads Device EP0 control/status (same bit layout as the hub EP0_CTRL).
func (p *UsbVhubAst2700V1VHUBDEV) ReadEP0CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteEP0CTRL writes Device EP0 control/status (same bit layout as the hub EP0_CTRL).
func (p *UsbVhubAst2700V1VHUBDEV) WriteEP0CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadEP0DATA reads Base DMA address of this device's EP0 64-byte data buffer.
func (p *UsbVhubAst2700V1VHUBDEV) ReadEP0DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteEP0DATA writes Base DMA address of this device's EP0 64-byte data buffer.
func (p *UsbVhubAst2700V1VHUBDEV) WriteEP0DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

