// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// UsbVhubAst2700V1VHUBEP AST2700 vHub per-generic-endpoint registers. Up to 21 generic endpoints are shared across all downstream devices; each is assigned to a device + EP number via CONFIG. Located at controller_base + 0x200 + 0x10*g_index. Supports single-stage DMA (typically OUT) and 256/32-entry descriptor-ring DMA (IN).
type UsbVhubAst2700V1VHUBEP struct {
    Base uintptr
}

// ReadCONFIG reads Endpoint config — enable, direction, type, EP number, owning device, max packet.
func (p *UsbVhubAst2700V1VHUBEP) ReadCONFIG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCONFIG writes Endpoint config — enable, direction, type, EP number, owning device, max packet.
func (p *UsbVhubAst2700V1VHUBEP) WriteCONFIG(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadDMACTLSTAT reads Endpoint DMA control/status — mode select, reset, long/contiguous mode, engine status.
func (p *UsbVhubAst2700V1VHUBEP) ReadDMACTLSTAT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteDMACTLSTAT writes Endpoint DMA control/status — mode select, reset, long/contiguous mode, engine status.
func (p *UsbVhubAst2700V1VHUBEP) WriteDMACTLSTAT(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadDESCBASE reads Endpoint DMA base address. In descriptor mode: base of the descriptor ring. In single-stage mode: the data buffer DMA address.
func (p *UsbVhubAst2700V1VHUBEP) ReadDESCBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteDESCBASE writes Endpoint DMA base address. In descriptor mode: base of the descriptor ring. In single-stage mode: the data buffer DMA address.
func (p *UsbVhubAst2700V1VHUBEP) WriteDESCBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadDESCSTATUS reads Endpoint DMA status — single-stage TX size/kick and descriptor read/write pointers.
func (p *UsbVhubAst2700V1VHUBEP) ReadDESCSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteDESCSTATUS writes Endpoint DMA status — single-stage TX size/kick and descriptor read/write pointers.
func (p *UsbVhubAst2700V1VHUBEP) WriteDESCSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

