// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// VgaAst2700V1VGALINK AST2700 VGA link packer/retimer block used to connect CPU-die and IO-die display paths.
type VgaAst2700V1VGALINK struct {
    Base uintptr
}

// ReadVERSION reads VGA link block version register.
func (p *VgaAst2700V1VGALINK) ReadVERSION() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteVERSION writes VGA link block version register.
func (p *VgaAst2700V1VGALINK) WriteVERSION(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadSCRATCH0 reads VGA link scratch register 0.
func (p *VgaAst2700V1VGALINK) ReadSCRATCH0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteSCRATCH0 writes VGA link scratch register 0.
func (p *VgaAst2700V1VGALINK) WriteSCRATCH0(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCHECKSUM reads VGA link checksum container.
func (p *VgaAst2700V1VGALINK) ReadCHECKSUM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCHECKSUM writes VGA link checksum container.
func (p *VgaAst2700V1VGALINK) WriteCHECKSUM(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadSCRATCH1 reads VGA link scratch register 1.
func (p *VgaAst2700V1VGALINK) ReadSCRATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteSCRATCH1 writes VGA link scratch register 1.
func (p *VgaAst2700V1VGALINK) WriteSCRATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCTRL1 reads VGA link control register 1.
func (p *VgaAst2700V1VGALINK) ReadCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCTRL1 writes VGA link control register 1.
func (p *VgaAst2700V1VGALINK) WriteCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCTRL2 reads VGA link FIFO threshold control register.
func (p *VgaAst2700V1VGALINK) ReadCTRL2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCTRL2 writes VGA link FIFO threshold control register.
func (p *VgaAst2700V1VGALINK) WriteCTRL2(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadENCSTATUS reads Encoder-side status register.
func (p *VgaAst2700V1VGALINK) ReadENCSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteENCSTATUS writes Encoder-side status register.
func (p *VgaAst2700V1VGALINK) WriteENCSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadENCCFG reads Encoder-side configuration register.
func (p *VgaAst2700V1VGALINK) ReadENCCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteENCCFG writes Encoder-side configuration register.
func (p *VgaAst2700V1VGALINK) WriteENCCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadINTRSTATUS reads Interrupt status register.
func (p *VgaAst2700V1VGALINK) ReadINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteINTRSTATUS writes Interrupt status register.
func (p *VgaAst2700V1VGALINK) WriteINTRSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadINTRSTATUSEN reads Interrupt status-enable register.
func (p *VgaAst2700V1VGALINK) ReadINTRSTATUSEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteINTRSTATUSEN writes Interrupt status-enable register.
func (p *VgaAst2700V1VGALINK) WriteINTRSTATUSEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadINTRSIGNALEN reads Interrupt signal-enable register.
func (p *VgaAst2700V1VGALINK) ReadINTRSIGNALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteINTRSIGNALEN writes Interrupt signal-enable register.
func (p *VgaAst2700V1VGALINK) WriteINTRSIGNALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadINTRFORCE reads Interrupt force register.
func (p *VgaAst2700V1VGALINK) ReadINTRFORCE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteINTRFORCE writes Interrupt force register.
func (p *VgaAst2700V1VGALINK) WriteINTRFORCE(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadHTIMING0 reads Horizontal total and sync-end timing.
func (p *VgaAst2700V1VGALINK) ReadHTIMING0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteHTIMING0 writes Horizontal total and sync-end timing.
func (p *VgaAst2700V1VGALINK) WriteHTIMING0(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadHTIMING1 reads Horizontal back-porch end and display-end timing.
func (p *VgaAst2700V1VGALINK) ReadHTIMING1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteHTIMING1 writes Horizontal back-porch end and display-end timing.
func (p *VgaAst2700V1VGALINK) WriteHTIMING1(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadVTIMING0 reads Vertical total and sync-end timing.
func (p *VgaAst2700V1VGALINK) ReadVTIMING0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteVTIMING0 writes Vertical total and sync-end timing.
func (p *VgaAst2700V1VGALINK) WriteVTIMING0(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadVTIMING1 reads Vertical back-porch end and display-end timing.
func (p *VgaAst2700V1VGALINK) ReadVTIMING1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteVTIMING1 writes Vertical back-porch end and display-end timing.
func (p *VgaAst2700V1VGALINK) WriteVTIMING1(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadPATGEN reads Pattern-generator control register.
func (p *VgaAst2700V1VGALINK) ReadPATGEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WritePATGEN writes Pattern-generator control register.
func (p *VgaAst2700V1VGALINK) WritePATGEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadWAITFRAME reads Wait-frame configuration and hold register.
func (p *VgaAst2700V1VGALINK) ReadWAITFRAME() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteWAITFRAME writes Wait-frame configuration and hold register.
func (p *VgaAst2700V1VGALINK) WriteWAITFRAME(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadCOLORBARSWITCHHPOINT reads Color-bar switch horizontal point.
func (p *VgaAst2700V1VGALINK) ReadCOLORBARSWITCHHPOINT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteCOLORBARSWITCHHPOINT writes Color-bar switch horizontal point.
func (p *VgaAst2700V1VGALINK) WriteCOLORBARSWITCHHPOINT(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadFRAMESTARTCFG reads Frame-start configuration register.
func (p *VgaAst2700V1VGALINK) ReadFRAMESTARTCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteFRAMESTARTCFG writes Frame-start configuration register.
func (p *VgaAst2700V1VGALINK) WriteFRAMESTARTCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadSRCOVERWRITE reads Source overwrite selection and enable control.
func (p *VgaAst2700V1VGALINK) ReadSRCOVERWRITE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteSRCOVERWRITE writes Source overwrite selection and enable control.
func (p *VgaAst2700V1VGALINK) WriteSRCOVERWRITE(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadSCRATCH2 reads VGA link scratch register 2.
func (p *VgaAst2700V1VGALINK) ReadSCRATCH2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteSCRATCH2 writes VGA link scratch register 2.
func (p *VgaAst2700V1VGALINK) WriteSCRATCH2(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadDECSTATUS reads Decoder-side status register.
func (p *VgaAst2700V1VGALINK) ReadDECSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteDECSTATUS writes Decoder-side status register.
func (p *VgaAst2700V1VGALINK) WriteDECSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadDECCFG reads Decoder-side configuration register.
func (p *VgaAst2700V1VGALINK) ReadDECCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteDECCFG writes Decoder-side configuration register.
func (p *VgaAst2700V1VGALINK) WriteDECCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadSYNCRESET reads Sync reset write-through register.
func (p *VgaAst2700V1VGALINK) ReadSYNCRESET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteSYNCRESET writes Sync reset write-through register.
func (p *VgaAst2700V1VGALINK) WriteSYNCRESET(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadLOWPOWERCTRL reads Low-power control register.
func (p *VgaAst2700V1VGALINK) ReadLOWPOWERCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteLOWPOWERCTRL writes Low-power control register.
func (p *VgaAst2700V1VGALINK) WriteLOWPOWERCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadVPLLCFG reads IO-die VPLL configuration register.
func (p *VgaAst2700V1VGALINK) ReadVPLLCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteVPLLCFG writes IO-die VPLL configuration register.
func (p *VgaAst2700V1VGALINK) WriteVPLLCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadVPLLBJ reads IO-die VPLL BJ configuration register.
func (p *VgaAst2700V1VGALINK) ReadVPLLBJ() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteVPLLBJ writes IO-die VPLL BJ configuration register.
func (p *VgaAst2700V1VGALINK) WriteVPLLBJ(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadDEBUG reads Debug register.
func (p *VgaAst2700V1VGALINK) ReadDEBUG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteDEBUG writes Debug register.
func (p *VgaAst2700V1VGALINK) WriteDEBUG(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadDUMMY reads Dummy register.
func (p *VgaAst2700V1VGALINK) ReadDUMMY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteDUMMY writes Dummy register.
func (p *VgaAst2700V1VGALINK) WriteDUMMY(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadMONITOR reads Monitor register.
func (p *VgaAst2700V1VGALINK) ReadMONITOR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteMONITOR writes Monitor register.
func (p *VgaAst2700V1VGALINK) WriteMONITOR(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadMONITORMUX reads Monitor mux register.
func (p *VgaAst2700V1VGALINK) ReadMONITORMUX() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteMONITORMUX writes Monitor mux register.
func (p *VgaAst2700V1VGALINK) WriteMONITORMUX(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

