// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// VideoAst2700V1VIDEO AST2700 video capture/compression engine register block.
type VideoAst2700V1VIDEO struct {
    Base uintptr
}

// ReadPROTECTIONKEY reads Write 0x1a038aa8 to unlock protected registers.
func (p *VideoAst2700V1VIDEO) ReadPROTECTIONKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WritePROTECTIONKEY writes Write 0x1a038aa8 to unlock protected registers.
func (p *VideoAst2700V1VIDEO) WritePROTECTIONKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadSEQCTRL reads SEQ_CTRL
func (p *VideoAst2700V1VIDEO) ReadSEQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteSEQCTRL writes SEQ_CTRL
func (p *VideoAst2700V1VIDEO) WriteSEQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCTRL reads CTRL
func (p *VideoAst2700V1VIDEO) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCTRL writes CTRL
func (p *VideoAst2700V1VIDEO) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadTGS0 reads Timing generation horizontal/direct-fetch base setting.
func (p *VideoAst2700V1VIDEO) ReadTGS0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteTGS0 writes Timing generation horizontal/direct-fetch base setting.
func (p *VideoAst2700V1VIDEO) WriteTGS0(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadTGS1 reads Timing generation vertical/direct-fetch offset setting.
func (p *VideoAst2700V1VIDEO) ReadTGS1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteTGS1 writes Timing generation vertical/direct-fetch offset setting.
func (p *VideoAst2700V1VIDEO) WriteTGS1(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadSCALINGFACTOR reads SCALING_FACTOR
func (p *VideoAst2700V1VIDEO) ReadSCALINGFACTOR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteSCALINGFACTOR writes SCALING_FACTOR
func (p *VideoAst2700V1VIDEO) WriteSCALINGFACTOR(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadSCALINGFILTER reads Scaling filter parameter registers 0..3.[n] (n < 4)
func (p *VideoAst2700V1VIDEO) ReadSCALINGFILTER(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018 + uint32(n)*4))
}

// WriteSCALINGFILTER writes Scaling filter parameter registers 0..3.[n] (n < 4)
func (p *VideoAst2700V1VIDEO) WriteSCALINGFILTER(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0018+uint32(n)*4, uint32(val))
}

// ReadBCDCTRL reads BCD_CTRL
func (p *VideoAst2700V1VIDEO) ReadBCDCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteBCDCTRL writes BCD_CTRL
func (p *VideoAst2700V1VIDEO) WriteBCDCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadCAPWINDOW reads CAP_WINDOW
func (p *VideoAst2700V1VIDEO) ReadCAPWINDOW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCAPWINDOW writes CAP_WINDOW
func (p *VideoAst2700V1VIDEO) WriteCAPWINDOW(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadCOMPWINDOW reads COMP_WINDOW
func (p *VideoAst2700V1VIDEO) ReadCOMPWINDOW() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteCOMPWINDOW writes COMP_WINDOW
func (p *VideoAst2700V1VIDEO) WriteCOMPWINDOW(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadCOMPPROCOFFSET reads COMP_PROC_OFFSET
func (p *VideoAst2700V1VIDEO) ReadCOMPPROCOFFSET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteCOMPPROCOFFSET writes COMP_PROC_OFFSET
func (p *VideoAst2700V1VIDEO) WriteCOMPPROCOFFSET(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadCOMPOFFSET reads COMP_OFFSET
func (p *VideoAst2700V1VIDEO) ReadCOMPOFFSET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteCOMPOFFSET writes COMP_OFFSET
func (p *VideoAst2700V1VIDEO) WriteCOMPOFFSET(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadJPEGADDR reads JPEG_ADDR
func (p *VideoAst2700V1VIDEO) ReadJPEGADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteJPEGADDR writes JPEG_ADDR
func (p *VideoAst2700V1VIDEO) WriteJPEGADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadSRC0ADDR reads SRC0_ADDR
func (p *VideoAst2700V1VIDEO) ReadSRC0ADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteSRC0ADDR writes SRC0_ADDR
func (p *VideoAst2700V1VIDEO) WriteSRC0ADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadSRCSCANLINEOFFSET reads SRC_SCANLINE_OFFSET
func (p *VideoAst2700V1VIDEO) ReadSRCSCANLINEOFFSET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteSRCSCANLINEOFFSET writes SRC_SCANLINE_OFFSET
func (p *VideoAst2700V1VIDEO) WriteSRCSCANLINEOFFSET(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadSRC1ADDR reads SRC1_ADDR
func (p *VideoAst2700V1VIDEO) ReadSRC1ADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteSRC1ADDR writes SRC1_ADDR
func (p *VideoAst2700V1VIDEO) WriteSRC1ADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadBCDADDR reads BCD_ADDR
func (p *VideoAst2700V1VIDEO) ReadBCDADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteBCDADDR writes BCD_ADDR
func (p *VideoAst2700V1VIDEO) WriteBCDADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadCOMPADDR reads COMP_ADDR
func (p *VideoAst2700V1VIDEO) ReadCOMPADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteCOMPADDR writes COMP_ADDR
func (p *VideoAst2700V1VIDEO) WriteCOMPADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadSTREAMBUFSIZE reads STREAM_BUF_SIZE
func (p *VideoAst2700V1VIDEO) ReadSTREAMBUFSIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteSTREAMBUFSIZE writes STREAM_BUF_SIZE
func (p *VideoAst2700V1VIDEO) WriteSTREAMBUFSIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadCOMPWRITEOFFSETREADBACK reads COMP_WRITE_OFFSET_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadCOMPWRITEOFFSETREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// ReadCOMPCTRL reads COMP_CTRL
func (p *VideoAst2700V1VIDEO) ReadCOMPCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteCOMPCTRL writes COMP_CTRL
func (p *VideoAst2700V1VIDEO) WriteCOMPCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadJPEGEFFECTIVEBITCTRL reads JPEG_EFFECTIVE_BIT_CTRL
func (p *VideoAst2700V1VIDEO) ReadJPEGEFFECTIVEBITCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteJPEGEFFECTIVEBITCTRL writes JPEG_EFFECTIVE_BIT_CTRL
func (p *VideoAst2700V1VIDEO) WriteJPEGEFFECTIVEBITCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadQUANTIZATIONVALUE reads QUANTIZATION_VALUE
func (p *VideoAst2700V1VIDEO) ReadQUANTIZATIONVALUE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteQUANTIZATIONVALUE writes QUANTIZATION_VALUE
func (p *VideoAst2700V1VIDEO) WriteQUANTIZATIONVALUE(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadCBADDR reads CB_ADDR
func (p *VideoAst2700V1VIDEO) ReadCBADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteCBADDR writes CB_ADDR
func (p *VideoAst2700V1VIDEO) WriteCBADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadCOMPTOTALSIZEREADBACK reads COMP_TOTAL_SIZE_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadCOMPTOTALSIZEREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// ReadCOMPBLOCKCOUNTREADBACK reads COMP_BLOCK_COUNT_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadCOMPBLOCKCOUNTREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// ReadFRAMEENDOFFSETREADBACK reads FRAME_END_OFFSET_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadFRAMEENDOFFSETREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// ReadCOMPFRAMECOUNTREADBACK reads COMP_FRAME_COUNT_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadCOMPFRAMECOUNTREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteCOMPFRAMECOUNTREADBACK writes COMP_FRAME_COUNT_READ_BACK
func (p *VideoAst2700V1VIDEO) WriteCOMPFRAMECOUNTREADBACK(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadUSERHEADERPARAM reads USER_HEADER_PARAM
func (p *VideoAst2700V1VIDEO) ReadUSERHEADERPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteUSERHEADERPARAM writes USER_HEADER_PARAM
func (p *VideoAst2700V1VIDEO) WriteUSERHEADERPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadCOMPSIZEREADBACK reads COMP_SIZE_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadCOMPSIZEREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// ReadSRCLREDGEDET reads SRC_LR_EDGE_DET
func (p *VideoAst2700V1VIDEO) ReadSRCLREDGEDET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteSRCLREDGEDET writes SRC_LR_EDGE_DET
func (p *VideoAst2700V1VIDEO) WriteSRCLREDGEDET(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadSRCTBEDGEDET reads SRC_TB_EDGE_DET
func (p *VideoAst2700V1VIDEO) ReadSRCTBEDGEDET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteSRCTBEDGEDET writes SRC_TB_EDGE_DET
func (p *VideoAst2700V1VIDEO) WriteSRCTBEDGEDET(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadMODEDETECTSTATUS reads MODE_DETECT_STATUS
func (p *VideoAst2700V1VIDEO) ReadMODEDETECTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteMODEDETECTSTATUS writes MODE_DETECT_STATUS
func (p *VideoAst2700V1VIDEO) WriteMODEDETECTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadSYNCSTATUS reads SYNC_STATUS
func (p *VideoAst2700V1VIDEO) ReadSYNCSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// WriteSYNCSTATUS writes SYNC_STATUS
func (p *VideoAst2700V1VIDEO) WriteSYNCSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x009c, uint32(val))
}

// ReadHTOTALPIXELS reads H_TOTAL_PIXELS
func (p *VideoAst2700V1VIDEO) ReadHTOTALPIXELS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteHTOTALPIXELS writes H_TOTAL_PIXELS
func (p *VideoAst2700V1VIDEO) WriteHTOTALPIXELS(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadEXTMODEDETECTCTRL1 reads EXT_MODE_DETECT_CTRL1
func (p *VideoAst2700V1VIDEO) ReadEXTMODEDETECTCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteEXTMODEDETECTCTRL1 writes EXT_MODE_DETECT_CTRL1
func (p *VideoAst2700V1VIDEO) WriteEXTMODEDETECTCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadEXTCTRL1 reads EXT_CTRL1
func (p *VideoAst2700V1VIDEO) ReadEXTCTRL1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteEXTCTRL1 writes EXT_CTRL1
func (p *VideoAst2700V1VIDEO) WriteEXTCTRL1(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// ReadDIRECTACCESSTIMING1 reads DIRECT_ACCESS_TIMING1
func (p *VideoAst2700V1VIDEO) ReadDIRECTACCESSTIMING1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteDIRECTACCESSTIMING1 writes DIRECT_ACCESS_TIMING1
func (p *VideoAst2700V1VIDEO) WriteDIRECTACCESSTIMING1(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

// ReadDIRECTACCESSTIMING2 reads DIRECT_ACCESS_TIMING2
func (p *VideoAst2700V1VIDEO) ReadDIRECTACCESSTIMING2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteDIRECTACCESSTIMING2 writes DIRECT_ACCESS_TIMING2
func (p *VideoAst2700V1VIDEO) WriteDIRECTACCESSTIMING2(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadEXTCTRL2 reads EXT_CTRL2
func (p *VideoAst2700V1VIDEO) ReadEXTCTRL2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteEXTCTRL2 writes EXT_CTRL2
func (p *VideoAst2700V1VIDEO) WriteEXTCTRL2(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadSRCLREDGEDET4K2K reads SRC_LR_EDGE_DET_4K2K
func (p *VideoAst2700V1VIDEO) ReadSRCLREDGEDET4K2K() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteSRCLREDGEDET4K2K writes SRC_LR_EDGE_DET_4K2K
func (p *VideoAst2700V1VIDEO) WriteSRCLREDGEDET4K2K(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadMODEDETECTSTATUS4K2K reads MODE_DETECT_STATUS_4K2K
func (p *VideoAst2700V1VIDEO) ReadMODEDETECTSTATUS4K2K() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteMODEDETECTSTATUS4K2K writes MODE_DETECT_STATUS_4K2K
func (p *VideoAst2700V1VIDEO) WriteMODEDETECTSTATUS4K2K(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadENGINESTATUS reads Video engine status readback registers 1..4.[n] (n < 4)
func (p *VideoAst2700V1VIDEO) ReadENGINESTATUS(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0 + uint32(n)*4))
}

// ReadEXTRAMODEDETECTSTATUS reads EXTRA_MODE_DETECT_STATUS
func (p *VideoAst2700V1VIDEO) ReadEXTRAMODEDETECTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// ReadBCDBOUNDINGBOX1 reads BCD_BOUNDING_BOX1
func (p *VideoAst2700V1VIDEO) ReadBCDBOUNDINGBOX1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// ReadBCDBOUNDINGBOX2 reads BCD_BOUNDING_BOX2
func (p *VideoAst2700V1VIDEO) ReadBCDBOUNDINGBOX2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// ReadMGMTSEQCTRL reads Management compression sequence control.
func (p *VideoAst2700V1VIDEO) ReadMGMTSEQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// WriteMGMTSEQCTRL writes Management compression sequence control.
func (p *VideoAst2700V1VIDEO) WriteMGMTSEQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0204, uint32(val))
}

// ReadMGMTCTRL reads Management compression control.
func (p *VideoAst2700V1VIDEO) ReadMGMTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0208))
}

// WriteMGMTCTRL writes Management compression control.
func (p *VideoAst2700V1VIDEO) WriteMGMTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0208, uint32(val))
}

// ReadMGMTCOMPPROCOFFSET reads MGMT_COMP_PROC_OFFSET
func (p *VideoAst2700V1VIDEO) ReadMGMTCOMPPROCOFFSET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0238))
}

// WriteMGMTCOMPPROCOFFSET writes MGMT_COMP_PROC_OFFSET
func (p *VideoAst2700V1VIDEO) WriteMGMTCOMPPROCOFFSET(val uint32) {
    reg.Write(uint32(p.Base)+0x0238, uint32(val))
}

// ReadMGMTCOMPOFFSET reads MGMT_COMP_OFFSET
func (p *VideoAst2700V1VIDEO) ReadMGMTCOMPOFFSET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x023c))
}

// WriteMGMTCOMPOFFSET writes MGMT_COMP_OFFSET
func (p *VideoAst2700V1VIDEO) WriteMGMTCOMPOFFSET(val uint32) {
    reg.Write(uint32(p.Base)+0x023c, uint32(val))
}

// ReadMGMTSRC0ADDR reads MGMT_SRC0_ADDR
func (p *VideoAst2700V1VIDEO) ReadMGMTSRC0ADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0244))
}

// WriteMGMTSRC0ADDR writes MGMT_SRC0_ADDR
func (p *VideoAst2700V1VIDEO) WriteMGMTSRC0ADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0244, uint32(val))
}

// ReadMGMTSRCSCANLINEOFFSET reads MGMT_SRC_SCANLINE_OFFSET
func (p *VideoAst2700V1VIDEO) ReadMGMTSRCSCANLINEOFFSET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0248))
}

// WriteMGMTSRCSCANLINEOFFSET writes MGMT_SRC_SCANLINE_OFFSET
func (p *VideoAst2700V1VIDEO) WriteMGMTSRCSCANLINEOFFSET(val uint32) {
    reg.Write(uint32(p.Base)+0x0248, uint32(val))
}

// ReadMGMTSRC1ADDR reads MGMT_SRC1_ADDR
func (p *VideoAst2700V1VIDEO) ReadMGMTSRC1ADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x024c))
}

// WriteMGMTSRC1ADDR writes MGMT_SRC1_ADDR
func (p *VideoAst2700V1VIDEO) WriteMGMTSRC1ADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x024c, uint32(val))
}

// ReadMGMTBCDADDR reads MGMT_BCD_ADDR
func (p *VideoAst2700V1VIDEO) ReadMGMTBCDADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0250))
}

// WriteMGMTBCDADDR writes MGMT_BCD_ADDR
func (p *VideoAst2700V1VIDEO) WriteMGMTBCDADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0250, uint32(val))
}

// ReadMGMTCOMPADDR reads MGMT_COMP_ADDR
func (p *VideoAst2700V1VIDEO) ReadMGMTCOMPADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0254))
}

// WriteMGMTCOMPADDR writes MGMT_COMP_ADDR
func (p *VideoAst2700V1VIDEO) WriteMGMTCOMPADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0254, uint32(val))
}

// ReadMGMTCOMPCTRL reads MGMT_COMP_CTRL
func (p *VideoAst2700V1VIDEO) ReadMGMTCOMPCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0260))
}

// WriteMGMTCOMPCTRL writes MGMT_COMP_CTRL
func (p *VideoAst2700V1VIDEO) WriteMGMTCOMPCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0260, uint32(val))
}

// ReadMGMTQUANTIZATIONVALUE reads MGMT_QUANTIZATION_VALUE
func (p *VideoAst2700V1VIDEO) ReadMGMTQUANTIZATIONVALUE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0268))
}

// WriteMGMTQUANTIZATIONVALUE writes MGMT_QUANTIZATION_VALUE
func (p *VideoAst2700V1VIDEO) WriteMGMTQUANTIZATIONVALUE(val uint32) {
    reg.Write(uint32(p.Base)+0x0268, uint32(val))
}

// ReadMGMTCOMPTOTALSIZEREADBACK reads MGMT_COMP_TOTAL_SIZE_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadMGMTCOMPTOTALSIZEREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0270))
}

// ReadMGMTFRAMEENDOFFSETREADBACK reads MGMT_FRAME_END_OFFSET_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadMGMTFRAMEENDOFFSETREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0278))
}

// ReadMGMTUSERHEADERPARAM reads MGMT_USER_HEADER_PARAM
func (p *VideoAst2700V1VIDEO) ReadMGMTUSERHEADERPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0280))
}

// WriteMGMTUSERHEADERPARAM writes MGMT_USER_HEADER_PARAM
func (p *VideoAst2700V1VIDEO) WriteMGMTUSERHEADERPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0280, uint32(val))
}

// ReadGLOBALCTRL reads Video control and SRAM table mapping.
func (p *VideoAst2700V1VIDEO) ReadGLOBALCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0300))
}

// WriteGLOBALCTRL writes Video control and SRAM table mapping.
func (p *VideoAst2700V1VIDEO) WriteGLOBALCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0300, uint32(val))
}

// ReadINTERRUPTCTRL reads INTERRUPT_CTRL
func (p *VideoAst2700V1VIDEO) ReadINTERRUPTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0304))
}

// WriteINTERRUPTCTRL writes INTERRUPT_CTRL
func (p *VideoAst2700V1VIDEO) WriteINTERRUPTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0304, uint32(val))
}

// ReadINTERRUPTSTATUS reads INTERRUPT_STATUS
func (p *VideoAst2700V1VIDEO) ReadINTERRUPTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0308))
}

// WriteINTERRUPTSTATUS writes INTERRUPT_STATUS
func (p *VideoAst2700V1VIDEO) WriteINTERRUPTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0308, uint32(val))
}

// ReadMODEDETECT reads MODE_DETECT
func (p *VideoAst2700V1VIDEO) ReadMODEDETECT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x030c))
}

// WriteMODEDETECT writes MODE_DETECT
func (p *VideoAst2700V1VIDEO) WriteMODEDETECT(val uint32) {
    reg.Write(uint32(p.Base)+0x030c, uint32(val))
}

// ReadMEMRESTRICTSTART reads MEM_RESTRICT_START
func (p *VideoAst2700V1VIDEO) ReadMEMRESTRICTSTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0310))
}

// WriteMEMRESTRICTSTART writes MEM_RESTRICT_START
func (p *VideoAst2700V1VIDEO) WriteMEMRESTRICTSTART(val uint32) {
    reg.Write(uint32(p.Base)+0x0310, uint32(val))
}

// ReadMEMRESTRICTEND reads MEM_RESTRICT_END
func (p *VideoAst2700V1VIDEO) ReadMEMRESTRICTEND() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0314))
}

// WriteMEMRESTRICTEND writes MEM_RESTRICT_END
func (p *VideoAst2700V1VIDEO) WriteMEMRESTRICTEND(val uint32) {
    reg.Write(uint32(p.Base)+0x0314, uint32(val))
}

// ReadMEMRESTRICTSTART2 reads MEM_RESTRICT_START2
func (p *VideoAst2700V1VIDEO) ReadMEMRESTRICTSTART2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0318))
}

// WriteMEMRESTRICTSTART2 writes MEM_RESTRICT_START2
func (p *VideoAst2700V1VIDEO) WriteMEMRESTRICTSTART2(val uint32) {
    reg.Write(uint32(p.Base)+0x0318, uint32(val))
}

// ReadDATATRUNCATION reads DATA_TRUNCATION
func (p *VideoAst2700V1VIDEO) ReadDATATRUNCATION() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0328))
}

// WriteDATATRUNCATION writes DATA_TRUNCATION
func (p *VideoAst2700V1VIDEO) WriteDATATRUNCATION(val uint32) {
    reg.Write(uint32(p.Base)+0x0328, uint32(val))
}

// ReadWATCHDOGREADBACK reads WATCHDOG_READ_BACK
func (p *VideoAst2700V1VIDEO) ReadWATCHDOGREADBACK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x033c))
}

// ReadVGASCRATCHREMAP reads VGA scratch remap readback registers.[n] (n < 10)
func (p *VideoAst2700V1VIDEO) ReadVGASCRATCHREMAP(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0340 + uint32(n)*4))
}

// ReadTABLESRAM reads Quantization/Huffman table SRAM window selected by GLOBAL_CTRL.[n] (n < 128)
func (p *VideoAst2700V1VIDEO) ReadTABLESRAM(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0400 + uint32(n)*4))
}

// WriteTABLESRAM writes Quantization/Huffman table SRAM window selected by GLOBAL_CTRL.[n] (n < 128)
func (p *VideoAst2700V1VIDEO) WriteTABLESRAM(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0400+uint32(n)*4, uint32(val))
}

