// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// WdtAst2700V1WDT AST2700 watchdog timer register block.
type WdtAst2700V1WDT struct {
    Base uintptr
}

// ReadSTATUS reads Counter status register (WDT00), current down-counter value.
func (p *WdtAst2700V1WDT) ReadSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// ReadRELOAD reads Counter reload value register (WDT04), units of 1 us.
func (p *WdtAst2700V1WDT) ReadRELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteRELOAD writes Counter reload value register (WDT04), units of 1 us.
func (p *WdtAst2700V1WDT) WriteRELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadRESTART reads Counter restart register (WDT08); write 0x4755 to restart.
func (p *WdtAst2700V1WDT) ReadRESTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteRESTART writes Counter restart register (WDT08); write 0x4755 to restart.
func (p *WdtAst2700V1WDT) WriteRESTART(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCTRL reads Watchdog control register (WDT0C).
func (p *WdtAst2700V1WDT) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCTRL writes Watchdog control register (WDT0C).
func (p *WdtAst2700V1WDT) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadTIMEOUTSTATUS reads Timeout and interrupt status register (WDT10).
func (p *WdtAst2700V1WDT) ReadTIMEOUTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// ReadCLEARTIMEOUTSTATUS reads Clear timeout and interrupt status register (WDT14).
func (p *WdtAst2700V1WDT) ReadCLEARTIMEOUTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCLEARTIMEOUTSTATUS writes Clear timeout and interrupt status register (WDT14).
func (p *WdtAst2700V1WDT) WriteCLEARTIMEOUTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadRESETWIDTH reads External reset pulse width/control register (WDT18).
func (p *WdtAst2700V1WDT) ReadRESETWIDTH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteRESETWIDTH writes External reset pulse width/control register (WDT18).
func (p *WdtAst2700V1WDT) WriteRESETWIDTH(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadRESETMASK reads Watchdog reset mask registers[n] (n < 5)
func (p *WdtAst2700V1WDT) ReadRESETMASK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c + uint32(n)*4))
}

// WriteRESETMASK writes Watchdog reset mask registers[n] (n < 5)
func (p *WdtAst2700V1WDT) WriteRESETMASK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x001c+uint32(n)*4, uint32(val))
}

// ReadSWRESETCTRL reads Software mode reset control register (WDT30).
func (p *WdtAst2700V1WDT) ReadSWRESETCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteSWRESETCTRL writes Software mode reset control register (WDT30).
func (p *WdtAst2700V1WDT) WriteSWRESETCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadSWRESETMASK reads Software mode reset mask registers[n] (n < 5)
func (p *WdtAst2700V1WDT) ReadSWRESETMASK(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034 + uint32(n)*4))
}

// WriteSWRESETMASK writes Software mode reset mask registers[n] (n < 5)
func (p *WdtAst2700V1WDT) WriteSWRESETMASK(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0034+uint32(n)*4, uint32(val))
}

// ReadFUNCTIONDISABLE reads Function disable control register (WDT48), write-1-set until SRST#.
func (p *WdtAst2700V1WDT) ReadFUNCTIONDISABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteFUNCTIONDISABLE writes Function disable control register (WDT48), write-1-set until SRST#.
func (p *WdtAst2700V1WDT) WriteFUNCTIONDISABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadSCRATCH reads Scratch register (WDT4C).
func (p *WdtAst2700V1WDT) ReadSCRATCH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteSCRATCH writes Scratch register (WDT4C).
func (p *WdtAst2700V1WDT) WriteSCRATCH(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadRESETMASKWRITEPROTECT reads Reset mask write protection registers[n] (n < 5)
func (p *WdtAst2700V1WDT) ReadRESETMASKWRITEPROTECT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050 + uint32(n)*4))
}

// WriteRESETMASKWRITEPROTECT writes Reset mask write protection registers[n] (n < 5)
func (p *WdtAst2700V1WDT) WriteRESETMASKWRITEPROTECT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0050+uint32(n)*4, uint32(val))
}

// ReadSWRESETMASKWRITEPROTECT reads Software reset mask write protection registers[n] (n < 5)
func (p *WdtAst2700V1WDT) ReadSWRESETMASKWRITEPROTECT(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064 + uint32(n)*4))
}

// WriteSWRESETMASKWRITEPROTECT writes Software reset mask write protection registers[n] (n < 5)
func (p *WdtAst2700V1WDT) WriteSWRESETMASKWRITEPROTECT(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0064+uint32(n)*4, uint32(val))
}

// ReadWRITEPROTECT reads WDT register write protection register (WDT7C).
func (p *WdtAst2700V1WDT) ReadWRITEPROTECT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteWRITEPROTECT writes WDT register write protection register (WDT7C).
func (p *WdtAst2700V1WDT) WriteWRITEPROTECT(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

