// Generated by aspeed-data-gen. DO NOT EDIT.
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
//!Peripheral access API (generated using chiptool v0.1.0 (5a2574e 2026-04-28))
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Interrupt {}
unsafe impl riscv::InterruptNumber for Interrupt {
    const MAX_INTERRUPT_NUMBER: usize = 0;
    #[inline(always)]
    fn number(self) -> usize {
        unreachable!()
    }
    #[inline(always)]
    fn from_number(value: usize) -> riscv::result::Result<Self> {
        Err(riscv::result::Error::InvalidVariant(value))
    }
}
unsafe impl riscv::ExternalInterruptNumber for Interrupt {}
#[cfg(feature = "rt")]
mod _vectors {
    unsafe extern "C" {
        fn DefaultHandler();
    }
    pub type ExternalInterruptHandler = unsafe extern "C" fn();
    #[unsafe(export_name = "_external_interrupt_handlers")]
    pub static __EXTERNAL_INTERRUPTS: [ExternalInterruptHandler; 0] = [];
}
#[cfg(feature = "rt")]
pub use Interrupt as interrupt;
///UART12 (16550, 4-byte stride, 1846153 Hz clock)
pub const UART12: uart_v1::UART = unsafe { uart_v1::UART::from_ptr(0x14c3_3b00usize as _) };
///AST2700 BootMCU 64-bit timer @ 1 MHz (IRQ 7, MTIP)
pub const TIMER: bootmcu_timer_v1::TIMER =
    unsafe { bootmcu_timer_v1::TIMER::from_ptr(0x14c3_6000usize as _) };
///AST2700 G7 watchdog timer 0
pub const WDT0: wdt_v1::WDT = unsafe { wdt_v1::WDT::from_ptr(0x14c3_7000usize as _) };
///IPC1 data-channel bus (4 sub-channels, polling)
pub const IPC1: ipc1_v1::IPC1 = unsafe { ipc1_v1::IPC1::from_ptr(0x14c3_9000usize as _) };
pub mod bootmcu_timer_v1 {
    ///AST2700 BootMCU 64-bit free-running timer with alarm interrupt. Clocked at 1 MHz; INTR_STS is cleared by writing ALARM_L and ALARM_H. Base address: 0x14C36000 (IO-die, BootMCU view).
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct TIMER {
        ptr: *mut u8,
    }
    unsafe impl Send for TIMER {}
    unsafe impl Sync for TIMER {}
    impl TIMER {
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
            Self { ptr: ptr as _ }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut () {
            self.ptr as _
        }
        ///Counter low 32 bits (read-only, free-running).
        #[inline(always)]
        pub const fn COUNT_L(self) -> crate::common::Reg<u32, crate::common::R> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
        }
        ///Counter high 32 bits (read-only, free-running).
        #[inline(always)]
        pub const fn COUNT_H(self) -> crate::common::Reg<u32, crate::common::R> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
        }
        ///Alarm compare value — low 32 bits. Writing this register also clears TMR_CTRL.INTR_STS.
        #[inline(always)]
        pub const fn ALARM_L(self) -> crate::common::Reg<u32, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
        }
        ///Alarm compare value — high 32 bits. Writing this register also clears TMR_CTRL.INTR_STS.
        #[inline(always)]
        pub const fn ALARM_H(self) -> crate::common::Reg<u32, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0cusize) as _) }
        }
        ///Timer control and interrupt status register. Bits written 1 in this register set the corresponding function. Use CTRL_CLR to clear bits.
        #[inline(always)]
        pub const fn CTRL(self) -> crate::common::Reg<CTRL, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
        }
        ///Write-1-clear mirror of CTRL. Write 1 to a bit to clear the corresponding CTRL bit. Example: write TMR_CTRL_EN to stop the timer.
        #[inline(always)]
        pub const fn CTRL_CLR(self) -> crate::common::Reg<CTRL, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
        }
    }
    ///Timer control register (used for both CTRL and CTRL_CLR).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct CTRL(pub u32);
    impl CTRL {
        ///Timer enable. 1 = timer counting enabled. Write to CTRL_CLR to stop.
        #[must_use]
        #[inline(always)]
        pub const fn EN(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Timer enable. 1 = timer counting enabled. Write to CTRL_CLR to stop.
        #[inline(always)]
        pub const fn set_EN(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Reset-on-alarm enable. 1 = counter resets to 0 when ALARM is reached.
        #[must_use]
        #[inline(always)]
        pub const fn RESET_EN(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Reset-on-alarm enable. 1 = counter resets to 0 when ALARM is reached.
        #[inline(always)]
        pub const fn set_RESET_EN(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Counter clear (self-clearing). Write 1 to reset the 64-bit counter to 0.
        #[must_use]
        #[inline(always)]
        pub const fn COUNT_CLR(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Counter clear (self-clearing). Write 1 to reset the 64-bit counter to 0.
        #[inline(always)]
        pub const fn set_COUNT_CLR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Interrupt status. Set when COUNT reaches ALARM. Cleared by writing ALARM_L or ALARM_H (not by writing CTRL_CLR).
        #[must_use]
        #[inline(always)]
        pub const fn INTR_STS(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///Interrupt status. Set when COUNT reaches ALARM. Cleared by writing ALARM_L or ALARM_H (not by writing CTRL_CLR).
        #[inline(always)]
        pub const fn set_INTR_STS(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for CTRL {
        #[inline(always)]
        fn default() -> CTRL {
            CTRL(0)
        }
    }
    impl core::fmt::Debug for CTRL {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("CTRL")
                .field("EN", &self.EN())
                .field("RESET_EN", &self.RESET_EN())
                .field("COUNT_CLR", &self.COUNT_CLR())
                .field("INTR_STS", &self.INTR_STS())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for CTRL {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "CTRL {{ EN: {=bool:?}, RESET_EN: {=bool:?}, COUNT_CLR: {=bool:?}, INTR_STS: {=bool:?} }}",
                self.EN(), self.RESET_EN(), self.COUNT_CLR(), self.INTR_STS()
            )
        }
    }
}
pub mod common {
    use core::marker::PhantomData;
    #[derive(Copy, Clone, PartialEq, Eq)]
    pub struct RW;
    #[derive(Copy, Clone, PartialEq, Eq)]
    pub struct R;
    #[derive(Copy, Clone, PartialEq, Eq)]
    pub struct W;
    mod sealed {
        use super::*;
        pub trait Access {}
        impl Access for R {}
        impl Access for W {}
        impl Access for RW {}
    }
    pub trait Access: sealed::Access + Copy {}
    impl Access for R {}
    impl Access for W {}
    impl Access for RW {}
    pub trait Read: Access {}
    impl Read for RW {}
    impl Read for R {}
    pub trait Write: Access {}
    impl Write for RW {}
    impl Write for W {}
    #[derive(Copy, Clone, PartialEq, Eq)]
    pub struct Reg<T: Copy, A: Access> {
        ptr: *mut u8,
        phantom: PhantomData<*mut (T, A)>,
    }
    unsafe impl<T: Copy, A: Access> Send for Reg<T, A> {}
    unsafe impl<T: Copy, A: Access> Sync for Reg<T, A> {}
    impl<T: Copy, A: Access> Reg<T, A> {
        #[allow(clippy::missing_safety_doc)]
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut T) -> Self {
            Self {
                ptr: ptr as _,
                phantom: PhantomData,
            }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut T {
            self.ptr as _
        }
    }
    impl<T: Copy, A: Read> Reg<T, A> {
        #[inline(always)]
        pub fn read(&self) -> T {
            unsafe { (self.ptr as *mut T).read_volatile() }
        }
    }
    impl<T: Copy, A: Write> Reg<T, A> {
        #[inline(always)]
        pub fn write_value(&self, val: T) {
            unsafe { (self.ptr as *mut T).write_volatile(val) }
        }
    }
    impl<T: Default + Copy, A: Write> Reg<T, A> {
        #[inline(always)]
        pub fn write(&self, f: impl FnOnce(&mut T)) {
            let mut val = Default::default();
            f(&mut val);
            self.write_value(val);
        }
    }
    impl<T: Copy, A: Read + Write> Reg<T, A> {
        #[inline(always)]
        pub fn modify(&self, f: impl FnOnce(&mut T)) {
            let mut val = self.read();
            f(&mut val);
            self.write_value(val);
        }
    }
}
pub mod ipc1_v1 {
    ///One half (TX or RX) of an IPC1 sub-channel. TX half is at sub-channel_base + 0x100; RX half at sub-channel_base + 0x000. Each half supports 4 message IDs (0–3).
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct CHAN {
        ptr: *mut u8,
    }
    unsafe impl Send for CHAN {}
    unsafe impl Sync for CHAN {}
    impl CHAN {
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
            Self { ptr: ptr as _ }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut () {
            self.ptr as _
        }
        ///Message trigger register. Write BIT(id) to dispatch a message with the given ID to the remote peer. The corresponding bit in STATUS is set on the remote side.
        #[inline(always)]
        pub const fn TRIG(self) -> crate::common::Reg<ID_MASK, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
        }
        ///Per-ID receive enable mask. Write BIT(id) to enable reception of messages with that ID. Only enabled IDs set STATUS bits.
        #[inline(always)]
        pub const fn ENABLE(self) -> crate::common::Reg<ID_MASK, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
        }
        ///Pending message status. Bit n is set when a message with ID n has been received and not yet consumed. Write BIT(id) to clear (acknowledge) after reading the payload.
        #[inline(always)]
        pub const fn STATUS(self) -> crate::common::Reg<ID_MASK, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
        }
        ///32-byte payload for message ID 0 (8 × 32-bit words). The transmitter writes here before triggering; the receiver reads here after detecting STATUS\[0\].
        #[inline(always)]
        pub const fn DATA0(self, n: usize) -> crate::common::Reg<u32, crate::common::RW> {
            assert!(n < 8usize);
            unsafe {
                crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize + n * 4usize) as _)
            }
        }
        ///32-byte payload for message ID 1 (8 × 32-bit words).
        #[inline(always)]
        pub const fn DATA1(self, n: usize) -> crate::common::Reg<u32, crate::common::RW> {
            assert!(n < 8usize);
            unsafe {
                crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x30usize + n * 4usize) as _)
            }
        }
        ///32-byte payload for message ID 2 (8 × 32-bit words).
        #[inline(always)]
        pub const fn DATA2(self, n: usize) -> crate::common::Reg<u32, crate::common::RW> {
            assert!(n < 8usize);
            unsafe {
                crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x50usize + n * 4usize) as _)
            }
        }
        ///32-byte payload for message ID 3 (Caliptra/reserved).
        #[inline(always)]
        pub const fn DATA3(self, n: usize) -> crate::common::Reg<u32, crate::common::RW> {
            assert!(n < 8usize);
            unsafe {
                crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x70usize + n * 4usize) as _)
            }
        }
    }
    ///AST2700 BootMCU IPC1 bus — 4 sub-channels at stride 0x200. Sub-channel index: 0=secure-CA35, 1=non-secure-CA35, 2=SSP, 3=TSP. Base address: 0x14C39000 (IO-die, BootMCU view).
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct IPC1 {
        ptr: *mut u8,
    }
    unsafe impl Send for IPC1 {}
    unsafe impl Sync for IPC1 {}
    impl IPC1 {
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
            Self { ptr: ptr as _ }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut () {
            self.ptr as _
        }
        ///Sub-channels 0–3 (stride 0x200 each).
        #[inline(always)]
        pub const fn CH(self, n: usize) -> SUBCHAN {
            assert!(n < 4usize);
            unsafe { SUBCHAN::from_ptr(self.ptr.wrapping_add(0x0usize + n * 512usize) as _) }
        }
    }
    ///One IPC1 sub-channel consisting of an RX half and a TX half. RX half (remote peer's TX) is at offset 0x000. TX half (this side's TX) is at offset 0x100.
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct SUBCHAN {
        ptr: *mut u8,
    }
    unsafe impl Send for SUBCHAN {}
    unsafe impl Sync for SUBCHAN {}
    impl SUBCHAN {
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
            Self { ptr: ptr as _ }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut () {
            self.ptr as _
        }
        ///Receive half — read incoming messages from the remote peer.
        #[inline(always)]
        pub const fn RX(self) -> CHAN {
            unsafe { CHAN::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
        }
        ///Transmit half — write outgoing messages to the remote peer.
        #[inline(always)]
        pub const fn TX(self) -> CHAN {
            unsafe { CHAN::from_ptr(self.ptr.wrapping_add(0x0100usize) as _) }
        }
    }
    ///4-bit mask, one bit per message ID (IDs 0–3).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct ID_MASK(pub u32);
    impl ID_MASK {
        ///Message ID 0.
        #[must_use]
        #[inline(always)]
        pub const fn ID0(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Message ID 0.
        #[inline(always)]
        pub const fn set_ID0(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Message ID 1.
        #[must_use]
        #[inline(always)]
        pub const fn ID1(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Message ID 1.
        #[inline(always)]
        pub const fn set_ID1(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Message ID 2.
        #[must_use]
        #[inline(always)]
        pub const fn ID2(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Message ID 2.
        #[inline(always)]
        pub const fn set_ID2(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Message ID 3 (Caliptra/reserved).
        #[must_use]
        #[inline(always)]
        pub const fn ID3(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Message ID 3 (Caliptra/reserved).
        #[inline(always)]
        pub const fn set_ID3(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for ID_MASK {
        #[inline(always)]
        fn default() -> ID_MASK {
            ID_MASK(0)
        }
    }
    impl core::fmt::Debug for ID_MASK {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("ID_MASK")
                .field("ID0", &self.ID0())
                .field("ID1", &self.ID1())
                .field("ID2", &self.ID2())
                .field("ID3", &self.ID3())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for ID_MASK {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "ID_MASK {{ ID0: {=bool:?}, ID1: {=bool:?}, ID2: {=bool:?}, ID3: {=bool:?} }}",
                self.ID0(),
                self.ID1(),
                self.ID2(),
                self.ID3()
            )
        }
    }
}
pub mod uart_v1 {
    ///16550-compatible UART register block. Base address: UART11 at 0x7E79_0500 (CM3 view). All registers at 4-byte stride; only bits \[7:0\] carry data.
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct UART {
        ptr: *mut u8,
    }
    unsafe impl Send for UART {}
    unsafe impl Sync for UART {}
    impl UART {
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
            Self { ptr: ptr as _ }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut () {
            self.ptr as _
        }
        ///Receiver Buffer Register (read, DLAB=0) / Transmit Holding Register (write, DLAB=0) / Baud Divisor Low byte (DLAB=1). Read: received byte. Write: byte to transmit. DLAB=1 access handled in HAL code via raw pointer.
        #[inline(always)]
        pub const fn RBR_THR(self) -> crate::common::Reg<DATA8, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
        }
        ///Interrupt Enable Register (DLAB=0) / Baud Divisor High byte (DLAB=1). DLAB=1 access handled in HAL code via raw pointer.
        #[inline(always)]
        pub const fn IER(self) -> crate::common::Reg<IER, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
        }
        ///FIFO Control Register (write) / Interrupt Identification Register (read). Reads return IIR; writes configure FIFO via FCR fields. FCR is write-only; IIR is read-only.
        #[inline(always)]
        pub const fn FCR_IIR(self) -> crate::common::Reg<FCR_IIR, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
        }
        ///Line Control Register. Controls data format and DLAB.
        #[inline(always)]
        pub const fn LCR(self) -> crate::common::Reg<LCR, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0cusize) as _) }
        }
        ///Modem Control Register.
        #[inline(always)]
        pub const fn MCR(self) -> crate::common::Reg<MCR, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x10usize) as _) }
        }
        ///Line Status Register. TX/RX status flags.
        #[inline(always)]
        pub const fn LSR(self) -> crate::common::Reg<LSR, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x14usize) as _) }
        }
        ///Modem Status Register.
        #[inline(always)]
        pub const fn MSR(self) -> crate::common::Reg<MSR, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x18usize) as _) }
        }
        ///Scratch Register. Read/write with no hardware effect.
        #[inline(always)]
        pub const fn SCR(self) -> crate::common::Reg<DATA8, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x1cusize) as _) }
        }
    }
    ///8-bit data register (RBR/THR and SCR share this layout).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct DATA8(pub u32);
    impl DATA8 {
        ///Data byte (bits \[7:0\]).
        #[must_use]
        #[inline(always)]
        pub const fn DATA(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0xff;
            val as u8
        }
        ///Data byte (bits \[7:0\]).
        #[inline(always)]
        pub const fn set_DATA(&mut self, val: u8) {
            self.0 = (self.0 & !(0xff << 0usize)) | (((val as u32) & 0xff) << 0usize);
        }
    }
    impl Default for DATA8 {
        #[inline(always)]
        fn default() -> DATA8 {
            DATA8(0)
        }
    }
    impl core::fmt::Debug for DATA8 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("DATA8").field("DATA", &self.DATA()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for DATA8 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "DATA8 {{ DATA: {=u8:?} }}", self.DATA())
        }
    }
    ///FIFO Control Register (write) / Interrupt Identification Register (read). Write access configures FIFO; read access returns interrupt status.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct FCR_IIR(pub u32);
    impl FCR_IIR {
        ///Write (FCR): FIFO Enable. 1 = enable TX and RX FIFOs; clearing this bit resets both FIFOs. Read (IIR): Interrupt Pending (active-low). 0 = interrupt pending.
        #[must_use]
        #[inline(always)]
        pub const fn FIFOE_OR_IP(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Write (FCR): FIFO Enable. 1 = enable TX and RX FIFOs; clearing this bit resets both FIFOs. Read (IIR): Interrupt Pending (active-low). 0 = interrupt pending.
        #[inline(always)]
        pub const fn set_FIFOE_OR_IP(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Write (FCR): Receiver FIFO Reset. Write 1 to flush RX FIFO. Read (IIR): Interrupt ID bit 1.
        #[must_use]
        #[inline(always)]
        pub const fn RFIFOR_OR_IID1(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Write (FCR): Receiver FIFO Reset. Write 1 to flush RX FIFO. Read (IIR): Interrupt ID bit 1.
        #[inline(always)]
        pub const fn set_RFIFOR_OR_IID1(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Write (FCR): Transmitter FIFO Reset. Write 1 to flush TX FIFO. Read (IIR): Interrupt ID bit 2.
        #[must_use]
        #[inline(always)]
        pub const fn XFIFOR_OR_IID2(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Write (FCR): Transmitter FIFO Reset. Write 1 to flush TX FIFO. Read (IIR): Interrupt ID bit 2.
        #[inline(always)]
        pub const fn set_XFIFOR_OR_IID2(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Write (FCR): DMA mode select. 0 = mode 0; 1 = mode 1. Read (IIR): Interrupt ID bit 3 (FIFO timeout indicator on 16550D).
        #[must_use]
        #[inline(always)]
        pub const fn DMA_OR_IID3(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Write (FCR): DMA mode select. 0 = mode 0; 1 = mode 1. Read (IIR): Interrupt ID bit 3 (FIFO timeout indicator on 16550D).
        #[inline(always)]
        pub const fn set_DMA_OR_IID3(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Write (FCR): TX FIFO trigger threshold. 00=empty; 01=2 bytes; 10=quarter full; 11=half full.
        #[must_use]
        #[inline(always)]
        pub const fn TX_TRIG(&self) -> u8 {
            let val = (self.0 >> 4usize) & 0x03;
            val as u8
        }
        ///Write (FCR): TX FIFO trigger threshold. 00=empty; 01=2 bytes; 10=quarter full; 11=half full.
        #[inline(always)]
        pub const fn set_TX_TRIG(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize);
        }
        ///Write (FCR): RX FIFO trigger threshold. 00=1 byte; 01=quarter full; 10=half full; 11=2 from full. Read (IIR): FIFO enabled status bits \[7:6\] (11=FIFOs enabled).
        #[must_use]
        #[inline(always)]
        pub const fn RX_TRIG(&self) -> u8 {
            let val = (self.0 >> 6usize) & 0x03;
            val as u8
        }
        ///Write (FCR): RX FIFO trigger threshold. 00=1 byte; 01=quarter full; 10=half full; 11=2 from full. Read (IIR): FIFO enabled status bits \[7:6\] (11=FIFOs enabled).
        #[inline(always)]
        pub const fn set_RX_TRIG(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize);
        }
    }
    impl Default for FCR_IIR {
        #[inline(always)]
        fn default() -> FCR_IIR {
            FCR_IIR(0)
        }
    }
    impl core::fmt::Debug for FCR_IIR {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("FCR_IIR")
                .field("FIFOE_OR_IP", &self.FIFOE_OR_IP())
                .field("RFIFOR_OR_IID1", &self.RFIFOR_OR_IID1())
                .field("XFIFOR_OR_IID2", &self.XFIFOR_OR_IID2())
                .field("DMA_OR_IID3", &self.DMA_OR_IID3())
                .field("TX_TRIG", &self.TX_TRIG())
                .field("RX_TRIG", &self.RX_TRIG())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for FCR_IIR {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "FCR_IIR {{ FIFOE_OR_IP: {=bool:?}, RFIFOR_OR_IID1: {=bool:?}, XFIFOR_OR_IID2: {=bool:?}, DMA_OR_IID3: {=bool:?}, TX_TRIG: {=u8:?}, RX_TRIG: {=u8:?} }}",
                self.FIFOE_OR_IP(), self.RFIFOR_OR_IID1(), self.XFIFOR_OR_IID2(), self
                .DMA_OR_IID3(), self.TX_TRIG(), self.RX_TRIG()
            )
        }
    }
    ///Interrupt Enable Register (DLAB=0).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct IER(pub u32);
    impl IER {
        ///Enable Received Data Available Interrupt. 1 = generate IRQ when RBR has received data (LSR.DR=1) or FIFO reaches trigger level.
        #[must_use]
        #[inline(always)]
        pub const fn ERBFI(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Enable Received Data Available Interrupt. 1 = generate IRQ when RBR has received data (LSR.DR=1) or FIFO reaches trigger level.
        #[inline(always)]
        pub const fn set_ERBFI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Enable Transmitter Holding Register Empty Interrupt. 1 = generate IRQ when THR is empty (LSR.THRE=1).
        #[must_use]
        #[inline(always)]
        pub const fn ETBEI(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Enable Transmitter Holding Register Empty Interrupt. 1 = generate IRQ when THR is empty (LSR.THRE=1).
        #[inline(always)]
        pub const fn set_ETBEI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Enable Receiver Line Status Interrupt. 1 = generate IRQ on OE/PE/FE/BI errors (LSR bits 1-4).
        #[must_use]
        #[inline(always)]
        pub const fn ELSI(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Enable Receiver Line Status Interrupt. 1 = generate IRQ on OE/PE/FE/BI errors (LSR bits 1-4).
        #[inline(always)]
        pub const fn set_ELSI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Enable Modem Status Interrupt. 1 = generate IRQ on CTS/DSR/RI/DCD changes (MSR bits 0-3).
        #[must_use]
        #[inline(always)]
        pub const fn EDSSI(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Enable Modem Status Interrupt. 1 = generate IRQ on CTS/DSR/RI/DCD changes (MSR bits 0-3).
        #[inline(always)]
        pub const fn set_EDSSI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
    }
    impl Default for IER {
        #[inline(always)]
        fn default() -> IER {
            IER(0)
        }
    }
    impl core::fmt::Debug for IER {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("IER")
                .field("ERBFI", &self.ERBFI())
                .field("ETBEI", &self.ETBEI())
                .field("ELSI", &self.ELSI())
                .field("EDSSI", &self.EDSSI())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for IER {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "IER {{ ERBFI: {=bool:?}, ETBEI: {=bool:?}, ELSI: {=bool:?}, EDSSI: {=bool:?} }}",
                self.ERBFI(),
                self.ETBEI(),
                self.ELSI(),
                self.EDSSI()
            )
        }
    }
    ///Line Control Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct LCR(pub u32);
    impl LCR {
        ///Word Length Select. 00=5 bits; 01=6 bits; 10=7 bits; 11=8 bits.
        #[must_use]
        #[inline(always)]
        pub const fn WLS(&self) -> u8 {
            let val = (self.0 >> 0usize) & 0x03;
            val as u8
        }
        ///Word Length Select. 00=5 bits; 01=6 bits; 10=7 bits; 11=8 bits.
        #[inline(always)]
        pub const fn set_WLS(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize);
        }
        ///Stop Bits. 0 = 1 stop bit; 1 = 2 stop bits (or 1.5 for 5-bit words).
        #[must_use]
        #[inline(always)]
        pub const fn STB(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Stop Bits. 0 = 1 stop bit; 1 = 2 stop bits (or 1.5 for 5-bit words).
        #[inline(always)]
        pub const fn set_STB(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Parity Enable. 1 = enable parity generation/checking.
        #[must_use]
        #[inline(always)]
        pub const fn PEN(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Parity Enable. 1 = enable parity generation/checking.
        #[inline(always)]
        pub const fn set_PEN(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Even Parity Select (when PEN=1). 0 = odd parity; 1 = even parity.
        #[must_use]
        #[inline(always)]
        pub const fn EPS(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Even Parity Select (when PEN=1). 0 = odd parity; 1 = even parity.
        #[inline(always)]
        pub const fn set_EPS(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Stick Parity. 1 = parity bit forced to 0 (EPS=1) or 1 (EPS=0).
        #[must_use]
        #[inline(always)]
        pub const fn SP(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        ///Stick Parity. 1 = parity bit forced to 0 (EPS=1) or 1 (EPS=0).
        #[inline(always)]
        pub const fn set_SP(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        ///Break Control. 1 = force TX line to spacing (break) state.
        #[must_use]
        #[inline(always)]
        pub const fn BC(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        ///Break Control. 1 = force TX line to spacing (break) state.
        #[inline(always)]
        pub const fn set_BC(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        ///Divisor Latch Access Bit. 1 = offsets 0x00 and 0x04 address DLL/DLH (baud rate divisor); 0 = offsets 0x00 and 0x04 address RBR/THR and IER. Clear to 0 after configuring baud rate.
        #[must_use]
        #[inline(always)]
        pub const fn DLAB(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        ///Divisor Latch Access Bit. 1 = offsets 0x00 and 0x04 address DLL/DLH (baud rate divisor); 0 = offsets 0x00 and 0x04 address RBR/THR and IER. Clear to 0 after configuring baud rate.
        #[inline(always)]
        pub const fn set_DLAB(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
    }
    impl Default for LCR {
        #[inline(always)]
        fn default() -> LCR {
            LCR(0)
        }
    }
    impl core::fmt::Debug for LCR {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("LCR")
                .field("WLS", &self.WLS())
                .field("STB", &self.STB())
                .field("PEN", &self.PEN())
                .field("EPS", &self.EPS())
                .field("SP", &self.SP())
                .field("BC", &self.BC())
                .field("DLAB", &self.DLAB())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for LCR {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "LCR {{ WLS: {=u8:?}, STB: {=bool:?}, PEN: {=bool:?}, EPS: {=bool:?}, SP: {=bool:?}, BC: {=bool:?}, DLAB: {=bool:?} }}",
                self.WLS(), self.STB(), self.PEN(), self.EPS(), self.SP(), self.BC(),
                self.DLAB()
            )
        }
    }
    ///Line Status Register. Read-only status bits.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct LSR(pub u32);
    impl LSR {
        ///Data Ready. 1 = at least one character is in the RX buffer / RX FIFO.
        #[must_use]
        #[inline(always)]
        pub const fn DR(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Data Ready. 1 = at least one character is in the RX buffer / RX FIFO.
        #[inline(always)]
        pub const fn set_DR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Overrun Error. 1 = a new character arrived before the previous was read. Cleared by reading LSR.
        #[must_use]
        #[inline(always)]
        pub const fn OE(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Overrun Error. 1 = a new character arrived before the previous was read. Cleared by reading LSR.
        #[inline(always)]
        pub const fn set_OE(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Parity Error. 1 = received character has wrong parity. Cleared by reading LSR.
        #[must_use]
        #[inline(always)]
        pub const fn PE(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Parity Error. 1 = received character has wrong parity. Cleared by reading LSR.
        #[inline(always)]
        pub const fn set_PE(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Framing Error. 1 = received character has no valid stop bit. Cleared by reading LSR.
        #[must_use]
        #[inline(always)]
        pub const fn FE(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Framing Error. 1 = received character has no valid stop bit. Cleared by reading LSR.
        #[inline(always)]
        pub const fn set_FE(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Break Interrupt. 1 = RX line has been held at 0 (spacing) for more than one character time. Cleared by reading LSR.
        #[must_use]
        #[inline(always)]
        pub const fn BI(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Break Interrupt. 1 = RX line has been held at 0 (spacing) for more than one character time. Cleared by reading LSR.
        #[inline(always)]
        pub const fn set_BI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Transmitter Holding Register Empty. 1 = THR is empty; safe to write next byte (or FIFO below threshold).
        #[must_use]
        #[inline(always)]
        pub const fn THRE(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        ///Transmitter Holding Register Empty. 1 = THR is empty; safe to write next byte (or FIFO below threshold).
        #[inline(always)]
        pub const fn set_THRE(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        ///Transmitter Empty. 1 = both THR and transmitter shift register are empty.
        #[must_use]
        #[inline(always)]
        pub const fn TEMT(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        ///Transmitter Empty. 1 = both THR and transmitter shift register are empty.
        #[inline(always)]
        pub const fn set_TEMT(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        ///FIFO data error (FIFO mode only). 1 = at least one PE/FE/BI error is present in the RX FIFO. Cleared when the erroneous byte is read out.
        #[must_use]
        #[inline(always)]
        pub const fn FIFOERR(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        ///FIFO data error (FIFO mode only). 1 = at least one PE/FE/BI error is present in the RX FIFO. Cleared when the erroneous byte is read out.
        #[inline(always)]
        pub const fn set_FIFOERR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
    }
    impl Default for LSR {
        #[inline(always)]
        fn default() -> LSR {
            LSR(0)
        }
    }
    impl core::fmt::Debug for LSR {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("LSR")
                .field("DR", &self.DR())
                .field("OE", &self.OE())
                .field("PE", &self.PE())
                .field("FE", &self.FE())
                .field("BI", &self.BI())
                .field("THRE", &self.THRE())
                .field("TEMT", &self.TEMT())
                .field("FIFOERR", &self.FIFOERR())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for LSR {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "LSR {{ DR: {=bool:?}, OE: {=bool:?}, PE: {=bool:?}, FE: {=bool:?}, BI: {=bool:?}, THRE: {=bool:?}, TEMT: {=bool:?}, FIFOERR: {=bool:?} }}",
                self.DR(), self.OE(), self.PE(), self.FE(), self.BI(), self.THRE(), self
                .TEMT(), self.FIFOERR()
            )
        }
    }
    ///Modem Control Register.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct MCR(pub u32);
    impl MCR {
        ///Data Terminal Ready output (active-low nDTR pin).
        #[must_use]
        #[inline(always)]
        pub const fn DTR(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Data Terminal Ready output (active-low nDTR pin).
        #[inline(always)]
        pub const fn set_DTR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Request To Send output (active-low nRTS pin).
        #[must_use]
        #[inline(always)]
        pub const fn RTS(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Request To Send output (active-low nRTS pin).
        #[inline(always)]
        pub const fn set_RTS(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Output 1 (general-purpose output, active-low).
        #[must_use]
        #[inline(always)]
        pub const fn OUT1(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Output 1 (general-purpose output, active-low).
        #[inline(always)]
        pub const fn set_OUT1(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Output 2 (active-low). On PC hardware this gates the interrupt; on ASPEED UARTs it must be set to 1 to enable interrupts.
        #[must_use]
        #[inline(always)]
        pub const fn OUT2(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Output 2 (active-low). On PC hardware this gates the interrupt; on ASPEED UARTs it must be set to 1 to enable interrupts.
        #[inline(always)]
        pub const fn set_OUT2(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Internal loopback mode. 1 = TX connected to RX internally; modem lines looped.
        #[must_use]
        #[inline(always)]
        pub const fn LOOP(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Internal loopback mode. 1 = TX connected to RX internally; modem lines looped.
        #[inline(always)]
        pub const fn set_LOOP(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
    }
    impl Default for MCR {
        #[inline(always)]
        fn default() -> MCR {
            MCR(0)
        }
    }
    impl core::fmt::Debug for MCR {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("MCR")
                .field("DTR", &self.DTR())
                .field("RTS", &self.RTS())
                .field("OUT1", &self.OUT1())
                .field("OUT2", &self.OUT2())
                .field("LOOP", &self.LOOP())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for MCR {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "MCR {{ DTR: {=bool:?}, RTS: {=bool:?}, OUT1: {=bool:?}, OUT2: {=bool:?}, LOOP: {=bool:?} }}",
                self.DTR(), self.RTS(), self.OUT1(), self.OUT2(), self.LOOP()
            )
        }
    }
    ///Modem Status Register. CTS/DSR/RI/DCD change and current state.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct MSR(pub u32);
    impl MSR {
        ///Delta CTS – CTS changed since last MSR read.
        #[must_use]
        #[inline(always)]
        pub const fn DCTS(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///Delta CTS – CTS changed since last MSR read.
        #[inline(always)]
        pub const fn set_DCTS(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Delta DSR – DSR changed since last MSR read.
        #[must_use]
        #[inline(always)]
        pub const fn DDSR(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Delta DSR – DSR changed since last MSR read.
        #[inline(always)]
        pub const fn set_DDSR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Trailing Edge Ring Indicator – RI went from active to inactive.
        #[must_use]
        #[inline(always)]
        pub const fn TERI(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        ///Trailing Edge Ring Indicator – RI went from active to inactive.
        #[inline(always)]
        pub const fn set_TERI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        ///Delta DCD – DCD changed since last MSR read.
        #[must_use]
        #[inline(always)]
        pub const fn DDCD(&self) -> bool {
            let val = (self.0 >> 3usize) & 0x01;
            val != 0
        }
        ///Delta DCD – DCD changed since last MSR read.
        #[inline(always)]
        pub const fn set_DDCD(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize);
        }
        ///Clear To Send (complement of nCTS input).
        #[must_use]
        #[inline(always)]
        pub const fn CTS(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Clear To Send (complement of nCTS input).
        #[inline(always)]
        pub const fn set_CTS(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Data Set Ready (complement of nDSR input).
        #[must_use]
        #[inline(always)]
        pub const fn DSR(&self) -> bool {
            let val = (self.0 >> 5usize) & 0x01;
            val != 0
        }
        ///Data Set Ready (complement of nDSR input).
        #[inline(always)]
        pub const fn set_DSR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize);
        }
        ///Ring Indicator (complement of nRI input).
        #[must_use]
        #[inline(always)]
        pub const fn RI(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        ///Ring Indicator (complement of nRI input).
        #[inline(always)]
        pub const fn set_RI(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        ///Data Carrier Detect (complement of nDCD input).
        #[must_use]
        #[inline(always)]
        pub const fn DCD(&self) -> bool {
            let val = (self.0 >> 7usize) & 0x01;
            val != 0
        }
        ///Data Carrier Detect (complement of nDCD input).
        #[inline(always)]
        pub const fn set_DCD(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize);
        }
    }
    impl Default for MSR {
        #[inline(always)]
        fn default() -> MSR {
            MSR(0)
        }
    }
    impl core::fmt::Debug for MSR {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("MSR")
                .field("DCTS", &self.DCTS())
                .field("DDSR", &self.DDSR())
                .field("TERI", &self.TERI())
                .field("DDCD", &self.DDCD())
                .field("CTS", &self.CTS())
                .field("DSR", &self.DSR())
                .field("RI", &self.RI())
                .field("DCD", &self.DCD())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for MSR {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "MSR {{ DCTS: {=bool:?}, DDSR: {=bool:?}, TERI: {=bool:?}, DDCD: {=bool:?}, CTS: {=bool:?}, DSR: {=bool:?}, RI: {=bool:?}, DCD: {=bool:?} }}",
                self.DCTS(), self.DDSR(), self.TERI(), self.DDCD(), self.CTS(), self
                .DSR(), self.RI(), self.DCD()
            )
        }
    }
}
pub mod wdt_v1 {
    ///ASPEED Watchdog Timer register block (shared IP: AST2600, AST1060). AST2600 instance 0 base: 0x7E78_5000, stride: 0x40. AST1060 instance 0 base: 0x7E78_5000, stride: 0x80 (4 instances). Registers 0x00-0x28 are identical across both SoCs.
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct WDT {
        ptr: *mut u8,
    }
    unsafe impl Send for WDT {}
    unsafe impl Sync for WDT {}
    impl WDT {
        #[inline(always)]
        pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
            Self { ptr: ptr as _ }
        }
        #[inline(always)]
        pub const fn as_ptr(&self) -> *mut () {
            self.ptr as _
        }
        ///Counter Status Register (WDT00). Read-only. Current down-counter value in microseconds. Loaded from RELOAD on reset or restart (0x4755 write to RESTART). Counts down to 0 when WDT is enabled. Default / power-on value: 0x014F_B180 (~22 s).
        #[inline(always)]
        pub const fn STATUS(self) -> crate::common::Reg<WDT_COUNTER, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0usize) as _) }
        }
        ///Counter Reload Value Register (WDT04). Value loaded into STATUS on reset or when 0x4755 is written to the RESTART register. Units: microseconds. Default: 0x014F_B180 (~22 s).
        #[inline(always)]
        pub const fn RELOAD(self) -> crate::common::Reg<WDT_COUNTER, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x04usize) as _) }
        }
        ///Counter Restart Register (WDT08). Write-only trigger. Write 0x4755 to reload STATUS from RELOAD and restart the counter (provided CTRL.WDT_EN=1). Any other write value is ignored.
        #[inline(always)]
        pub const fn RESTART(self) -> crate::common::Reg<WDT_RESTART, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x08usize) as _) }
        }
        ///Control Register (WDT0C). Configures reset mode, interrupt, and enable. Default: 0x0010 (WDT_EN=0, RST_SYS=1 = SOC reset mode).
        #[inline(always)]
        pub const fn CTRL(self) -> crate::common::Reg<WDT_CTRL, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x0cusize) as _) }
        }
        ///Software Mode Reset Control Register (WDT24). Write 0xAEED_F123 to trigger an immediate software-mode SOC reset (after setting SW_RESET_MASK1 to select which blocks to reset). This bit clears automatically after reset.
        #[inline(always)]
        pub const fn SW_RESET_CTRL(
            self,
        ) -> crate::common::Reg<WDT_SW_RESET_CTRL, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x24usize) as _) }
        }
        ///Software Mode Reset Mask Register #1 (WDT28). Each bit enables the corresponding subsystem to be reset when SW_RESET_CTRL is triggered. Zephyr uses 0x3FFF_FF1 to reset most subsystems.
        #[inline(always)]
        pub const fn SW_RESET_MASK1(
            self,
        ) -> crate::common::Reg<WDT_SW_RESET_MASK1, crate::common::RW> {
            unsafe { crate::common::Reg::from_ptr(self.ptr.wrapping_add(0x28usize) as _) }
        }
    }
    ///32-bit counter / reload value (WDT00 and WDT04 share this layout).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct WDT_COUNTER(pub u32);
    impl WDT_COUNTER {
        ///Counter value in microseconds.
        #[must_use]
        #[inline(always)]
        pub const fn VALUE(&self) -> u32 {
            let val = (self.0 >> 0usize) & 0xffff_ffff;
            val as u32
        }
        ///Counter value in microseconds.
        #[inline(always)]
        pub const fn set_VALUE(&mut self, val: u32) {
            self.0 = (self.0 & !(0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize);
        }
    }
    impl Default for WDT_COUNTER {
        #[inline(always)]
        fn default() -> WDT_COUNTER {
            WDT_COUNTER(0)
        }
    }
    impl core::fmt::Debug for WDT_COUNTER {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("WDT_COUNTER")
                .field("VALUE", &self.VALUE())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for WDT_COUNTER {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "WDT_COUNTER {{ VALUE: {=u32:?} }}", self.VALUE())
        }
    }
    ///WDT Control Register (WDT0C).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct WDT_CTRL(pub u32);
    impl WDT_CTRL {
        ///WDT Enable. 0 = disabled (counter holds current value); 1 = enabled (counter counts down).
        #[must_use]
        #[inline(always)]
        pub const fn WDT_EN(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        ///WDT Enable. 0 = disabled (counter holds current value); 1 = enabled (counter counts down).
        #[inline(always)]
        pub const fn set_WDT_EN(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        ///Reset system after timeout. 0 = disabled; 1 = assert SoC / CPU reset when counter reaches 0. Must clear WDT10\[0\] before enabling this bit.
        #[must_use]
        #[inline(always)]
        pub const fn RST_SYS(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        ///Reset system after timeout. 0 = disabled; 1 = assert SoC / CPU reset when counter reaches 0. Must clear WDT10\[0\] before enabling this bit.
        #[inline(always)]
        pub const fn set_RST_SYS(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        ///Allow SOC-level reset to reset this WDT instance. 0 = only SRST# or full-chip reset can reset this WDT; 1 = SOC system reset also resets this WDT.
        #[must_use]
        #[inline(always)]
        pub const fn WDT_RESET_BY_SOC(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        ///Allow SOC-level reset to reset this WDT instance. 0 = only SRST# or full-chip reset can reset this WDT; 1 = SOC system reset also resets this WDT.
        #[inline(always)]
        pub const fn set_WDT_RESET_BY_SOC(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        ///Reset system mode (bits \[6:5\]). 00 = SOC system reset (gated by reset mask registers); 01 = Full chip reset; 1x = CPU/FMC only (firmware reboot, no peripheral reset).
        #[must_use]
        #[inline(always)]
        pub const fn RST_MODE(&self) -> u8 {
            let val = (self.0 >> 5usize) & 0x03;
            val as u8
        }
        ///Reset system mode (bits \[6:5\]). 00 = SOC system reset (gated by reset mask registers); 01 = Full chip reset; 1x = CPU/FMC only (firmware reboot, no peripheral reset).
        #[inline(always)]
        pub const fn set_RST_MODE(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 5usize)) | (((val as u32) & 0x03) << 5usize);
        }
        ///External signal enable after timeout. 1 = pulse generated on an external output pin.
        #[must_use]
        #[inline(always)]
        pub const fn WDT_EXT(&self) -> bool {
            let val = (self.0 >> 27usize) & 0x01;
            val != 0
        }
        ///External signal enable after timeout. 1 = pulse generated on an external output pin.
        #[inline(always)]
        pub const fn set_WDT_EXT(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize);
        }
        ///Interrupt before timeout. 1 = generate interrupt when counter reaches pre-timeout value (set in CTRL bits \[31:10\]).
        #[must_use]
        #[inline(always)]
        pub const fn WDT_INTR(&self) -> bool {
            let val = (self.0 >> 28usize) & 0x01;
            val != 0
        }
        ///Interrupt before timeout. 1 = generate interrupt when counter reaches pre-timeout value (set in CTRL bits \[31:10\]).
        #[inline(always)]
        pub const fn set_WDT_INTR(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize);
        }
    }
    impl Default for WDT_CTRL {
        #[inline(always)]
        fn default() -> WDT_CTRL {
            WDT_CTRL(0)
        }
    }
    impl core::fmt::Debug for WDT_CTRL {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("WDT_CTRL")
                .field("WDT_EN", &self.WDT_EN())
                .field("RST_SYS", &self.RST_SYS())
                .field("WDT_RESET_BY_SOC", &self.WDT_RESET_BY_SOC())
                .field("RST_MODE", &self.RST_MODE())
                .field("WDT_EXT", &self.WDT_EXT())
                .field("WDT_INTR", &self.WDT_INTR())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for WDT_CTRL {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "WDT_CTRL {{ WDT_EN: {=bool:?}, RST_SYS: {=bool:?}, WDT_RESET_BY_SOC: {=bool:?}, RST_MODE: {=u8:?}, WDT_EXT: {=bool:?}, WDT_INTR: {=bool:?} }}",
                self.WDT_EN(), self.RST_SYS(), self.WDT_RESET_BY_SOC(), self.RST_MODE(),
                self.WDT_EXT(), self.WDT_INTR()
            )
        }
    }
    ///Counter Restart Register (WDT08).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct WDT_RESTART(pub u32);
    impl WDT_RESTART {
        ///Write 0x4755 to reload and restart the counter. Read returns 0 (write-only hardware).
        #[must_use]
        #[inline(always)]
        pub const fn KEY(&self) -> u16 {
            let val = (self.0 >> 0usize) & 0xffff;
            val as u16
        }
        ///Write 0x4755 to reload and restart the counter. Read returns 0 (write-only hardware).
        #[inline(always)]
        pub const fn set_KEY(&mut self, val: u16) {
            self.0 = (self.0 & !(0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize);
        }
    }
    impl Default for WDT_RESTART {
        #[inline(always)]
        fn default() -> WDT_RESTART {
            WDT_RESTART(0)
        }
    }
    impl core::fmt::Debug for WDT_RESTART {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("WDT_RESTART")
                .field("KEY", &self.KEY())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for WDT_RESTART {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "WDT_RESTART {{ KEY: {=u16:?} }}", self.KEY())
        }
    }
    ///Software Mode Reset Control Register (WDT24).
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct WDT_SW_RESET_CTRL(pub u32);
    impl WDT_SW_RESET_CTRL {
        ///Write 0xAEEDF123 to fire a software-mode SOC reset immediately. After reset this bit clears to 0 automatically. Only SOC reset mode is supported for software-triggered resets.
        #[must_use]
        #[inline(always)]
        pub const fn TRIGGER(&self) -> u32 {
            let val = (self.0 >> 0usize) & 0xffff_ffff;
            val as u32
        }
        ///Write 0xAEEDF123 to fire a software-mode SOC reset immediately. After reset this bit clears to 0 automatically. Only SOC reset mode is supported for software-triggered resets.
        #[inline(always)]
        pub const fn set_TRIGGER(&mut self, val: u32) {
            self.0 = (self.0 & !(0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize);
        }
    }
    impl Default for WDT_SW_RESET_CTRL {
        #[inline(always)]
        fn default() -> WDT_SW_RESET_CTRL {
            WDT_SW_RESET_CTRL(0)
        }
    }
    impl core::fmt::Debug for WDT_SW_RESET_CTRL {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("WDT_SW_RESET_CTRL")
                .field("TRIGGER", &self.TRIGGER())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for WDT_SW_RESET_CTRL {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "WDT_SW_RESET_CTRL {{ TRIGGER: {=u32:?} }}",
                self.TRIGGER()
            )
        }
    }
    ///Software Mode Reset Mask Register #1 (WDT28). Each bit enables (1) or disables (0) the reset of the corresponding subsystem when SW_RESET_CTRL is triggered.
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct WDT_SW_RESET_MASK1(pub u32);
    impl WDT_SW_RESET_MASK1 {
        ///Subsystem reset enable bitmask. Zephyr sets 0x03FF_FFF1 to reset the standard set of subsystems (ARM, SDRAM, AHB bridges, coprocessor, SOC controllers, USB, etc.).
        #[must_use]
        #[inline(always)]
        pub const fn MASK(&self) -> u32 {
            let val = (self.0 >> 0usize) & 0xffff_ffff;
            val as u32
        }
        ///Subsystem reset enable bitmask. Zephyr sets 0x03FF_FFF1 to reset the standard set of subsystems (ARM, SDRAM, AHB bridges, coprocessor, SOC controllers, USB, etc.).
        #[inline(always)]
        pub const fn set_MASK(&mut self, val: u32) {
            self.0 = (self.0 & !(0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize);
        }
    }
    impl Default for WDT_SW_RESET_MASK1 {
        #[inline(always)]
        fn default() -> WDT_SW_RESET_MASK1 {
            WDT_SW_RESET_MASK1(0)
        }
    }
    impl core::fmt::Debug for WDT_SW_RESET_MASK1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("WDT_SW_RESET_MASK1")
                .field("MASK", &self.MASK())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for WDT_SW_RESET_MASK1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "WDT_SW_RESET_MASK1 {{ MASK: {=u32:?} }}", self.MASK())
        }
    }
}
