// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// ClockAst1060V1SCU AST1060 System Control Unit (SCU). Base: 0x7E6E_2000. Protection key: write 0x1688A8A8 to SCU000. Controls clock gating, resets, H-PLL, PCLK divider, and CM4F memory map.
type ClockAst1060V1SCU struct {
    Base uintptr
}

// ReadPROTKEY reads Protection key register (SCU000). Write 0x1688A8A8 to unlock all SCU registers. Write any other value to lock. Readback: 1=unlocked, 0=locked.
func (p *ClockAst1060V1SCU) ReadPROTKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WritePROTKEY writes Protection key register (SCU000). Write 0x1688A8A8 to unlock all SCU registers. Write any other value to lock. Readback: 1=unlocked, 0=locked.
func (p *ClockAst1060V1SCU) WritePROTKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadSILICONREV reads Silicon revision ID (SCU004). Read-only. AST1060-A1: 0xA0010000. AST1060-A2: 0xA0030000.
func (p *ClockAst1060V1SCU) ReadSILICONREV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteSILICONREV writes Silicon revision ID (SCU004). Read-only. AST1060-A1: 0xA0010000. AST1060-A2: 0xA0030000.
func (p *ClockAst1060V1SCU) WriteSILICONREV(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadPROTKEY2 reads Protection key register 2 (SCU010). Identical to SCU000. Dual-key structure — both keys must be written to unlock.
func (p *ClockAst1060V1SCU) ReadPROTKEY2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WritePROTKEY2 writes Protection key register 2 (SCU010). Identical to SCU000. Dual-key structure — both keys must be written to unlock.
func (p *ClockAst1060V1SCU) WritePROTKEY2(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadSILICONREV2 reads Silicon revision ID 2 (SCU014). Identical to SCU004.
func (p *ClockAst1060V1SCU) ReadSILICONREV2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteSILICONREV2 writes Silicon revision ID 2 (SCU014). Identical to SCU004.
func (p *ClockAst1060V1SCU) WriteSILICONREV2(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadRESETCTRL1SET reads Module reset control set 1 (SCU040). RW1S: write 1 to assert reset. Write 1 to SCU044 to deassert. Main functional bit: bit 0 (SRAM controller). Keep all other bits at reset value (most are reserved=1).
func (p *ClockAst1060V1SCU) ReadRESETCTRL1SET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteRESETCTRL1SET writes Module reset control set 1 (SCU040). RW1S: write 1 to assert reset. Write 1 to SCU044 to deassert. Main functional bit: bit 0 (SRAM controller). Keep all other bits at reset value (most are reserved=1).
func (p *ClockAst1060V1SCU) WriteRESETCTRL1SET(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadRESETCTRL1CLR reads Module reset control clear 1 (SCU044). Write 1 to deassert corresponding SCU040 reset.
func (p *ClockAst1060V1SCU) ReadRESETCTRL1CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteRESETCTRL1CLR writes Module reset control clear 1 (SCU044). Write 1 to deassert corresponding SCU040 reset.
func (p *ClockAst1060V1SCU) WriteRESETCTRL1CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadRESETCTRL2SET reads Module reset control set 2 (SCU050). RW1S. Key bits: I3C0-3 (bits 8-11), I3C DMA (bit 7), I2C/SMBus (bit 2), ADC (bit 23), JTAG1 (bit 26), UART1-4 (bits 28-31). 0=running, 1=held in reset (default for most peripherals).
func (p *ClockAst1060V1SCU) ReadRESETCTRL2SET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteRESETCTRL2SET writes Module reset control set 2 (SCU050). RW1S. Key bits: I3C0-3 (bits 8-11), I3C DMA (bit 7), I2C/SMBus (bit 2), ADC (bit 23), JTAG1 (bit 26), UART1-4 (bits 28-31). 0=running, 1=held in reset (default for most peripherals).
func (p *ClockAst1060V1SCU) WriteRESETCTRL2SET(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadRESETCTRL2CLR reads Module reset control clear 2 (SCU054). Write 1 to deassert corresponding SCU050 reset.
func (p *ClockAst1060V1SCU) ReadRESETCTRL2CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteRESETCTRL2CLR writes Module reset control clear 2 (SCU054). Write 1 to deassert corresponding SCU050 reset.
func (p *ClockAst1060V1SCU) WriteRESETCTRL2CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadRAW060 reads SCU register at offset 0x060.
func (p *ClockAst1060V1SCU) ReadRAW060() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteRAW060 writes SCU register at offset 0x060.
func (p *ClockAst1060V1SCU) WriteRAW060(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadRAW070 reads SCU register at offset 0x070.
func (p *ClockAst1060V1SCU) ReadRAW070() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteRAW070 writes SCU register at offset 0x070.
func (p *ClockAst1060V1SCU) WriteRAW070(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadRAW074 reads SCU register at offset 0x074.
func (p *ClockAst1060V1SCU) ReadRAW074() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteRAW074 writes SCU register at offset 0x074.
func (p *ClockAst1060V1SCU) WriteRAW074(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadRAW078 reads SCU register at offset 0x078.
func (p *ClockAst1060V1SCU) ReadRAW078() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteRAW078 writes SCU register at offset 0x078.
func (p *ClockAst1060V1SCU) WriteRAW078(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadCLKSTOP1SET reads Clock stop control set 1 (SCU080). RW1S: write 1 to STOP a clock. Write 1 to SCU084 to un-stop (enable) a clock. Init: 0xFFFF7F8A — most bits reserved=1 (pre-stopped). Functional bits: [13]=HACE YCLK (stopped by default), [0]=SRAM MCLK (running).
func (p *ClockAst1060V1SCU) ReadCLKSTOP1SET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteCLKSTOP1SET writes Clock stop control set 1 (SCU080). RW1S: write 1 to STOP a clock. Write 1 to SCU084 to un-stop (enable) a clock. Init: 0xFFFF7F8A — most bits reserved=1 (pre-stopped). Functional bits: [13]=HACE YCLK (stopped by default), [0]=SRAM MCLK (running).
func (p *ClockAst1060V1SCU) WriteCLKSTOP1SET(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadCLKSTOP1CLR reads Clock stop control clear 1 (SCU084). Write 1 to un-stop (enable) a clock. Mirrors SCU080 bit positions.
func (p *ClockAst1060V1SCU) ReadCLKSTOP1CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteCLKSTOP1CLR writes Clock stop control clear 1 (SCU084). Write 1 to un-stop (enable) a clock. Mirrors SCU080 bit positions.
func (p *ClockAst1060V1SCU) WriteCLKSTOP1CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadCLKSTOP2SET reads Clock stop control set 2 (SCU090). RW1S. Init: 0xFFF0FFF0 — most bits reserved=1. Functional bits: [11]=I3C3CLK, [10]=I3C2CLK, [9]=I3C1CLK, [8]=I3C0CLK, [6]=RSA/ECC clock, [2]=REFCLK (all stopped by default except REFCLK).
func (p *ClockAst1060V1SCU) ReadCLKSTOP2SET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteCLKSTOP2SET writes Clock stop control set 2 (SCU090). RW1S. Init: 0xFFF0FFF0 — most bits reserved=1. Functional bits: [11]=I3C3CLK, [10]=I3C2CLK, [9]=I3C1CLK, [8]=I3C0CLK, [6]=RSA/ECC clock, [2]=REFCLK (all stopped by default except REFCLK).
func (p *ClockAst1060V1SCU) WriteCLKSTOP2SET(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadCLKSTOP2CLR reads Clock stop control clear 2 (SCU094). Write 1 to un-stop a clock.
func (p *ClockAst1060V1SCU) ReadCLKSTOP2CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteCLKSTOP2CLR writes Clock stop control clear 2 (SCU094). Write 1 to un-stop a clock.
func (p *ClockAst1060V1SCU) WriteCLKSTOP2CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadRAW0D0 reads SCU register range 0x0D0-0x0D8.[n] (n < 3)
func (p *ClockAst1060V1SCU) ReadRAW0D0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0 + uint32(n)*4))
}

// WriteRAW0D0 writes SCU register range 0x0D0-0x0D8.[n] (n < 3)
func (p *ClockAst1060V1SCU) WriteRAW0D0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x00d0+uint32(n)*4, uint32(val))
}

// ReadRAW0F0 reads SCU register at offset 0x0F0.
func (p *ClockAst1060V1SCU) ReadRAW0F0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f0))
}

// WriteRAW0F0 writes SCU register at offset 0x0F0.
func (p *ClockAst1060V1SCU) WriteRAW0F0(val uint32) {
    reg.Write(uint32(p.Base)+0x00f0, uint32(val))
}

// ReadHPLLPARAM reads H-PLL parameter register (SCU200). Output frequency = CLKIN(25 MHz) × (M+1) / (N+1) / (P+1). Default: M=0x77(119), N=2, P=0 → 25 × 120/3/1 = 1000 MHz.
func (p *ClockAst1060V1SCU) ReadHPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// WriteHPLLPARAM writes H-PLL parameter register (SCU200). Output frequency = CLKIN(25 MHz) × (M+1) / (N+1) / (P+1). Default: M=0x77(119), N=2, P=0 → 25 × 120/3/1 = 1000 MHz.
func (p *ClockAst1060V1SCU) WriteHPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0200, uint32(val))
}

// ReadHPLLEXT reads H-PLL extended parameter (SCU204). Bandwidth adjustment: NB = BWADJ + 1. Default 0x31=49 → NB=50. Recommended: NB = (M+1)/2.
func (p *ClockAst1060V1SCU) ReadHPLLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// WriteHPLLEXT writes H-PLL extended parameter (SCU204). Bandwidth adjustment: NB = BWADJ + 1. Default 0x31=49 → NB=50. Recommended: NB = (M+1)/2.
func (p *ClockAst1060V1SCU) WriteHPLLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x0204, uint32(val))
}

// ReadCLKSEL4 reads Clock selection register 4 (SCU310). PCLK divider: bits[11:8] — 0=HPLL/2 (default), 1=HPLL/4, ..., 15=HPLL/32. UART5 clock: bit[4] — 0=24 MHz/13 ≈ 1.846 MHz, 1=192 MHz/13 ≈ 14.769 MHz. I3C clock source: bit[31] — 0=HPLL, 1=480 MHz. I3C clock divider: bits[30:28] — ÷2 to ÷8 (100=÷5 default).
func (p *ClockAst1060V1SCU) ReadCLKSEL4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0310))
}

// WriteCLKSEL4 writes Clock selection register 4 (SCU310). PCLK divider: bits[11:8] — 0=HPLL/2 (default), 1=HPLL/4, ..., 15=HPLL/32. UART5 clock: bit[4] — 0=24 MHz/13 ≈ 1.846 MHz, 1=192 MHz/13 ≈ 14.769 MHz. I3C clock source: bit[31] — 0=HPLL, 1=480 MHz. I3C clock divider: bits[30:28] — ÷2 to ÷8 (100=÷5 default).
func (p *ClockAst1060V1SCU) WriteCLKSEL4(val uint32) {
    reg.Write(uint32(p.Base)+0x0310, uint32(val))
}

// ReadRAW314 reads SCU register at offset 0x314.
func (p *ClockAst1060V1SCU) ReadRAW314() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0314))
}

// WriteRAW314 writes SCU register at offset 0x314.
func (p *ClockAst1060V1SCU) WriteRAW314(val uint32) {
    reg.Write(uint32(p.Base)+0x0314, uint32(val))
}

// ReadRAW330 reads SCU register range 0x330-0x37C.[n] (n < 20)
func (p *ClockAst1060V1SCU) ReadRAW330(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0330 + uint32(n)*4))
}

// WriteRAW330 writes SCU register range 0x330-0x37C.[n] (n < 20)
func (p *ClockAst1060V1SCU) WriteRAW330(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0330+uint32(n)*4, uint32(val))
}

// ReadRAW410 reads SCU register range 0x410-0x6D4.[n] (n < 178)
func (p *ClockAst1060V1SCU) ReadRAW410(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0410 + uint32(n)*4))
}

// WriteRAW410 writes SCU register range 0x410-0x6D4.[n] (n < 178)
func (p *ClockAst1060V1SCU) WriteRAW410(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0410+uint32(n)*4, uint32(val))
}

// ReadCM4FMEMBASE reads CM4F memory base address register (SCUA14). Configures the physical base address of the CM4F's SRAM window. Can only be changed while CM4F is in reset (SCU050[RST_bit]=1). Default 0x00000000 (SRAM at physical 0x0).
func (p *ClockAst1060V1SCU) ReadCM4FMEMBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a14))
}

// WriteCM4FMEMBASE writes CM4F memory base address register (SCUA14). Configures the physical base address of the CM4F's SRAM window. Can only be changed while CM4F is in reset (SCU050[RST_bit]=1). Default 0x00000000 (SRAM at physical 0x0).
func (p *ClockAst1060V1SCU) WriteCM4FMEMBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0a14, uint32(val))
}

// ReadCM4FIMEMLIMIT reads CM4F instruction memory address limit register (SCUA18). Upper bound of the instruction fetch window. Default 0x20000000.
func (p *ClockAst1060V1SCU) ReadCM4FIMEMLIMIT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a18))
}

// WriteCM4FIMEMLIMIT writes CM4F instruction memory address limit register (SCUA18). Upper bound of the instruction fetch window. Default 0x20000000.
func (p *ClockAst1060V1SCU) WriteCM4FIMEMLIMIT(val uint32) {
    reg.Write(uint32(p.Base)+0x0a18, uint32(val))
}

// ReadCM4FDMEMLIMIT reads CM4F data memory address limit register (SCUA1C). Upper bound of the data access window. Default 0x20000000.
func (p *ClockAst1060V1SCU) ReadCM4FDMEMLIMIT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a1c))
}

// WriteCM4FDMEMLIMIT writes CM4F data memory address limit register (SCUA1C). Upper bound of the data access window. Default 0x20000000.
func (p *ClockAst1060V1SCU) WriteCM4FDMEMLIMIT(val uint32) {
    reg.Write(uint32(p.Base)+0x0a1c, uint32(val))
}

// ReadCM4FCACHEAREA reads CM4F cacheable area declaration (SCUA50). Bit N=1: the 32 MB region starting at base + N×32 MB is cacheable. Default 0xFFFFFFFF (all regions cacheable).
func (p *ClockAst1060V1SCU) ReadCM4FCACHEAREA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a50))
}

// WriteCM4FCACHEAREA writes CM4F cacheable area declaration (SCUA50). Bit N=1: the 32 MB region starting at base + N×32 MB is cacheable. Default 0xFFFFFFFF (all regions cacheable).
func (p *ClockAst1060V1SCU) WriteCM4FCACHEAREA(val uint32) {
    reg.Write(uint32(p.Base)+0x0a50, uint32(val))
}

// ReadCM4FCACHEINVAL reads CM4F cache invalidation control (SCUA54). Write to trigger cache invalidation.
func (p *ClockAst1060V1SCU) ReadCM4FCACHEINVAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a54))
}

// WriteCM4FCACHEINVAL writes CM4F cache invalidation control (SCUA54). Write to trigger cache invalidation.
func (p *ClockAst1060V1SCU) WriteCM4FCACHEINVAL(val uint32) {
    reg.Write(uint32(p.Base)+0x0a54, uint32(val))
}

// ReadCM4FCACHEFUNC reads CM4F cache function control register (SCUA58). Bit[0]=cache enable (I+D combined). Default 0x1 (cache enabled).
func (p *ClockAst1060V1SCU) ReadCM4FCACHEFUNC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0a58))
}

// WriteCM4FCACHEFUNC writes CM4F cache function control register (SCUA58). Bit[0]=cache enable (I+D combined). Default 0x1 (cache enabled).
func (p *ClockAst1060V1SCU) WriteCM4FCACHEFUNC(val uint32) {
    reg.Write(uint32(p.Base)+0x0a58, uint32(val))
}

// ReadRAWF00 reads SCU register range 0xF00-0xFFC.[n] (n < 64)
func (p *ClockAst1060V1SCU) ReadRAWF00(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0f00 + uint32(n)*4))
}

// WriteRAWF00 writes SCU register range 0xF00-0xFFC.[n] (n < 64)
func (p *ClockAst1060V1SCU) WriteRAWF00(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0f00+uint32(n)*4, uint32(val))
}

