// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// I2cfilterV1SMBUSFILTER ASPEED SMBus/I2C PFR Filter — per-instance registers. Instance N base address: 0x7E7B_2200 + N * 0x100. Program BUF with the physical SRAM address of the whitelist bitmap before setting EN or CFG.
type I2cfilterV1SMBUSFILTER struct {
    Base uintptr
}

// ReadEN reads Filter enable (offset 0x04). Write 1 to enable filtering on this I2C bus. Write 0 to disable (pass all transactions).
func (p *I2cfilterV1SMBUSFILTER) ReadEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteEN writes Filter enable (offset 0x04). Write 1 to enable filtering on this I2C bus. Write 0 to disable (pass all transactions).
func (p *I2cfilterV1SMBUSFILTER) WriteEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadBUF reads Whitelist buffer physical address (offset 0x08). Must point to a 16-byte-aligned, DMA-accessible SRAM region holding the ast_i2c_f_tbl structure (17 × 32-byte bitmaps). Write before setting CFG.
func (p *I2cfilterV1SMBUSFILTER) ReadBUF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteBUF writes Whitelist buffer physical address (offset 0x08). Must point to a 16-byte-aligned, DMA-accessible SRAM region holding the ast_i2c_f_tbl structure (17 × 32-byte bitmaps). Write before setting CFG.
func (p *I2cfilterV1SMBUSFILTER) WriteBUF(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCFG reads Filter config / whitelist enable (offset 0x0C). Write 1 to activate address whitelist (requires BUF set first). Write 0 to disable address filtering (block/pass all determined by default bitmap entry [0]).
func (p *I2cfilterV1SMBUSFILTER) ReadCFG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCFG writes Filter config / whitelist enable (offset 0x0C). Write 1 to activate address whitelist (requires BUF set first). Write 0 to disable address filtering (block/pass all determined by default bitmap entry [0]).
func (p *I2cfilterV1SMBUSFILTER) WriteCFG(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadTIMING reads Timeout timing (offset 0x10). Both halves [31:16] and [15:0] must hold the same count value:
//   count = PCLK_Hz / (i2c_kHz * 3 * 1000).
// At 100 MHz PCLK and 100 kHz I2C: count ≈ 333 (0x14D). Register value = (count << 16) | count.
func (p *I2cfilterV1SMBUSFILTER) ReadTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteTIMING writes Timeout timing (offset 0x10). Both halves [31:16] and [15:0] must hold the same count value:
//   count = PCLK_Hz / (i2c_kHz * 3 * 1000).
// At 100 MHz PCLK and 100 kHz I2C: count ≈ 333 (0x14D). Register value = (count << 16) | count.
func (p *I2cfilterV1SMBUSFILTER) WriteTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadINTEN reads Local interrupt enable (offset 0x14). Write 1 to enable interrupt for this instance.
func (p *I2cfilterV1SMBUSFILTER) ReadINTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteINTEN writes Local interrupt enable (offset 0x14). Write 1 to enable interrupt for this instance.
func (p *I2cfilterV1SMBUSFILTER) WriteINTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadINTSTS reads Local interrupt status (offset 0x18, write 1 to clear).
func (p *I2cfilterV1SMBUSFILTER) ReadINTSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteINTSTS writes Local interrupt status (offset 0x18, write 1 to clear).
func (p *I2cfilterV1SMBUSFILTER) WriteINTSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadSTS reads Status register (offset 0x20, read-only). Includes FIFO status and read/write pointers.
func (p *I2cfilterV1SMBUSFILTER) ReadSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteSTS writes Status register (offset 0x20, read-only). Includes FIFO status and read/write pointers.
func (p *I2cfilterV1SMBUSFILTER) WriteSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadSEQ reads Received sequence value register.
func (p *I2cfilterV1SMBUSFILTER) ReadSEQ() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteSEQ writes Received sequence value register.
func (p *I2cfilterV1SMBUSFILTER) WriteSEQ(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadMAP0 reads Address re-map table, slots 0–3 (offset 0x40). Each byte is a 7-bit target address for the corresponding whitelist bitmap slot (slot 0 = byte[7:0], slot 3 = byte[31:24]).
func (p *I2cfilterV1SMBUSFILTER) ReadMAP0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteMAP0 writes Address re-map table, slots 0–3 (offset 0x40). Each byte is a 7-bit target address for the corresponding whitelist bitmap slot (slot 0 = byte[7:0], slot 3 = byte[31:24]).
func (p *I2cfilterV1SMBUSFILTER) WriteMAP0(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadMAP1 reads Address re-map table, slots 4–7 (offset 0x44).
func (p *I2cfilterV1SMBUSFILTER) ReadMAP1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteMAP1 writes Address re-map table, slots 4–7 (offset 0x44).
func (p *I2cfilterV1SMBUSFILTER) WriteMAP1(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadMAP2 reads Address re-map table, slots 8–11 (offset 0x48).
func (p *I2cfilterV1SMBUSFILTER) ReadMAP2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteMAP2 writes Address re-map table, slots 8–11 (offset 0x48).
func (p *I2cfilterV1SMBUSFILTER) WriteMAP2(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadMAP3 reads Address re-map table, slots 12–15 (offset 0x4C).
func (p *I2cfilterV1SMBUSFILTER) ReadMAP3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteMAP3 writes Address re-map table, slots 12–15 (offset 0x4C).
func (p *I2cfilterV1SMBUSFILTER) WriteMAP3(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadINFO reads Blocked-transaction info FIFO read port (offset 0x60, read-only). Each read pops one 32-bit entry from the FIFO describing a blocked transaction (address, direction, data bytes).
func (p *I2cfilterV1SMBUSFILTER) ReadINFO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteINFO writes Blocked-transaction info FIFO read port (offset 0x60, read-only). Each read pops one 32-bit entry from the FIFO describing a blocked transaction (address, direction, data bytes).
func (p *I2cfilterV1SMBUSFILTER) WriteINFO(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

