// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// I2cfilterV1SMBUSFILTERGLOBAL ASPEED SMBus/I2C PFR Filter — global interrupt registers. Base: 0x7E7B_2000 (AST1060). Contains one interrupt-enable bit and one interrupt-status bit per filter instance (bit N = instance N).
type I2cfilterV1SMBUSFILTERGLOBAL struct {
    Base uintptr
}

// ReadGLOBALINTEN reads Global per-instance interrupt enable (offset 0x08). Bit N enables the interrupt from filter instance N.
func (p *I2cfilterV1SMBUSFILTERGLOBAL) ReadGLOBALINTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteGLOBALINTEN writes Global per-instance interrupt enable (offset 0x08). Bit N enables the interrupt from filter instance N.
func (p *I2cfilterV1SMBUSFILTERGLOBAL) WriteGLOBALINTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadGLOBALINTSTS reads Global per-instance interrupt status (offset 0x0C, write 1 to clear). Bit N is set when filter instance N raises an interrupt.
func (p *I2cfilterV1SMBUSFILTERGLOBAL) ReadGLOBALINTSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteGLOBALINTSTS writes Global per-instance interrupt status (offset 0x0C, write 1 to clear). Bit N is set when filter instance N raises an interrupt.
func (p *I2cfilterV1SMBUSFILTERGLOBAL) WriteGLOBALINTSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

