// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// Ipc0V1CHAN One half (TX or RX) of an IPC0 sub-channel. Each half supports four message IDs with a 32-byte payload per ID.
type Ipc0V1CHAN struct {
    Base uintptr
}

// ReadTRIG reads Message trigger register. Write bit n to dispatch message ID n.
func (p *Ipc0V1CHAN) ReadTRIG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteTRIG writes Message trigger register. Write bit n to dispatch message ID n.
func (p *Ipc0V1CHAN) WriteTRIG(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadENABLE reads Per-ID receive enable mask.
func (p *Ipc0V1CHAN) ReadENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteENABLE writes Per-ID receive enable mask.
func (p *Ipc0V1CHAN) WriteENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadSTATUS reads Pending message status. Write bit n to acknowledge message ID n.
func (p *Ipc0V1CHAN) ReadSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteSTATUS writes Pending message status. Write bit n to acknowledge message ID n.
func (p *Ipc0V1CHAN) WriteSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadDATA0 reads 32-byte payload for message ID 0.[n] (n < 8)
func (p *Ipc0V1CHAN) ReadDATA0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010 + uint32(n)*4))
}

// WriteDATA0 writes 32-byte payload for message ID 0.[n] (n < 8)
func (p *Ipc0V1CHAN) WriteDATA0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0010+uint32(n)*4, uint32(val))
}

// ReadDATA1 reads 32-byte payload for message ID 1.[n] (n < 8)
func (p *Ipc0V1CHAN) ReadDATA1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030 + uint32(n)*4))
}

// WriteDATA1 writes 32-byte payload for message ID 1.[n] (n < 8)
func (p *Ipc0V1CHAN) WriteDATA1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0030+uint32(n)*4, uint32(val))
}

// ReadDATA2 reads 32-byte payload for message ID 2.[n] (n < 8)
func (p *Ipc0V1CHAN) ReadDATA2(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050 + uint32(n)*4))
}

// WriteDATA2 writes 32-byte payload for message ID 2.[n] (n < 8)
func (p *Ipc0V1CHAN) WriteDATA2(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0050+uint32(n)*4, uint32(val))
}

// ReadDATA3 reads 32-byte payload for message ID 3.[n] (n < 8)
func (p *Ipc0V1CHAN) ReadDATA3(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070 + uint32(n)*4))
}

// WriteDATA3 writes 32-byte payload for message ID 3.[n] (n < 8)
func (p *Ipc0V1CHAN) WriteDATA3(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0070+uint32(n)*4, uint32(val))
}

