// Code generated by chiptool; DO NOT EDIT.

package pac

// Ipc0V1IPC0 AST2700 IPC0 bus: five data-channel sub-channels at stride 0x200.
type Ipc0V1IPC0 struct {
    Base uintptr
}

// CH returns Sub-channels 0-4 at 0x200-byte stride.[n] (n < 5)
func (p *Ipc0V1IPC0) CH(n uintptr) Ipc0V1SUBCHAN {
    return Ipc0V1SUBCHAN{Base: p.Base + 0x0000 + n*512}
}

