// Code generated by chiptool; DO NOT EDIT.

package pac

// Peripheral base addresses
const (
    // PWM_TACH_BASE PWM and fan tachometer controller
    PWM_TACH_BASE = 0x7e610000
    // FMC_BASE Firmware Memory Controller
    FMC_BASE = 0x7e620000
    // SPI1_BASE SPI Flash Controller 1
    SPI1_BASE = 0x7e630000
    // SPI2_BASE SPI Flash Controller 2
    SPI2_BASE = 0x7e640000
    // HACE_BASE Hash and Crypto Engine
    HACE_BASE = 0x7e6d0000
    // ADC_BASE ADC controller
    ADC_BASE = 0x7e6e9000
    // SECURE_BASE Secure Boot Controller and OTP engine
    SECURE_BASE = 0x7e6f2000
    // SGPIO_BASE Serial GPIO Master
    SGPIO_BASE = 0x7e780500
    // TIMER_BASE 8-channel 32-bit countdown timer
    TIMER_BASE = 0x7e782000
    // UART1_BASE UART1 16550-compatible controller
    UART1_BASE = 0x7e783000
    // UART5_BASE UART5 16550-compatible controller
    UART5_BASE = 0x7e784000
    // UART2_BASE UART2 16550-compatible controller
    UART2_BASE = 0x7e78d000
    // UART3_BASE UART3 16550-compatible controller
    UART3_BASE = 0x7e78e000
    // UART4_BASE UART4 16550-compatible controller
    UART4_BASE = 0x7e78f000
    // PECI_BASE PECI controller
    PECI_BASE = 0x7e78b000
    // UART6_BASE UART6 16550-compatible controller
    UART6_BASE = 0x7e790000
    // UART7_BASE UART7 16550-compatible controller
    UART7_BASE = 0x7e790100
    // UART8_BASE UART8 16550-compatible controller
    UART8_BASE = 0x7e790200
    // UART9_BASE UART9 16550-compatible controller
    UART9_BASE = 0x7e790300
    // UART10_BASE UART10 16550-compatible controller
    UART10_BASE = 0x7e790400
    // UART11_BASE UART11 16550-compatible controller
    UART11_BASE = 0x7e790500
    // UART12_BASE UART12 16550-compatible controller
    UART12_BASE = 0x7e790600
    // UART13_BASE UART13 16550-compatible controller
    UART13_BASE = 0x7e790700
    // UART_DMA_BASE UART DMA controller
    UART_DMA_BASE = 0x7e79e000
    // I3C_GLOBAL_BASE I3C global controller
    I3C_GLOBAL_BASE = 0x7e7a0000
    // I3C0_BASE I3C0
    I3C0_BASE = 0x7e7a2000
    // I3C1_BASE I3C1
    I3C1_BASE = 0x7e7a3000
    // I3C2_BASE I3C2
    I3C2_BASE = 0x7e7a4000
    // I3C3_BASE I3C3
    I3C3_BASE = 0x7e7a5000
    // I2C_GLOBAL_BASE I2C/SMBus global interrupt and clock controller
    I2C_GLOBAL_BASE = 0x7e7b0000
    // I2C0_BASE I2C0
    I2C0_BASE = 0x7e7b0080
    // I2C1_BASE I2C1
    I2C1_BASE = 0x7e7b0100
    // I2C2_BASE I2C2
    I2C2_BASE = 0x7e7b0180
    // I2C3_BASE I2C3
    I2C3_BASE = 0x7e7b0200
    // I2C4_BASE I2C4
    I2C4_BASE = 0x7e7b0280
    // I2C5_BASE I2C5
    I2C5_BASE = 0x7e7b0300
    // I2C6_BASE I2C6
    I2C6_BASE = 0x7e7b0380
    // I2C7_BASE I2C7
    I2C7_BASE = 0x7e7b0400
    // I2C8_BASE I2C8
    I2C8_BASE = 0x7e7b0480
    // I2C9_BASE I2C9
    I2C9_BASE = 0x7e7b0500
    // I2C10_BASE I2C10
    I2C10_BASE = 0x7e7b0580
    // I2C11_BASE I2C11
    I2C11_BASE = 0x7e7b0600
    // I2C12_BASE I2C12
    I2C12_BASE = 0x7e7b0680
    // I2C13_BASE I2C13
    I2C13_BASE = 0x7e7b0700
    // I2C0_BUF_BASE I2C0_BUF
    I2C0_BUF_BASE = 0x7e7b0c00
    // I2C1_BUF_BASE I2C1_BUF
    I2C1_BUF_BASE = 0x7e7b0c20
    // I2C2_BUF_BASE I2C2_BUF
    I2C2_BUF_BASE = 0x7e7b0c40
    // I2C3_BUF_BASE I2C3_BUF
    I2C3_BUF_BASE = 0x7e7b0c60
    // I2C4_BUF_BASE I2C4_BUF
    I2C4_BUF_BASE = 0x7e7b0c80
    // I2C5_BUF_BASE I2C5_BUF
    I2C5_BUF_BASE = 0x7e7b0ca0
    // I2C6_BUF_BASE I2C6_BUF
    I2C6_BUF_BASE = 0x7e7b0cc0
    // I2C7_BUF_BASE I2C7_BUF
    I2C7_BUF_BASE = 0x7e7b0ce0
    // I2C8_BUF_BASE I2C8_BUF
    I2C8_BUF_BASE = 0x7e7b0d00
    // I2C9_BUF_BASE I2C9_BUF
    I2C9_BUF_BASE = 0x7e7b0d20
    // I2C10_BUF_BASE I2C10_BUF
    I2C10_BUF_BASE = 0x7e7b0d40
    // I2C11_BUF_BASE I2C11_BUF
    I2C11_BUF_BASE = 0x7e7b0d60
    // I2C12_BUF_BASE I2C12_BUF
    I2C12_BUF_BASE = 0x7e7b0d80
    // I2C13_BUF_BASE I2C13_BUF
    I2C13_BUF_BASE = 0x7e7b0da0
    // WDT1_BASE WDT1
    WDT1_BASE = 0x7e785000
    // WDT2_BASE WDT2
    WDT2_BASE = 0x7e785080
    // WDT3_BASE WDT3
    WDT3_BASE = 0x7e785100
    // WDT4_BASE WDT4
    WDT4_BASE = 0x7e785180
)

