// Code generated by chiptool; DO NOT EDIT.

package pac

import "src.kyanite.computer/aspeed-go/reg"

// PeciV1PECI ASPEED PECI controller.  Implements the Platform Environment Control Interface (PECI) single-wire host protocol for reading Intel CPU telemetry. Base: 0x7E78_B000 (AST2600, CM3 view).
type PeciV1PECI struct {
    Base uintptr
}

// ReadCTRL reads PECI Control Register (PECI00, offset 0x00). Main control: enable PECI engine, clock source, clock divider, input/output signal inversion, bus contention detection.
func (p *PeciV1PECI) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCTRL writes PECI Control Register (PECI00, offset 0x00). Main control: enable PECI engine, clock source, clock divider, input/output signal inversion, bus contention detection.
func (p *PeciV1PECI) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadTIMINGNEG reads PECI Timing Negotiation Register (PECI04, offset 0x04). Sets T_NEGO_MSG (message timing) and T_NEGO_ADDR (address timing) in units of PECI clock cycles.  Both are negotiated with the target.
func (p *PeciV1PECI) ReadTIMINGNEG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteTIMINGNEG writes PECI Timing Negotiation Register (PECI04, offset 0x04). Sets T_NEGO_MSG (message timing) and T_NEGO_ADDR (address timing) in units of PECI clock cycles.  Both are negotiated with the target.
func (p *PeciV1PECI) WriteTIMINGNEG(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCMD reads PECI Command Register (PECI08, offset 0x08). Writing FIRE=1 launches a PECI transaction. STATUS holds the current state machine status. PIN_MONITORING lets software observe the PECI wire state.
func (p *PeciV1PECI) ReadCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCMD writes PECI Command Register (PECI08, offset 0x08). Writing FIRE=1 launches a PECI transaction. STATUS holds the current state machine status. PIN_MONITORING lets software observe the PECI wire state.
func (p *PeciV1PECI) WriteCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadRWLENGTH reads PECI Read/Write Length Register (PECI0C, offset 0x0C). Specifies the target device address, write byte count, read byte count, and whether to append an Assured Write FCS.
func (p *PeciV1PECI) ReadRWLENGTH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteRWLENGTH writes PECI Read/Write Length Register (PECI0C, offset 0x0C). Specifies the target device address, write byte count, read byte count, and whether to append an Assured Write FCS.
func (p *PeciV1PECI) WriteRWLENGTH(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadEXPECTEDFCS reads PECI Expected FCS Register (PECI10, offset 0x10). Expected read FCS, auto-computed write FCS, and expected write FCS. Written by software before launching a transaction for FCS checking.
func (p *PeciV1PECI) ReadEXPECTEDFCS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteEXPECTEDFCS writes PECI Expected FCS Register (PECI10, offset 0x10). Expected read FCS, auto-computed write FCS, and expected write FCS. Written by software before launching a transaction for FCS checking.
func (p *PeciV1PECI) WriteEXPECTEDFCS(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCAPTUREDFCS reads PECI Captured FCS Register (PECI14, offset 0x14). Read-only. Holds the FCS bytes captured from the last transaction. Compare CAPTURED_RD_FCS against EXPECTED_RD_FCS to verify integrity.
func (p *PeciV1PECI) ReadCAPTUREDFCS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCAPTUREDFCS writes PECI Captured FCS Register (PECI14, offset 0x14). Read-only. Holds the FCS bytes captured from the last transaction. Compare CAPTURED_RD_FCS against EXPECTED_RD_FCS to verify integrity.
func (p *PeciV1PECI) WriteCAPTUREDFCS(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadINTCTRL reads PECI Interrupt Control Register (PECI18, offset 0x18). Enable bits for each interrupt source and timing negotiation mode select.
func (p *PeciV1PECI) ReadINTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteINTCTRL writes PECI Interrupt Control Register (PECI18, offset 0x18). Enable bits for each interrupt source and timing negotiation mode select.
func (p *PeciV1PECI) WriteINTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadINTSTS reads PECI Interrupt Status Register (PECI1C, offset 0x1C). RW1C. Status bits mirror the INT_CTRL enable bit definitions. Also contains TIMING_RESULT [29:16] which holds the negotiated timing. Write 1 to a status bit to clear it.
func (p *PeciV1PECI) ReadINTSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteINTSTS writes PECI Interrupt Status Register (PECI1C, offset 0x1C). RW1C. Status bits mirror the INT_CTRL enable bit definitions. Also contains TIMING_RESULT [29:16] which holds the negotiated timing. Write 1 to a status bit to clear it.
func (p *PeciV1PECI) WriteINTSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadWRDATA0 reads PECI Write Data Buffer 0, bytes [3:0] (PECI20, offset 0x20).
func (p *PeciV1PECI) ReadWRDATA0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteWRDATA0 writes PECI Write Data Buffer 0, bytes [3:0] (PECI20, offset 0x20).
func (p *PeciV1PECI) WriteWRDATA0(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadWRDATA1 reads PECI Write Data Buffer 1, bytes [7:4] (PECI24, offset 0x24).
func (p *PeciV1PECI) ReadWRDATA1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteWRDATA1 writes PECI Write Data Buffer 1, bytes [7:4] (PECI24, offset 0x24).
func (p *PeciV1PECI) WriteWRDATA1(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadWRDATA2 reads PECI Write Data Buffer 2, bytes [11:8] (PECI28, offset 0x28).
func (p *PeciV1PECI) ReadWRDATA2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteWRDATA2 writes PECI Write Data Buffer 2, bytes [11:8] (PECI28, offset 0x28).
func (p *PeciV1PECI) WriteWRDATA2(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadWRDATA3 reads PECI Write Data Buffer 3, bytes [15:12] (PECI2C, offset 0x2C).
func (p *PeciV1PECI) ReadWRDATA3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteWRDATA3 writes PECI Write Data Buffer 3, bytes [15:12] (PECI2C, offset 0x2C).
func (p *PeciV1PECI) WriteWRDATA3(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadRDDATA0 reads PECI Read Data Buffer 0, bytes [3:0] (PECI30, offset 0x30).
func (p *PeciV1PECI) ReadRDDATA0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteRDDATA0 writes PECI Read Data Buffer 0, bytes [3:0] (PECI30, offset 0x30).
func (p *PeciV1PECI) WriteRDDATA0(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadRDDATA1 reads PECI Read Data Buffer 1, bytes [7:4] (PECI34, offset 0x34).
func (p *PeciV1PECI) ReadRDDATA1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteRDDATA1 writes PECI Read Data Buffer 1, bytes [7:4] (PECI34, offset 0x34).
func (p *PeciV1PECI) WriteRDDATA1(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadRDDATA2 reads PECI Read Data Buffer 2, bytes [11:8] (PECI38, offset 0x38).
func (p *PeciV1PECI) ReadRDDATA2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteRDDATA2 writes PECI Read Data Buffer 2, bytes [11:8] (PECI38, offset 0x38).
func (p *PeciV1PECI) WriteRDDATA2(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadRDDATA3 reads PECI Read Data Buffer 3, bytes [15:12] (PECI3C, offset 0x3C).
func (p *PeciV1PECI) ReadRDDATA3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteRDDATA3 writes PECI Read Data Buffer 3, bytes [15:12] (PECI3C, offset 0x3C).
func (p *PeciV1PECI) WriteRDDATA3(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadWRDATA4 reads PECI Write Data Buffer 4, bytes [19:16] (PECI40, offset 0x40).
func (p *PeciV1PECI) ReadWRDATA4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteWRDATA4 writes PECI Write Data Buffer 4, bytes [19:16] (PECI40, offset 0x40).
func (p *PeciV1PECI) WriteWRDATA4(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadWRDATA5 reads PECI Write Data Buffer 5, bytes [23:20] (PECI44, offset 0x44).
func (p *PeciV1PECI) ReadWRDATA5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteWRDATA5 writes PECI Write Data Buffer 5, bytes [23:20] (PECI44, offset 0x44).
func (p *PeciV1PECI) WriteWRDATA5(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadWRDATA6 reads PECI Write Data Buffer 6, bytes [27:24] (PECI48, offset 0x48).
func (p *PeciV1PECI) ReadWRDATA6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteWRDATA6 writes PECI Write Data Buffer 6, bytes [27:24] (PECI48, offset 0x48).
func (p *PeciV1PECI) WriteWRDATA6(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadWRDATA7 reads PECI Write Data Buffer 7, bytes [31:28] (PECI4C, offset 0x4C).
func (p *PeciV1PECI) ReadWRDATA7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteWRDATA7 writes PECI Write Data Buffer 7, bytes [31:28] (PECI4C, offset 0x4C).
func (p *PeciV1PECI) WriteWRDATA7(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadRDDATA4 reads PECI Read Data Buffer 4, bytes [19:16] (PECI50, offset 0x50).
func (p *PeciV1PECI) ReadRDDATA4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteRDDATA4 writes PECI Read Data Buffer 4, bytes [19:16] (PECI50, offset 0x50).
func (p *PeciV1PECI) WriteRDDATA4(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadRDDATA5 reads PECI Read Data Buffer 5, bytes [23:20] (PECI54, offset 0x54).
func (p *PeciV1PECI) ReadRDDATA5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteRDDATA5 writes PECI Read Data Buffer 5, bytes [23:20] (PECI54, offset 0x54).
func (p *PeciV1PECI) WriteRDDATA5(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadRDDATA6 reads PECI Read Data Buffer 6, bytes [27:24] (PECI58, offset 0x58).
func (p *PeciV1PECI) ReadRDDATA6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteRDDATA6 writes PECI Read Data Buffer 6, bytes [27:24] (PECI58, offset 0x58).
func (p *PeciV1PECI) WriteRDDATA6(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadRDDATA7 reads PECI Read Data Buffer 7, bytes [31:28] (PECI5C, offset 0x5C).
func (p *PeciV1PECI) ReadRDDATA7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteRDDATA7 writes PECI Read Data Buffer 7, bytes [31:28] (PECI5C, offset 0x5C).
func (p *PeciV1PECI) WriteRDDATA7(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

