// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// PwmV1PWMTACH ASPEED G6 PWM and Fan Tachometer controller. Base: 0x7E61_0000 (AST2600).  16 PWM outputs, 16 tachometer inputs. Each channel occupies 0x10 bytes; channels 0–15 at offsets 0x00–0xF0.
type PwmV1PWMTACH struct {
    Base uintptr
}

// ReadCH0PWMCTRL reads PWM Channel 0 Control Register (offset 0x00).
func (p *PwmV1PWMTACH) ReadCH0PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCH0PWMCTRL writes PWM Channel 0 Control Register (offset 0x00).
func (p *PwmV1PWMTACH) WriteCH0PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCH0PWMDUTY reads PWM Channel 0 Duty Cycle Register (offset 0x04).
func (p *PwmV1PWMTACH) ReadCH0PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCH0PWMDUTY writes PWM Channel 0 Duty Cycle Register (offset 0x04).
func (p *PwmV1PWMTACH) WriteCH0PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCH0TACHCTRL reads Tachometer Channel 0 Control Register (offset 0x08).
func (p *PwmV1PWMTACH) ReadCH0TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCH0TACHCTRL writes Tachometer Channel 0 Control Register (offset 0x08).
func (p *PwmV1PWMTACH) WriteCH0TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCH0TACHSTS reads Tachometer Channel 0 Status Register (offset 0x0C).
func (p *PwmV1PWMTACH) ReadCH0TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCH0TACHSTS writes Tachometer Channel 0 Status Register (offset 0x0C).
func (p *PwmV1PWMTACH) WriteCH0TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCH1PWMCTRL reads PWM Channel 1 Control Register (offset 0x10).
func (p *PwmV1PWMTACH) ReadCH1PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCH1PWMCTRL writes PWM Channel 1 Control Register (offset 0x10).
func (p *PwmV1PWMTACH) WriteCH1PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCH1PWMDUTY reads PWM Channel 1 Duty Cycle Register (offset 0x14).
func (p *PwmV1PWMTACH) ReadCH1PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCH1PWMDUTY writes PWM Channel 1 Duty Cycle Register (offset 0x14).
func (p *PwmV1PWMTACH) WriteCH1PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCH1TACHCTRL reads Tachometer Channel 1 Control Register (offset 0x18).
func (p *PwmV1PWMTACH) ReadCH1TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteCH1TACHCTRL writes Tachometer Channel 1 Control Register (offset 0x18).
func (p *PwmV1PWMTACH) WriteCH1TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadCH1TACHSTS reads Tachometer Channel 1 Status Register (offset 0x1C).
func (p *PwmV1PWMTACH) ReadCH1TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteCH1TACHSTS writes Tachometer Channel 1 Status Register (offset 0x1C).
func (p *PwmV1PWMTACH) WriteCH1TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadCH2PWMCTRL reads PWM Channel 2 Control Register (offset 0x20).
func (p *PwmV1PWMTACH) ReadCH2PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteCH2PWMCTRL writes PWM Channel 2 Control Register (offset 0x20).
func (p *PwmV1PWMTACH) WriteCH2PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadCH2PWMDUTY reads PWM Channel 2 Duty Cycle Register (offset 0x24).
func (p *PwmV1PWMTACH) ReadCH2PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteCH2PWMDUTY writes PWM Channel 2 Duty Cycle Register (offset 0x24).
func (p *PwmV1PWMTACH) WriteCH2PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadCH2TACHCTRL reads Tachometer Channel 2 Control Register (offset 0x28).
func (p *PwmV1PWMTACH) ReadCH2TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteCH2TACHCTRL writes Tachometer Channel 2 Control Register (offset 0x28).
func (p *PwmV1PWMTACH) WriteCH2TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadCH2TACHSTS reads Tachometer Channel 2 Status Register (offset 0x2C).
func (p *PwmV1PWMTACH) ReadCH2TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteCH2TACHSTS writes Tachometer Channel 2 Status Register (offset 0x2C).
func (p *PwmV1PWMTACH) WriteCH2TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadCH3PWMCTRL reads PWM Channel 3 Control Register (offset 0x30).
func (p *PwmV1PWMTACH) ReadCH3PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCH3PWMCTRL writes PWM Channel 3 Control Register (offset 0x30).
func (p *PwmV1PWMTACH) WriteCH3PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadCH3PWMDUTY reads PWM Channel 3 Duty Cycle Register (offset 0x34).
func (p *PwmV1PWMTACH) ReadCH3PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteCH3PWMDUTY writes PWM Channel 3 Duty Cycle Register (offset 0x34).
func (p *PwmV1PWMTACH) WriteCH3PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadCH3TACHCTRL reads Tachometer Channel 3 Control Register (offset 0x38).
func (p *PwmV1PWMTACH) ReadCH3TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteCH3TACHCTRL writes Tachometer Channel 3 Control Register (offset 0x38).
func (p *PwmV1PWMTACH) WriteCH3TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadCH3TACHSTS reads Tachometer Channel 3 Status Register (offset 0x3C).
func (p *PwmV1PWMTACH) ReadCH3TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteCH3TACHSTS writes Tachometer Channel 3 Status Register (offset 0x3C).
func (p *PwmV1PWMTACH) WriteCH3TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadCH4PWMCTRL reads PWM Channel 4 Control Register (offset 0x40).
func (p *PwmV1PWMTACH) ReadCH4PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteCH4PWMCTRL writes PWM Channel 4 Control Register (offset 0x40).
func (p *PwmV1PWMTACH) WriteCH4PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadCH4PWMDUTY reads PWM Channel 4 Duty Cycle Register (offset 0x44).
func (p *PwmV1PWMTACH) ReadCH4PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteCH4PWMDUTY writes PWM Channel 4 Duty Cycle Register (offset 0x44).
func (p *PwmV1PWMTACH) WriteCH4PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadCH4TACHCTRL reads Tachometer Channel 4 Control Register (offset 0x48).
func (p *PwmV1PWMTACH) ReadCH4TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteCH4TACHCTRL writes Tachometer Channel 4 Control Register (offset 0x48).
func (p *PwmV1PWMTACH) WriteCH4TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadCH4TACHSTS reads Tachometer Channel 4 Status Register (offset 0x4C).
func (p *PwmV1PWMTACH) ReadCH4TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteCH4TACHSTS writes Tachometer Channel 4 Status Register (offset 0x4C).
func (p *PwmV1PWMTACH) WriteCH4TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadCH5PWMCTRL reads PWM Channel 5 Control Register (offset 0x50).
func (p *PwmV1PWMTACH) ReadCH5PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteCH5PWMCTRL writes PWM Channel 5 Control Register (offset 0x50).
func (p *PwmV1PWMTACH) WriteCH5PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadCH5PWMDUTY reads PWM Channel 5 Duty Cycle Register (offset 0x54).
func (p *PwmV1PWMTACH) ReadCH5PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteCH5PWMDUTY writes PWM Channel 5 Duty Cycle Register (offset 0x54).
func (p *PwmV1PWMTACH) WriteCH5PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadCH5TACHCTRL reads Tachometer Channel 5 Control Register (offset 0x58).
func (p *PwmV1PWMTACH) ReadCH5TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteCH5TACHCTRL writes Tachometer Channel 5 Control Register (offset 0x58).
func (p *PwmV1PWMTACH) WriteCH5TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadCH5TACHSTS reads Tachometer Channel 5 Status Register (offset 0x5C).
func (p *PwmV1PWMTACH) ReadCH5TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteCH5TACHSTS writes Tachometer Channel 5 Status Register (offset 0x5C).
func (p *PwmV1PWMTACH) WriteCH5TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadCH6PWMCTRL reads PWM Channel 6 Control Register (offset 0x60).
func (p *PwmV1PWMTACH) ReadCH6PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteCH6PWMCTRL writes PWM Channel 6 Control Register (offset 0x60).
func (p *PwmV1PWMTACH) WriteCH6PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadCH6PWMDUTY reads PWM Channel 6 Duty Cycle Register (offset 0x64).
func (p *PwmV1PWMTACH) ReadCH6PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteCH6PWMDUTY writes PWM Channel 6 Duty Cycle Register (offset 0x64).
func (p *PwmV1PWMTACH) WriteCH6PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadCH6TACHCTRL reads Tachometer Channel 6 Control Register (offset 0x68).
func (p *PwmV1PWMTACH) ReadCH6TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteCH6TACHCTRL writes Tachometer Channel 6 Control Register (offset 0x68).
func (p *PwmV1PWMTACH) WriteCH6TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadCH6TACHSTS reads Tachometer Channel 6 Status Register (offset 0x6C).
func (p *PwmV1PWMTACH) ReadCH6TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteCH6TACHSTS writes Tachometer Channel 6 Status Register (offset 0x6C).
func (p *PwmV1PWMTACH) WriteCH6TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadCH7PWMCTRL reads PWM Channel 7 Control Register (offset 0x70).
func (p *PwmV1PWMTACH) ReadCH7PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteCH7PWMCTRL writes PWM Channel 7 Control Register (offset 0x70).
func (p *PwmV1PWMTACH) WriteCH7PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadCH7PWMDUTY reads PWM Channel 7 Duty Cycle Register (offset 0x74).
func (p *PwmV1PWMTACH) ReadCH7PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteCH7PWMDUTY writes PWM Channel 7 Duty Cycle Register (offset 0x74).
func (p *PwmV1PWMTACH) WriteCH7PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadCH7TACHCTRL reads Tachometer Channel 7 Control Register (offset 0x78).
func (p *PwmV1PWMTACH) ReadCH7TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteCH7TACHCTRL writes Tachometer Channel 7 Control Register (offset 0x78).
func (p *PwmV1PWMTACH) WriteCH7TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadCH7TACHSTS reads Tachometer Channel 7 Status Register (offset 0x7C).
func (p *PwmV1PWMTACH) ReadCH7TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteCH7TACHSTS writes Tachometer Channel 7 Status Register (offset 0x7C).
func (p *PwmV1PWMTACH) WriteCH7TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadCH8PWMCTRL reads PWM Channel 8 Control Register (offset 0x80).
func (p *PwmV1PWMTACH) ReadCH8PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteCH8PWMCTRL writes PWM Channel 8 Control Register (offset 0x80).
func (p *PwmV1PWMTACH) WriteCH8PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadCH8PWMDUTY reads PWM Channel 8 Duty Cycle Register (offset 0x84).
func (p *PwmV1PWMTACH) ReadCH8PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteCH8PWMDUTY writes PWM Channel 8 Duty Cycle Register (offset 0x84).
func (p *PwmV1PWMTACH) WriteCH8PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadCH8TACHCTRL reads Tachometer Channel 8 Control Register (offset 0x88).
func (p *PwmV1PWMTACH) ReadCH8TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteCH8TACHCTRL writes Tachometer Channel 8 Control Register (offset 0x88).
func (p *PwmV1PWMTACH) WriteCH8TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadCH8TACHSTS reads Tachometer Channel 8 Status Register (offset 0x8C).
func (p *PwmV1PWMTACH) ReadCH8TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteCH8TACHSTS writes Tachometer Channel 8 Status Register (offset 0x8C).
func (p *PwmV1PWMTACH) WriteCH8TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadCH9PWMCTRL reads PWM Channel 9 Control Register (offset 0x90).
func (p *PwmV1PWMTACH) ReadCH9PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteCH9PWMCTRL writes PWM Channel 9 Control Register (offset 0x90).
func (p *PwmV1PWMTACH) WriteCH9PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadCH9PWMDUTY reads PWM Channel 9 Duty Cycle Register (offset 0x94).
func (p *PwmV1PWMTACH) ReadCH9PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteCH9PWMDUTY writes PWM Channel 9 Duty Cycle Register (offset 0x94).
func (p *PwmV1PWMTACH) WriteCH9PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadCH9TACHCTRL reads Tachometer Channel 9 Control Register (offset 0x98).
func (p *PwmV1PWMTACH) ReadCH9TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteCH9TACHCTRL writes Tachometer Channel 9 Control Register (offset 0x98).
func (p *PwmV1PWMTACH) WriteCH9TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadCH9TACHSTS reads Tachometer Channel 9 Status Register (offset 0x9C).
func (p *PwmV1PWMTACH) ReadCH9TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// WriteCH9TACHSTS writes Tachometer Channel 9 Status Register (offset 0x9C).
func (p *PwmV1PWMTACH) WriteCH9TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x009c, uint32(val))
}

// ReadCH10PWMCTRL reads PWM Channel 10 Control Register (offset 0xA0).
func (p *PwmV1PWMTACH) ReadCH10PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteCH10PWMCTRL writes PWM Channel 10 Control Register (offset 0xA0).
func (p *PwmV1PWMTACH) WriteCH10PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadCH10PWMDUTY reads PWM Channel 10 Duty Cycle Register (offset 0xA4).
func (p *PwmV1PWMTACH) ReadCH10PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteCH10PWMDUTY writes PWM Channel 10 Duty Cycle Register (offset 0xA4).
func (p *PwmV1PWMTACH) WriteCH10PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadCH10TACHCTRL reads Tachometer Channel 10 Control Register (offset 0xA8).
func (p *PwmV1PWMTACH) ReadCH10TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteCH10TACHCTRL writes Tachometer Channel 10 Control Register (offset 0xA8).
func (p *PwmV1PWMTACH) WriteCH10TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// ReadCH10TACHSTS reads Tachometer Channel 10 Status Register (offset 0xAC).
func (p *PwmV1PWMTACH) ReadCH10TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteCH10TACHSTS writes Tachometer Channel 10 Status Register (offset 0xAC).
func (p *PwmV1PWMTACH) WriteCH10TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

// ReadCH11PWMCTRL reads PWM Channel 11 Control Register (offset 0xB0).
func (p *PwmV1PWMTACH) ReadCH11PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteCH11PWMCTRL writes PWM Channel 11 Control Register (offset 0xB0).
func (p *PwmV1PWMTACH) WriteCH11PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadCH11PWMDUTY reads PWM Channel 11 Duty Cycle Register (offset 0xB4).
func (p *PwmV1PWMTACH) ReadCH11PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteCH11PWMDUTY writes PWM Channel 11 Duty Cycle Register (offset 0xB4).
func (p *PwmV1PWMTACH) WriteCH11PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadCH11TACHCTRL reads Tachometer Channel 11 Control Register (offset 0xB8).
func (p *PwmV1PWMTACH) ReadCH11TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteCH11TACHCTRL writes Tachometer Channel 11 Control Register (offset 0xB8).
func (p *PwmV1PWMTACH) WriteCH11TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadCH11TACHSTS reads Tachometer Channel 11 Status Register (offset 0xBC).
func (p *PwmV1PWMTACH) ReadCH11TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteCH11TACHSTS writes Tachometer Channel 11 Status Register (offset 0xBC).
func (p *PwmV1PWMTACH) WriteCH11TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadCH12PWMCTRL reads PWM Channel 12 Control Register (offset 0xC0).
func (p *PwmV1PWMTACH) ReadCH12PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteCH12PWMCTRL writes PWM Channel 12 Control Register (offset 0xC0).
func (p *PwmV1PWMTACH) WriteCH12PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadCH12PWMDUTY reads PWM Channel 12 Duty Cycle Register (offset 0xC4).
func (p *PwmV1PWMTACH) ReadCH12PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteCH12PWMDUTY writes PWM Channel 12 Duty Cycle Register (offset 0xC4).
func (p *PwmV1PWMTACH) WriteCH12PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadCH12TACHCTRL reads Tachometer Channel 12 Control Register (offset 0xC8).
func (p *PwmV1PWMTACH) ReadCH12TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteCH12TACHCTRL writes Tachometer Channel 12 Control Register (offset 0xC8).
func (p *PwmV1PWMTACH) WriteCH12TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadCH12TACHSTS reads Tachometer Channel 12 Status Register (offset 0xCC).
func (p *PwmV1PWMTACH) ReadCH12TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteCH12TACHSTS writes Tachometer Channel 12 Status Register (offset 0xCC).
func (p *PwmV1PWMTACH) WriteCH12TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadCH13PWMCTRL reads PWM Channel 13 Control Register (offset 0xD0).
func (p *PwmV1PWMTACH) ReadCH13PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// WriteCH13PWMCTRL writes PWM Channel 13 Control Register (offset 0xD0).
func (p *PwmV1PWMTACH) WriteCH13PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00d0, uint32(val))
}

// ReadCH13PWMDUTY reads PWM Channel 13 Duty Cycle Register (offset 0xD4).
func (p *PwmV1PWMTACH) ReadCH13PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteCH13PWMDUTY writes PWM Channel 13 Duty Cycle Register (offset 0xD4).
func (p *PwmV1PWMTACH) WriteCH13PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadCH13TACHCTRL reads Tachometer Channel 13 Control Register (offset 0xD8).
func (p *PwmV1PWMTACH) ReadCH13TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteCH13TACHCTRL writes Tachometer Channel 13 Control Register (offset 0xD8).
func (p *PwmV1PWMTACH) WriteCH13TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadCH13TACHSTS reads Tachometer Channel 13 Status Register (offset 0xDC).
func (p *PwmV1PWMTACH) ReadCH13TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00dc))
}

// WriteCH13TACHSTS writes Tachometer Channel 13 Status Register (offset 0xDC).
func (p *PwmV1PWMTACH) WriteCH13TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00dc, uint32(val))
}

// ReadCH14PWMCTRL reads PWM Channel 14 Control Register (offset 0xE0).
func (p *PwmV1PWMTACH) ReadCH14PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteCH14PWMCTRL writes PWM Channel 14 Control Register (offset 0xE0).
func (p *PwmV1PWMTACH) WriteCH14PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadCH14PWMDUTY reads PWM Channel 14 Duty Cycle Register (offset 0xE4).
func (p *PwmV1PWMTACH) ReadCH14PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e4))
}

// WriteCH14PWMDUTY writes PWM Channel 14 Duty Cycle Register (offset 0xE4).
func (p *PwmV1PWMTACH) WriteCH14PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x00e4, uint32(val))
}

// ReadCH14TACHCTRL reads Tachometer Channel 14 Control Register (offset 0xE8).
func (p *PwmV1PWMTACH) ReadCH14TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e8))
}

// WriteCH14TACHCTRL writes Tachometer Channel 14 Control Register (offset 0xE8).
func (p *PwmV1PWMTACH) WriteCH14TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00e8, uint32(val))
}

// ReadCH14TACHSTS reads Tachometer Channel 14 Status Register (offset 0xEC).
func (p *PwmV1PWMTACH) ReadCH14TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec))
}

// WriteCH14TACHSTS writes Tachometer Channel 14 Status Register (offset 0xEC).
func (p *PwmV1PWMTACH) WriteCH14TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00ec, uint32(val))
}

// ReadCH15PWMCTRL reads PWM Channel 15 Control Register (offset 0xF0).
func (p *PwmV1PWMTACH) ReadCH15PWMCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f0))
}

// WriteCH15PWMCTRL writes PWM Channel 15 Control Register (offset 0xF0).
func (p *PwmV1PWMTACH) WriteCH15PWMCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00f0, uint32(val))
}

// ReadCH15PWMDUTY reads PWM Channel 15 Duty Cycle Register (offset 0xF4).
func (p *PwmV1PWMTACH) ReadCH15PWMDUTY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f4))
}

// WriteCH15PWMDUTY writes PWM Channel 15 Duty Cycle Register (offset 0xF4).
func (p *PwmV1PWMTACH) WriteCH15PWMDUTY(val uint32) {
    reg.Write(uint32(p.Base)+0x00f4, uint32(val))
}

// ReadCH15TACHCTRL reads Tachometer Channel 15 Control Register (offset 0xF8).
func (p *PwmV1PWMTACH) ReadCH15TACHCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f8))
}

// WriteCH15TACHCTRL writes Tachometer Channel 15 Control Register (offset 0xF8).
func (p *PwmV1PWMTACH) WriteCH15TACHCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00f8, uint32(val))
}

// ReadCH15TACHSTS reads Tachometer Channel 15 Status Register (offset 0xFC).
func (p *PwmV1PWMTACH) ReadCH15TACHSTS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00fc))
}

// WriteCH15TACHSTS writes Tachometer Channel 15 Status Register (offset 0xFC).
func (p *PwmV1PWMTACH) WriteCH15TACHSTS(val uint32) {
    reg.Write(uint32(p.Base)+0x00fc, uint32(val))
}

